### ISSUE TITLE
FastStream runs out of memory on Firefox

### ISSUE THREAD

**Issue by gt-nik** [Andrews54757/FastStream#1]
**Hi all,
This project seems very promising.**

OS: Windows 11 x64 Version 22H2 (OS Build 22621.2070)
OS RAM: 6GB
Browser: Firefox 118.0.2 portable
FastStream Video Player: 1.1.12

Video 1
=======
MP4 1.832GB video Page: https://www.antenna.gr/watch/1676579/i-magissa-epeisodio-16
1. CPU Load 100% During video buffering (even if option "Predownload entire video in the background if possible" is disabled).
2. All my internet download speed (100 GBps) is used.
3. Very high CPU Load even after "100% Buffered".
4. 1, 2 and 3 exist even if video is not currently playing (even if video not started at all)
5. After some time Firefox Crashed (details button is disabled).
6. Firefox restarted and try again.
7. Now 1, 2, 3, and 4 exist but Firefox not crashed.
8. I press the download button, ask for name, download started but failed

Video 2
=======
mpd video Page: https://www.ertflix.gr/vod/vod.313312-3os-orophos-42
1. CPU Load 100% During video buffering (even if option "Predownload entire video in the background if possible" is disabled).
2. All my internet download speed (100 GBps) is used.
3. Very high CPU Load even after "100% Buffered".
4. 1, 2 and 3 exist even if video is not currently playing (even if video not started at all)
5. I press the download button, ask for name, video downloaded successfully as mp4
6. Other video qualities downloaded successfully as mp4

Video 3
=======
TS video Page: https://www.skaitv.gr/episode/seires/oi-pantheoi/2023-10-25-21
1. When i toggle extension ON (toolbar button), the video frame become hidden.
2. I have to toggle extension OFF( toolbar button), and refresh the page to see the original video frame again.

Video 4
=======
MP4 1.302GB video Page: https://www.alphatv.gr/show/fonoi-sto-kabanario/?vtype=player&vid=57574&showId=1531&year=2023
1. same as video 1

**Thanks Andrew
Best regards**

**Please note that the above tested with Firefox portable - "modified" cache settings (about:config):**
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk_cache_ssl", false);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.check_doc_frequency", 3);
user_pref("browser.cache.memory.enable", true);

**Comment by Andrews54757** [comment]
Thanks for the report! Can you try disabling the "Automatically analyze sequential videos for intros/outros" option in settings? It could be that your computer doesn't have enough processing power.

I also can't access those videos in the United States, they are only available in Greece. Do you have any other links to videos where you see the same problem?

**Comment by gt-nik** [comment]
Hi,
I edit my 1st post adding Firefox portable "cache" settings (may be useful).

I have a little time to perform some more tests.
Note that next test performed using Firefox portable default cache settings (about:config) (so disk cache is enabled now)

1. Open MP4 1.832GB video Page: https://www.antenna.gr/watch/1676579/i-magissa-epeisodio-16
- a) Video in not playing (waitting for "play" button to start)
- b) FastStream Video Player is not enabled yet.
- c) RAM=26%

2. FastStream Video Player is enabled by toolbar button
- a) option "Predownload entire video in the background if possible" is disabled.
- b) option "Automatically analyze sequential videos for intros/outros"  is disabled.
- c) FastStream Video Player is buffering the video !!! (it seems it does not respect 2a and 2b options)
- d) All my internet download speed (100 GBps) is used.
- e) Very high CPU Load.
- f) if i press the download button it says: "Video has not finished downloading yet! Are you sure you want to save it?" i press "No".
- g) RAM is increasing

3. FastStream Video Player: 100% Buffered
- a) RAM=58%

4. FastStream Video Player: download button pressed
- a) Enter a name for the file
- b) system unstable
- c) RAM=99%
- d) Firefox Crashed

have a good day

**Comment by Andrews54757** [comment]
@gt-nik can you open Firefox's developer tools and copy and paste the output from the logger? I can't access the video you provided because it is blocked for people in the United States.

**Comment by Andrews54757** [comment]
I've also fixed the bug that causes the predownload option to be ignored. The fix will be available on the next release.

Other than that issue, I am unable to reproduce your crashing problem. The player works without issues on firefox on my test streams. Since I can't reproduce the problem, I don't think I can pinpoint the source of your issue without getting a debug log. If you are unsure of how to do this, please see [Firefox's guide](https://firefox-source-docs.mozilla.org/devtools-user/web_console/) to opening the javascript console. On Windows, pressing `Ctrl+Shift+K` should open the console.

Still, thank you so much for reporting bugs!

**Comment by gt-nik** [comment]
**Test 1**
1. Open MP4 1.832GB video Page: https://www.antenna.gr/watch/1676579/i-magissa-epeisodio-16
a) Firefox not crashed but download is failed 
b) Console log of 1a > file: [console-export-2023-10-27_8-55-49[page].txt](https://github.com/Andrews54757/FastStream/files/13185657/console-export-2023-10-27_8-55-49.page.txt)



**Test 2**
1. Open: about:debugging#/runtime/this-firefox
a) FastStream Video Player > Inspect

2. Open MP4 1.832GB video Page: https://www.antenna.gr/watch/1676579/i-magissa-epeisodio-16
a) Video in not playing (waitting for "play" button to start)
b) FastStream Video Player is not enabled yet.
c) RAM=25%

3. FastStream Video Player is enabled by toolbar button
a) option "Predownload entire video in the background if possible" is disabled.
b) option "Automatically analyze sequential videos for intros/outros"  is disabled.
c) FastStream Video Player is buffering the video !!! (it seems it does not respect 3a and 3b options)
d) All my internet download speed (100 GBps) is used.
e) Very high CPU Load.

4. Gah. Your tab just crashed.
a) Console log of 1a > file: [console-export-2023-10-27_9-5-15 [debug].txt](https://github.com/Andrews54757/FastStream/files/13185662/console-export-2023-10-27_9-5-15.debug.txt)

**Comment by Andrews54757** [comment]
@gt-nik Thank you for providing me with this information! Reading the logs, I do not see anything out of the ordinary. I believe your computer is running out of memory. To try to address this problem, I have implemented a 150 MB/s data limit https://github.com/Andrews54757/FastStream/commit/5bbb4ba4a6ebcf53561f5499f68ac11966c0235b so that the computer is able to have extra time to consolidate memory.

The fix is already live at https://addons.mozilla.org/en-US/firefox/addon/faststream/
Please update the extension and let me know if it worked.

**Comment by Andrews54757** [comment]
Preliminary investigation of Firefox's implementation of `Blob` seems to indicate that they are only stored in memory unlike in Chrome, where they are stored as a temporary file. This may be the reason why your computer is running out of memory. There is unfortunately not much I can do about this as it is a browser issue. I will try to think of a solution. Perhaps Firefox might be able to store the data properly if I use IndexedDB.

**Comment by gt-nik** [comment]
**New Test (still old version FastStream Video Player: 1.1.12)**
1. Open MP4 0.954GB video Page: https://bestvidhd.site/embed-ye6svaxbhod2-950x480.html
- a) RAM=29%
- ...........
- b) FastStream Video Player: 100% Buffered
- c) RAM=59%

2. FastStream Video Player: download button pressed
- a) Enter a name for the file
- b) firefox's save as window open asking for save as location and name (already exist the name from 4a)
- c) system unstable
- d) RAM=99%
- e) Firefox Crashed

**Restart Firefox, and follow the same procedure... but now**

3. Open MP4 0.954GB video Page: https://bestvidhd.site/embed-ye6svaxbhod2-950x480.html
- a) RAM=29%
- ...........
- b) FastStream Video Player: 100% Buffered
- c) RAM=61%

4. FastStream Video Player: download button pressed
- a) Enter a name for the file (in FastStream Video Player popup message)
- b) When i press OK button and the firefox's save as window open asking for save as location and name (already exist the name from 4a), this is the time that my OS getting "crazy"!!!
- c) After some tries, i managed to press very-very-very quick the save button.
- d) RAM seems to decrease quick (i think before reach too high values)
- e) mp4 saved SUCCESSFULLY
- f) RAM=68% (Tab still opened, FastStream Video Player: 100% Buffered)
- g) RAM=41% (video Tab closed)

**Comment by gt-nik** [comment]
Andrews54757 said: Perhaps Firefox might be able to store the data properly if I use IndexedDB.

or in firefox's download folder (as firefox do using FileName.part files until complete)

**Comment by gt-nik** [comment]
FastStream Video Player: 1.1.14.2
1. Open MP4 1.832GB video Page: https://www.antenna.gr/watch/1676579/i-magissa-epeisodio-16
- RAM=30%
- option "Predownload entire video in the background if possible" is disabled.
- option "Automatically analyze sequential videos for intros/outros"  is disabled.
- FastStream Video Player is buffering the video !!!
- Very low internet download speed is used.
- Very low CPU Load.
- if i press the download button it says: "Video has not finished downloading yet! Are you sure you want to save it?" i press "No".
- RAM is increasing
- Buffer is never getting 100%, so video is playing normally with low resources, but cannot be downloaded.


maybe i have to watch all the video first to be buffered?



What if player and downloader run separately?
When user press the download button and give the filename, then all video will be buffered and downloaded at the same time (storing the temporary data to disk until compete).

In my opinion, if you decide to save the temporary data to disk,
it is preferred to use the download folder,
because data will be saved to a high speed disk (maybe SSD) and not in a USB flash drive (if a portable firefox is used running from a removable drive)

thanks

**Comment by Andrews54757** [comment]
@gt-nik I have published a fix for the issue. The buffer will now use a temporary IndexedDB database so it doesn't use up memory. Please update the extension and try playing videos with the "predownload entire video" option set.

Note: Video downloads may still suffer from issues as I haven't updated that feature yet.

**Comment by gt-nik** [comment]
Browser: Firefox **119.0.0** portable (running from HDD)
FastStream Video Player: **1.1.14.3**

**Firefox portable - "modified" cache settings (about:config):**
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk_cache_ssl", false);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.check_doc_frequency", 3);
user_pref("browser.cache.memory.enable", true);


1. Open MP4 1.832GB video Page: https://www.antenna.gr/watch/1676579/i-magissa-epeisodio-16
- RAM=33%
- option "Predownload entire video in the background if possible" is enabled.
- option "Automatically analyze sequential videos for intros/outros" is disabled.
- FastStream Video Player is buffering the video !!!
- Normal Internet download speed during buffering.
- Normal CPU Load during buffering.
- if i press the download button it says: "Video has not finished downloading yet! Are you sure you want to save it?" i press "No".
- Player is running very smooth and without any unusual efects
- Video 100% Buffered
- RAM=38%
- download button pressed
- Enter a name for the file
- Firefox internal "save as" dialog
- CPU load and RAM very low
- Firefox shows that download completed but the size on disk is only 132KB (not 1.832GB)
- video file opened in Notepad++ - it is text  https://github.com/Andrews54757/FastStream/assets/62329227/ed730bf9-3085-442b-888d-7047182a8545
- Temporary IndexedDB database path "...FirefoxPortable\Data\profile\storage\default\moz-extension+++..." size 1.9GB+
- Toggle FastStream off (toolbar button) has no effect (FastStream Video Player is still here)
- Video Tab closed > Temporary IndexedDB database size released to 480KB


Additional Notes:
- FastStream toolbar button: some times i have to "toggle on - refresh page - toggle on again" in order the player to appear.
- FastStream toolbar button: all the time "Toggle off" has no effect (FastStream Video Player is still here)
- When option "Predownload entire video in the background if possible" is disabled, player is still working good and ALL the video has not to Predownloaded.

Have a nice day

**Comment by Andrews54757** [comment]
@gt-nik I've published a fix for the download issue. Downloads will now also use IndexedDB so it won't run out of memory. Please update the extension and try downloading videos again.

**Comment by gt-nik** [comment]
Browser: Firefox 119.0.0 portable (running from HD)
FastStream Video Player: 1.1.15.0

Firefox portable - "modified" cache settings (about:config):
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.disk.capacity", 0);
user_pref("browser.cache.disk_cache_ssl", false);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.check_doc_frequency", 3);
user_pref("browser.cache.memory.enable", true);

FastStream Video Player options:
option "Predownload entire video in the background if possible" is enabled.
option "Automatically analyze sequential videos for intros/outros" is disabled.


1. Open MP4 1.3GB video Page: https://www.alphatv.gr/show/fonoi-sto-kabanario/?vtype=player&vid=57674&showId=1531&year=2023
- Buffering 2C=188sec, Local data processing and saving to disk=222sec (Saving=148sec + until Firefox SaveAs dialog=6sec + Firefox Saving to disk=68sec) [1. console-export-2023-10-29_9-30-23.txt](https://github.com/Andrews54757/FastStream/files/13197518/1.console-export-2023-10-29_9-30-23.txt)




2. Open MP4 1.832GB video Page: https://www.antenna.gr/watch/1676579/i-magissa-epeisodio-16
- Buffering 5C=356sec, Local data processing and saving to disk=376sec (Saving=278sec + until Firefox SaveAs dialog=7sec + Firefox Saving to disk=91sec) [2. console-export-2023-10-29_9-50-41.txt](https://github.com/Andrews54757/FastStream/files/13197520/2.console-export-2023-10-29_9-50-41.txt)




3. Open TS 61min31sec video Page: https://www.skaitv.gr/episode/seires/oi-pantheoi/2023-10-26-21
- video file: https://videostream.skai.gr/skaivod/_definst_/mp4:skai/2_Do-Not-Delete_Shows/Pantheoi/S00133026_PANTHEOI_S01E026.mp4/chunklist.m3u8
- when FastStream Video Player is enabled, original player become hidden but no player is visible (empty space). Page refresh, player disable/enable again has the effect the original player to show/hide but FastStream Video Player never become visible.
- watching the internet connection activity it seems that video is buffering (even player is not visible) [3. console-export-2023-10-29_10-3-30.txt](https://github.com/Andrews54757/FastStream/files/13197521/3.console-export-2023-10-29_10-3-30.txt)


NOTE:
All video i tried not mentioned here (also one with many qualities) downloaded successfully (ecxept the above #3)
but the Local data processing and saving to disk takes very long time.

**Comment by Andrews54757** [comment]
@gt-nik Saving to disk taking a long time is inevitable if you are on Firefox and you have a low-end computer. Firefox [does not support](https://mozilla.github.io/standards-positions/#native-file-system) the FileSystem API. It also doesn't support service workers in extension contexts. This means that it cannot stream files directly to the downloads folder and must use IndexedDB. Try using Chrome, it has a better implementation of `Blobs` that allow for faster file saving.

**Comment by Andrews54757** [comment]
For the issue of the player being invisible, that is likely because the website uses some JavaScript to remove the player from the page. This is a very difficult problem to fix, and it may even be impossible. In the meantime:
1. Open a new tab, and press the faststream icon to open the player
2. Go to the website with the video in a seperate tab
3. Click the golden chain icon button to open the sources browser
4. Find the video source you want on the list, and press "Play"

**Comment by gt-nik** [comment]
For the issue of the player being invisible, i did next:
1. Open a new tab, and press the faststream icon to open the player
2. Click on "toggle sources browser" button and paste video source url: https://videostream.skai.gr/skaivod/_definst_/mp4:skai/2_Do-Not-Delete_Shows/Pantheoi/S00133026_PANTHEOI_S01E026.mp4/chunklist.m3u8
3. press play and video played and downloaded successfully!!!

Thanks

**Comment by Andrews54757** [comment]
@gt-nik After some investigation, it appears as though the website is setting the padding of the player iframe. I've fixed the issue by overriding that to 0. I've updated the Firefox extension with a version containing the fix (v1.1.15.1). Please update the extension to that version and try again.

**Comment by gt-nik** [comment]
> Please update the extension to that version and try again.

Yes version 1.1.15.1 fix the issue
Thank you Andrew

**Comment by gt-nik** [comment]
> Try using Chrome

I tried Edge v118.0.2088.76 already installed in my windows 11 with FastStream v1.1.14
and here are my results.

1. Open MP4 1.832GB video Page: https://www.antenna.gr/watch/1676579/i-magissa-epeisodio-16
- FIREFOX: Buffering 5C=356sec, Local data processing and saving to disk=376sec - TOTAL=732sec
- Edge: Buffering 5C=230sec, Local data processing and saving to disk=12sec - TOTAL=242sec
- Neat download manager: Download=112sec, Local data merging=52sec - TOTAL=164sec

NOTE:
- Neat download manager (Firefox extension + windows application) has partial support for video files, download but does not convert TS to mp4 and has no support for m3u8, mpd formats)
- I prefer Firefox as browser+FastStream as video player, but Edge+FastStream is by far faster for those like me who downloading many movies. I wish Firefox to add the needed functions for better/faster file saving etc.

**Comment by Andrews54757** [comment]
Upcoming release 1.1.17 will have concurrent save + download feature https://github.com/Andrews54757/FastStream/commit/f02bbcfb3d4f8842a5c69e49dedd2e63b186f8fb so that you can save videos while they are being downloaded. This should improve download/saving speeds.
