### ISSUE TITLE
[BUG] Other extension doesn't work on FastStream

### ISSUE THREAD

**Issue by TakeOFFF** [Andrews54757/FastStream#104]
**Describe the bug**
GREAT TOOL, THX TO THE DEV BUT IT DOESNT WORK TOGETHER WITH ANOTHER IMPORTANT EXTENSIONS *"VIDEOTRANSFORMATOR"* WHICH LETS ME MIRROW VIDEOS (https://chromewebstore.google.com/u/1/detail/video-transformer/cafdfogfbjpgdmppmdchgcggdepfbndo)

**Version**
Version
1.2.25.1

**Platform**
The browser you are using Brave/Chrome/Firefox/etc..

**Steps to Reproduce**
Please tell us how to reproduce the issue. A URL to a specific video is encouraged.

**Comment by Andrews54757** [comment]
This is not a bug. Other chrome extensions cannot interact with FastStream because it is contained in an Iframe. You can request a mirroring feature instead.
