### ISSUE TITLE
Cant Drag Button into the "hidden" bar

### ISSUE THREAD

**Issue by Nvertd** [Andrews54757/FastStream#105]
In the video player, all the buttons on the bottom right (sources, fullscreen, settings, download.etc) can be draged into the hidden section (the three dots in a circle icon) except for **resolution settings** and **playback rate setting**.

**Comment by Andrews54757** [comment]
What do you mean? You can't see the icons? you can't move them at all?

**Comment by Andrews54757** [comment]
Oh, I understand now. Try doing it in reorder mode. (click and hold down on the icons)

**Comment by Nvertd** [comment]
Yes and upon holding, as soon as you click(for playback speed and resolution at least) you go into the drop-down list instead of reordering.

**Comment by Andrews54757** [comment]
Fixed
