### ISSUE TITLE
Set Default Resolution

### ISSUE THREAD

**Issue by Nvertd** [Andrews54757/FastStream#106]
Specify the default resolution the player will attemtp to stream at.

**Comment by Andrews54757** [comment]
See https://github.com/Andrews54757/FastStream/issues/10#issuecomment-1849239863

**Comment by Nvertd** [comment]
@Andrews54757 Based on #10 does that mean this is a bug? My monitor is 1920x1080, but the video player keeps choosing 854x480 when i am in full screen
