### ISSUE TITLE
[Feature] Ability to flip video horizontally

### ISSUE THREAD

**Issue by TakeOFFF** [Andrews54757/FastStream#109]
**Is your feature request related to a problem? Please describe.**
Id like to request a mirrowing + rotating feature for FastStream because other chrome extensions cannot interact with FastStream
 :(

**Describe the solution you'd like**
Mirrowing + rotating feature for FastStream

**Additional context**
It would be great if you could add those features with keyboard shortcuts.

Nonetheless great tool, thx a lot!!

**Comment by Andrews54757** [comment]
I'll add after I refactor the video configuration settings.

**Comment by TakeOFFF** [comment]
Thank you🤩🫡

**Comment by Andrews54757** [comment]
Added two keybinds for flipping and rotating a video. Will be available in V1.3.1
