### ISSUE TITLE
[Feature] Youtube History registering video watched with FastStream

### ISSUE THREAD

**Issue by menachemshapiro** [Andrews54757/FastStream#110]
**Is your feature request related to a problem? Please describe.**
I'm not sure if this is a bug or a feature, but I have FastStream set to automatically load on youtube. When I watch the video, it doesn't get registered in my history as a watched video. So youtube just keeps recommending the same videos over and over, because it doesn't think I watched them. 

**Describe the solution you'd like**
Is there a way to make youtube see that I've watched the video?

**Describe alternatives you've considered**
Turn off FastStream, and only turn it on when I need to use its functionality. But I'd prefer to use FastStream all the time.

**Comment by Andrews54757** [comment]
This is not a problem I can solve. Google doesn't count views from external players. If they did, it would be very easy to fake views.

**Comment by ChromiaCat** [comment]
> This is not a problem I can solve. Google doesn't count views from external players. If they did, it would be very easy to fake views.

There might be an indirect way. I've noticed the YT player loading before FastStream replaces it and it seems that's enough for YT to think I've watched the entire video, If there's a way to consistently delay FastStream enough for YT to register the video in history that would work. Might be something worth for the back burner.

**Comment by pintassilgo** [comment]
[PocketTube](https://pockettube.io/) extension provides a button to mark video as watched without even loading it. When you click to mark as watched, the video is registered in [Youtube Activity History](https://myactivity.google.com/product/youtube). How it's done I have no idea and this extension has obfuscated code, but I guess this proves it's somehow doable.

**Comment by aqtoo** [comment]
> [PocketTube](https://pockettube.io/) extension provides a button to mark video as watched without even loading it. When you click to mark as watched, the video is registered in [Youtube Activity History](https://myactivity.google.com/product/youtube). How it's done I have no idea and this extension has obfuscated code, but I guess this proves it's somehow doable.

So the potential for FastStream to make a video as watched when it's own player ends is possible?

**Comment by ChromiaCat** [comment]
> > [PocketTube](https://pockettube.io/) extension provides a button to mark video as watched without even loading it. When you click to mark as watched, the video is registered in [Youtube Activity History](https://myactivity.google.com/product/youtube). How it's done I have no idea and this extension has obfuscated code, but I guess this proves it's somehow doable.
> 
> So the potential for FastStream to make a video as watched when it's own player ends is possible?

Possibly but unless Andrews or anyone else is willing to delve into PocketTube code the option to delay player replacing is the best we'll get at tricking YT to mark a video as watched.

**Comment by aqtoo** [comment]
Well by my logic why not just make it be marked as watch when FastStream's player reaches the end of the video?

Not the prettiest solution, but it's better than no watch history.

**Comment by Andrews54757** [comment]
FastStream isn't like most other youtube-related extensions, which only interface with Youtube's web client to do their work. Instead, FastStream is more like a third-party client that works independently of it. Barring scraping authentication tokens from Youtube's website (which is dangerous and likely breaks policy), Faststream has no way to associate the videos you watched with your google account.

**Comment by aqtoo** [comment]
> Faststream has no way to associate the videos you watched with your google account.

Well a solution was offered, how it would be executed in code I have no clue, but since another YouTube Extension has the ability to click a button to mark a video as watched, which DOES show up in your history.

My solution thought out to be when FastStream is done playing a YouTube video, send that same request to mark it as watched to YouTube, ONLY on YouTube, as a majority of users probably use this for YT.

**Comment by ChromiaCat** [comment]
> FastStream isn't like most other youtube-related extensions, which only interface with Youtube's web client to do their work. Instead, FastStream is more like a third-party client that works independently of it. Barring scraping authentication tokens from Youtube's website (which is dangerous and likely breaks policy), Faststream has no way to associate the videos you watched with your google account.

Maybe if there's a field in options that the user pastes whichever cookie is needed and FS uses that to sync watched videos.

**Comment by ale5000-git** [comment]
If this is done it would be nice to have an option since there will also be users that prefer to don't have their actions saved.

**Comment by Andrews54757** [comment]
Done. You can control it via the save progress config.

https://github.com/Andrews54757/FastStream/commit/349df8d412bc1f8a5d47f80f83527839b5b693bb
