### ISSUE TITLE
[Feature]Close Menu When Mouse Leaves Menu

### ISSUE THREAD

**Issue by Nvertd** [Andrews54757/FastStream#113]
As the titles suggest, close the menues like resolution, playback speed etc when the mouse leaves the menu box.
so essentialy when you click one the icon the menu box opens and stays there, once the mouse enters and then leaves (or after clicking and leaveing), the menu closes automatically. Instead of having to press the icon again to close the menu.

**Comment by Andrews54757** [comment]
Persistent menus are intended. See #21
