### ISSUE TITLE
[Feature] Solution for bluetooth earphone delay issues or integration of Chrome Audio Delay Patch?

### ISSUE THREAD

**Issue by i1itione** [Andrews54757/FastStream#116]
After testing, when playing videos through the FastStream player, the Chrome Audio Delay Patch seems to have no effect. 
According to the function introduction of the Chrome Audio Delay Patch, it seems to add delay to the video to synchronize with 
the audio delay. I wonder if it is possible to achieve a similar effect directly in FastStream, or to support/integrate this Patch?

Chrome Audio Delay Patch:
https://github.com/gurux13/chrome-audio-delay

**Comment by Andrews54757** [comment]
This can be done, but doing it correctly is Very Hard™. The simplest solution is to play the audio and video separately and add a delay to the video. However, it will be almost impossible to guarantee that they will always be in sync, especially across different hardware.

I believe that a satisfactory fix to this problem will require changes to the browser itself. I suggest writing to the Chrome developers to implement this natively.

As for the patch you provided, it doesn't indicate that FastStream needs to integrate anything special. It should work with FastStream. Maybe it's a bug?

**Comment by Andrews54757** [comment]
Added a video delay option
