### ISSUE TITLE
[BUG] Player icons (Quality, Volume, etc,) invisible on first page load

### ISSUE THREAD

**Issue by nilsgng** [Andrews54757/FastStream#117]
**Describe the bug**
The Icons in the Player for Quality, Volume etc are sometimes invisible when the youtube page first loads, this is mostly fixed by reloading the page (f5), it is worth mentioning that the time and the red percentage indicators are still visible, only the icons themselves are invisible. You can still click on them and they open the menu they are supposed to, just not visible.

**Version**
v1.3.0
has appeared for me for the last few versions aswell, just looked into it today and analysed when it exactly happens

**Platform**
Firefox 115.8.0esr 64bit

**Steps to Reproduce**
Appears most often for me when opening a new browser window and going on youtube, often it is the first video that has the icons missing, by refreshing the page, the bug should be fixed for the remaining session.

**Comment by Andrews54757** [comment]
Sounds like a bug with Firefox, not FastStream. FastStream's icons are simple SVGs. they shouldn't fail.

**Comment by nilsgng** [comment]
thanks for the reply, i'll keep an eye on the issue and also check compatibility with my other addons, even tho they shouldnt affect anything regarding faststream

**Comment by Andrews54757** [comment]
I've split the icons across two files in case that helps.

**Comment by Andrews54757** [comment]
Let me know if you are still having this issue `>=1.3.1`

**Comment by nilsgng** [comment]
unfortunately still have the issue, But I really think it is a firefox/addon issue at this point

**Comment by sudosign** [comment]
reproduced on mullvad browser(also FF addons) on youtube. same steps to reproduce, but (i think) only happens when using the regex not sure tho

**Comment by Andrews54757** [comment]
Closing as stale. Unfortunately, as this is a browser issue, there is not much I can do to fix it for now.
