### ISSUE TITLE
[Feature] Download List

### ISSUE THREAD

**Issue by WagnerQuetsia** [Andrews54757/FastStream#118]
Sometimes I need to download several videos, so I need to open several tabs.

Is it possible to add videos to a download list? If I advance to the next video in the same tab, the progress is lost.

I need to wait for the download to finish and then start the next video download.

**Comment by Andrews54757** [comment]
Current design of the extension does not make this possible. But besides that, I do not recommend using FastStream or other browser extensions to mass-download videos. Being browser-based, they are inefficient compared to actual download manager apps. For example, it incurs more ssd writes, which may reduce the lifespan of your SSD. FastStream (and other browser based extensions) are better suited for single downloads.
