### ISSUE TITLE
[Feature] Autoplay next video in a playlist (Youtube)

### ISSUE THREAD

**Issue by Nvertd** [Andrews54757/FastStream#119]
I don't know if this counts as the same feature request as in #103. But being able to play next video in a playlist (on Youtube) would be nice.

**Comment by Andrews54757** [comment]
I stripped out playlist support a while ago on YoutubeJS to reduce file size. I can try integrating it later

**Comment by Andrews54757** [comment]
Done

**Comment by Nvertd** [comment]
Auto Play next video in playlist requires the browser to be in the foreground. It stops auto playing when the browser is the the background.
