### ISSUE TITLE
[Feature] Add support for Invidious instances

### ISSUE THREAD

**Issue by Efiyo** [Andrews54757/FastStream#120]
**Is your feature request related to a problem? Please describe.**
- The Youtube frontend is very sluggish, hence I went to solutions like your project Faststream which fixes all the issues of their video player and Invidious, which fixes the issue with their bloated frontend. I unfortunately have not found a way to use both at the same time so I could use the Faststream player on an Invidious instance.

**Describe the solution you'd like**
- I'd like if there was a way for Faststream video player to work with Invidious instances if possible.

**Describe alternatives you've considered**

**Additional context**

**Comment by Andrews54757** [comment]
I'm not sure what you mean. I just tried using FastStream on a public invidious instance. It works fine.

**Comment by Andrews54757** [comment]
![image](https://github.com/Andrews54757/FastStream/assets/13282284/36293721-7021-4e42-a934-f851d444718f)

**Comment by Efiyo** [comment]
That is interesting, apologies for not testing more, I've just tried it on Firefox Nightly 126.0  on a private instances and it's not working, I will report back with testing on different profiles to see if some settings maybe affect it. On the other hand, it does work with Chrome 122.0 on Windows.

EDIT: Tested some more, on a private instance I am hosting it's not working, on public it does even on Firefox. Is there a way to debug to figure out why it's not working on a private instance?

**Comment by Andrews54757** [comment]
I've added support for custom Youtube URLS. https://github.com/Andrews54757/FastStream/commit/f2bda9dcf51cef913634173ecaf654ee8b69ba1b

To set up, add a custom source pattern like so:
```
youtube /^https:\/\/yewtu\.be\/watch\?v\=.*$/
```

See https://regex101.com/r/mWOF8r/1 for an explanation of what the regex is.
