### ISSUE TITLE
Saving is broken for some sites

### ISSUE THREAD

**Issue by RNavarro3000** [Andrews54757/FastStream#121]
**Describe the bug**
Saving videos on twitter.com and vimeo.com is broken, but I can save videos from youtube.com just fine.

**Version**
1.3.2

**Platform**
Firefox on Windows

**Steps to Reproduce**
Can't download these test videos:
https://vimeo.com/channels/staffpicks/818944000
https://twitter.com/gunsnrosesgirl3/status/1773233651808981486

**Comment by Andrews54757** [comment]
Fixed

**Comment by RNavarro3000** [comment]
Many thanks...
