### ISSUE TITLE
[BUG] Doesn't detect video player on mega.nz

### ISSUE THREAD

**Issue by itszux** [Andrews54757/FastStream#122]
**Describe the bug**
I used the extension only for a short time and it worked always except on this website (mega.nz) it doesn't detect the video player

**Version**
1.3.3

**Platform**
Brave on windows 10.

**Steps to Reproduce**
example: https://mega.nz/file/4i8FDRrB#5Lbl905zE7IKPAtjz8qdP_44HL79I7vTJA9l2XIMJ5M

**Comment by Andrews54757** [comment]
Mega uses a client side encryption algorithm. Such encryption, DRM, is not supported by FastStream.
