### ISSUE TITLE
[BUG] Rumble - No option to change resolutions in FastStream

### ISSUE THREAD

**Issue by RNavarro3000** [Andrews54757/FastStream#125]
**Describe the bug**
Native player presents four resolutions for the video below. FastStream doesn't show Quality button and defaults to 480p.

**Version**
1.3.3

**Platform**
Firefox on Windows, Firefox on Linux, Chrome on Linux

**Steps to Reproduce**
https://rumble.com/v4o3nqh-barstool-pizza-review-prima-pizzeria-schenectady-ny.html

**Comment by Andrews54757** [comment]
The website uses multiple MP4 files to represent different qualities, it is not a stream. Only streams have selectable quality levels. There is no way for FastStream to know about all the mp4 files ahead of time.

Turn on FastStream after selecting the quality you want in the default player. Then FastStream will pick up the mp4 file with the quality you select.
