### ISSUE TITLE
[Feature] Put version number in Settings window

### ISSUE THREAD

**Issue by RNavarro3000** [Andrews54757/FastStream#126]
**Is your feature request related to a problem? Please describe.**
I know FastStream flashes its version number at the start but its only a fraction of a second, then overwritten by the percentage of the video loading. Most times my aging eyes just can't capture it quick enough. 

**Describe the solution you'd like**
Please add version to the bottom of settings window. It would be nice have quick access to the version when reporting an issue on Github.  Otherwise I have to drill into the browser extension/addons menu to get it.

**Comment by Andrews54757** [comment]
Done.
