### ISSUE TITLE
Windowed Fullscreen Option

### ISSUE THREAD

**Issue by Nemisor** [Andrews54757/FastStream#127]
Awesome player, however it would be nice if another view option was available, something along the lines of YouTube Windowed FullScreen. 

I currently use this to automatically "maximize" youtube without going legit fullscreen, which is very handy on ultra-widescreen monitors, etc. Please consider adding this functionality if possible, thank you!

**Comment by Andrews54757** [comment]
Good idea, I'll implement it

**Comment by Andrews54757** [comment]
Done

**Comment by Nemisor** [comment]
Most awesome, thank you so much!

**Comment by Nemisor** [comment]
Not sure if you'll see this, but a very small follow-up request:

Would it be possible to save whatever view-style option you pick for future videos? So if windowed fullscreen was selected, it would retain that setting for future videos?

**Comment by Andrews54757** [comment]
it is possible for me to add that, but I do not think it is necessarily a good design choice. However, I will add a windowed fullscreen keybind to make it easier to enable windowed fullscreen.
