### ISSUE TITLE
[BUG] Some sites have problems when using the new windowed function

### ISSUE THREAD

**Issue by Mioni** [Andrews54757/FastStream#128]
**Describe the bug**
First of all, this function is incredible!
Some sites fail when using this new function, I'll send you some examples:
https://animes.vision/animes/dungeon-meshi-dublado/episodio-15/dublado
https://goanimes.net/episodio/assistir-wind-breaker-episodio-2/

**Platform**
Vivaldi

**Comment by Andrews54757** [comment]
Fixed
