### ISSUE TITLE
Please make it available for Firefox Android 

### ISSUE THREAD

**Issue by androidghosh** [Andrews54757/FastStream#129]
Make it available in Firefox Android extension store

**Comment by Andrews54757** [comment]
From the readme:

> Please note that there are no plans to make FastStream mobile compatible any time soon. Developing FastStream for Chrome and Firefox for the desktop is already an exhausting endeavor. Supporting mobile on top of all that is too much work for a mere college-student programming hobbyist like me. That said, if you find a way to make it work on more browsers or devices, please feel free to share and make a pull request!
