### ISSUE TITLE
[BUG] Player doesnt recognize its already in full screen

### ISSUE THREAD

**Issue by Nvertd** [Andrews54757/FastStream#130]
The player thinks its not in full screen, and pressing the fullscreen button only makes it go into fullscreen, which it already is. So essentially nothing happens.
![image](https://github.com/Andrews54757/FastStream/assets/162870405/6baf842c-b5f3-4ce1-86d4-dca21d947800)

**Comment by Andrews54757** [comment]
Can you explain how I can reproduce this issue? it works fine for me.

**Comment by Nvertd** [comment]
I do not know how to reproduce it, it just happens once in a while.

**Comment by Andrews54757** [comment]
IDK how to fix issues I can't reproduce ;)
