### ISSUE TITLE
[BUG] + [Feature]: detect videos

### ISSUE THREAD

**Issue by sudosign** [Andrews54757/FastStream#131]
faststream v1.3.5 on mullvad and thorium on yt and anime sites(specifically aniwave)

bug: only checks on the first load, if video not in first load of website, is undetected

example steps:

1. go to aniwave
2. go to any anime
3. select a next episode
4. scroll down such that player is not in screen
5. wait for fully loaded
6. player is not loaded with faststream

possible feature to fix: add hotkey to scan current screen and detect videos

**Comment by Andrews54757** [comment]
This is not a bug. It is intended behavior to prevent faststream from being activated on hidden players. Scanning is passive so I can't add a hotkey for it. Instead, press `Ctrl + R` to reload the page.
