### ISSUE TITLE
[Feature] Better scale for volume control and loudness normalization

### ISSUE THREAD

**Issue by automainint** [Andrews54757/FastStream#133]
It's very inconvenient to set audio volume. Here is an example
![image](https://github.com/Andrews54757/FastStream/assets/69725676/18a2ade0-a8af-4662-9611-2aaef25e1948)
The band is almost at 0 visually. If I move the band one pixel, it will change the volume by a several percent.

Also, YouTube have video loudness metadata in LUFS. It would be good to have the option to normalize the audio automatically.

This is especially important for music, when each video is very loud,

Maybe a logarithmic volume scale will be more convenient.

**Comment by Andrews54757** [comment]
Metadata isn't handled by faststream directly. That is done by Dash.JS. The volume shortcut there is for quick rough adjustment. If you want more precise control, I suggest using the mixer controls in the audio config panel. that is in decibels.
