### ISSUE TITLE
[Feature] Video stats + localization

### ISSUE THREAD

**Issue by realgooseman** [Andrews54757/FastStream#137]
Hi @Andrews54757,

Great extension, it's a must on some websites.
I would like to suggest some features and improvements.

### **Visibility**

The extension was quite hard to find so I published it on AlternativeTo, an (open-source) software database to hopefully popularize it.
Here is the link to the published page : https://alternativeto.net/software/faststream/about/

### **New feature : Video stats**

An useful feature that could be added to this packed player is like the "Stats for nerds" feature on YouTube. Where it gives technical details about the current video you're watching. This could be very handy if you want to know the resolution, framerate, codec, buffering,... of the video currently playing in FastStream.

### **Localization**

Currently the extension is available in English, Spanish and Japanese. The process to submit new translations is not straight forward. What could greatly improve the pace and quality of translation contributions is by setting up a translation panel **(like Crowdin or Weblate for example)**. They're both free of charge for open source projects, the project just needs approval after submission.

**Comment by Andrews54757** [comment]
> Visibility

Thanks for publishing FastStream on alternativeto! I have been lacking the willpower to market FastStream to a wider audience. While I never really cared if it became popular, I also realize that more users mean more feedback and better improvement, so I still appreciate your initiative.

> New feature : Video stats

I honestly don't know how I can get some of the stats you listed from a technical perspective. Things like framerate or quality are not always provided by the stream manifest. To add them, FastStream will have to directly decode the video container to fetch those stats, which while possible is not ideal considering that formats may vary widely (APIs like webcodecs are not yet stable either).

Beyond that, I also don't want to override the browser's default context menu to add a custom one like Youtube does. I think it is important that users are able to do things like "inspect element" by right-clicking on the video.

> Localization

Localization instructions are available in #13 . People have in the past sent entire `json` files for localization, but you can also just add a comment if you find any errors. I will look into using a translation service later when I have time.
