### ISSUE TITLE
[Feature] Update notifier for manual installations.

### ISSUE THREAD

**Issue by ChromiaCat** [Andrews54757/FastStream#138]
**Is your feature request related to a problem? Please describe.**
Manual installations will be outdated unless the user is notified an update is out or they check back on this repo themselves.

**Describe the solution you'd like**
Some icon in the player indicating an update was found, with an option to toggle the icon as well as auto updates on/off, would be nice.

**Describe alternatives you've considered**
I thought about an auto updater being in this but I guess chrome wouldn't allow unpacked extensions to auto update for security reasons.

**Additional context**
I don't know if FastStream already has some way to show an update is released, so if this is already a thing fell free to close this.

**Comment by Andrews54757** [comment]
There is a notification in the settings window. The update notification system is only active if you install from unpacked, or install the `libre` files.

**Comment by ChromiaCat** [comment]
> There is a notification in the settings window. The update notification system is only active if you install from unpacked, or install the `libre` files.

I've successfully implemented a small icon next to the settings icon that shows up when an update is available. Should I make a PR?
![image](https://github.com/Andrews54757/FastStream/assets/43613021/e2036670-a036-4353-ad35-a6e54302c050)

**Comment by ChromiaCat** [comment]
> There is a notification in the settings window. The update notification system is only active if you install from unpacked, or install the `libre` files.

@Andrews54757 I've implemented a small icon next to the settings one when an update is available. Do you want me to PR this?
![image](https://github.com/Andrews54757/FastStream/assets/43613021/bae1c2df-5826-4582-a6e9-7e6d690866a5)

**Comment by Andrews54757** [comment]
Thanks, but it's alright. I don't think it's that important to have highly visible update notifications for now. I haven't yet figured out what FastStream's update schedule will look like in the long term. Not to mention that the code hasn't been refactored yet. I'll think about it later though and let you know if I change my mind.
