### ISSUE TITLE
[Feature] Revamp quality auto selection.

### ISSUE THREAD

**Issue by ChromiaCat** [Andrews54757/FastStream#139]
**Is your feature request related to a problem? Please describe.**
Kinda but not really.

**Describe the solution you'd like**
Quality multiplier factor is not very clear on what it will select for each value it can have. I know it says it will choose higher quality but higher in reference to what? Player size? Site window size?

**Describe alternatives you've considered**
An alternative would be to have a quality selection dropdown where FastStream will attempt to select said quality in the stream, if not it will go down in it's quality list until it matches the highest one that the stream offers.

e.g.
I want 1080p to auto select on all video streams.
If 1080p is the max quality the stream offers then select it.
If anything higher than 1080p is offered still auto select 1080p but also allow the user to manually select some other quality without forcing 1080p by continuously selecting it.
If 1080p is not available, select the highest available e.g. if the highest a video offers is 480p, select that.

**Additional context**

**Comment by Andrews54757** [comment]
Done
