### ISSUE TITLE
How to deal with fragments familiars ?[BUG]

### ISSUE THREAD

**Issue by DareDevil2000** [Andrews54757/FastStream#140]
**Describe the bug**
After completing 80% of the video in show " fragments failed! click to retry " but after clicking retry it doesent load and give the same error.

**Version**
FastStream V1.3.6"

**Platform**
Firefox 125.0.3 (64-bit)

**Steps to Reproduce**
Not a popular site

**Comment by Andrews54757** [comment]
If it gives the same error, it means the website's servers are refusing to send the video data to faststream. Not much I can do about that.
