### ISSUE TITLE
FastStream Video Player failed to save video!

### ISSUE THREAD

**Issue by PeterFaststream** [Andrews54757/FastStream#141]
Hi Andrews,

I cannot save the following HD (1280x720 & 1920x1080) stream without errors:

https://sportdeutschland.tv/goc/goc-2023-alte-reithalle-tag-3-9-40-16-00

FastStream Videoplayer Failed to save video!
Video size exceedslimits, will buffer 200s
Fragment failed chlick to retry!

!!Download 960*540 @ 1626Kbps is okay!!

What can I do? Please help me.

Many Thanks
Peter from Germany

![BufferFastStream](https://github.com/Andrews54757/FastStream/assets/170025249/1191f96d-9085-4c1f-a8d2-e357cf7593af)

![SaveFailureFaststream](https://github.com/Andrews54757/FastStream/assets/170025249/3e291205-9592-4f12-9523-c5200222a0da)

![Segment failed](https://github.com/Andrews54757/FastStream/assets/170025249/40c32acc-aa06-49e9-8008-649fabcbafcb)

**Comment by Andrews54757** [comment]
It means that the video server refused to send one of the video fragments. Theres not much I can do to fix this as the mp4 requires all fragments to play from start to end. You can try this instead to forcefully create a potentially broken mp4:

1. In settings, set the maximum size of the predownloaded video to infinity. You can just type `inf`.
2. After the movie is mostly downloaded, hold down `ALT` and click the download button.

If you do this it will save whatever it has into an MP4 regardless if some fragments are missing.

**Warning: The video may fail to play in regions where there are missing fragments**
