### ISSUE TITLE
Save file option doesn't work on some site

### ISSUE THREAD

**Issue by DareDevil2000** [Andrews54757/FastStream#144]
In some streaming site the save file option doesn't work even though the video is fully buffered, after clicking the save option it says the video is saving and complete the full loading animation and says video is saved but it doesn't.

Is there any ways that i can find the video in my local folder and copy from there ?

**Comment by Andrews54757** [comment]
Please include steps to reproduce the issue.

**Comment by DareDevil2000** [comment]
sorry lost track that , but can i get an answer of this "Is there any ways that i can find the video in my local folder and copy from there ?"

**Comment by Andrews54757** [comment]
Make sure you saved the video in the right location. I need steps to replicate your issue in order to know how to fix it. Closing issue as it lacks steps to reproduce the issue.
