### ISSUE TITLE
Does not connect  from this site [BUG]

### ISSUE THREAD

**Issue by DareDevil2000** [Andrews54757/FastStream#147]
**Describe the bug**
As the title says.

**Version**
 FastStream V1.3.8"

**Platform**
Firefox v126.0.1

**Steps to Reproduce**
[Open a video and click the extension it wont connect or some time a white screen appears and stuck there](https://www.braflix.so/)

**Comment by Andrews54757** [comment]
There is nothing faststream can do about a website that uses custom scripts to block modifications to its website. Instead, try the following:

1. Open a new tab, and click the icon to go to the player
2. In a different tab, go to the website you want, press play
3. Go to the faststream player tab, and click the sources browser
4. It will collect sources found from other tabs. you can then press play to play the video using faststream.
