### ISSUE TITLE
[BUG] Cannot Play VR Videos

### ISSUE THREAD

**Issue by looloo86** [Andrews54757/FastStream#148]
**Describe the bug**
A VR video no longer plays in VR anymore.

**Version**
1.3.8

**Platform**
Edge

**Steps to Reproduce**
This video plays in VR and can be panned around if played normally: https://www.youtube.com/watch?v=nV_hd6bLXmw
But when the extension is enabled the video is no longer in VR.

**Comment by Andrews54757** [comment]
VR videos are not supported and will not be supported for the time being.
