### ISSUE TITLE
[Feature] about www.braflix.so

### ISSUE THREAD

**Issue by jpACGlover** [Andrews54757/FastStream#149]
I've noticed that a FastStream is not compatible with the website www.braflix.so. Could you please consider adding support for Braflix in a future update?

**Comment by DareDevil2000** [comment]
Author's reply: https://github.com/Andrews54757/FastStream/issues/147#issuecomment-2153952964

**Comment by jpACGlover** [comment]
> 作者回复：[#147（评论）](https://github.com/Andrews54757/FastStream/issues/147#issuecomment-2153952964)

OK,Thanks
