### ISSUE TITLE
Not working in Incognito Mode on Firefox

### ISSUE THREAD

**Issue by SleepDaemon** [Andrews54757/FastStream#15]
I used youtube for this, but essentially I click on extension and it doesnt find the source. Where as on chromium browser it does.

**Comment by SleepDaemon** [comment]
and yes i gave it all the perms

**Comment by SleepDaemon** [comment]
now it wont work on YT for ff

**Comment by Andrews54757** [comment]
It works for me, what version of Faststream are you using? Version 1.2.0 doesn't work with Youtube but version 1.2.1 does. Try updating the extension.

**Comment by SleepDaemon** [comment]
Ok idk why but it started working except for YT. It works on other sites
like those piracy streaming ones. But not for YT which is fine cause the
extension doesn't work with Sponsorblock extension.

**Comment by SleepDaemon** [comment]
So yeah it works just not for yt for me.

**Comment by Andrews54757** [comment]
What version of FastStream are you using?

**Comment by SleepDaemon** [comment]
> What version of FastStream are you using?

Latest from FF store

**Comment by Andrews54757** [comment]
I need a number, EG: "Welcome to FastStream Vx.x.x"

**Comment by SleepDaemon** [comment]
Currently can't check as it's 10pm and I'm heading to bed. Will check
tomorrow.

**Comment by SleepDaemon** [comment]
> I need a number, EG: "Welcome to FastStream Vx.x.x"

v1.2.2

and also doesnt work now.

**Comment by SleepDaemon** [comment]
Ok i thinki i figured it out, it works as long as I am not in incog/private mode on ff.

**Comment by SleepDaemon** [comment]
Yes i gave the extension perm to run in private mode.

**Comment by woducku** [comment]
Same. Tried it in several sites. Tried putting the link manually too. But didn't work.

**Comment by Andrews54757** [comment]
I'll look into it

**Comment by Andrews54757** [comment]
Ok, I fixed the issue in V1.2.3 for Firefox, please update and try again.

**Comment by SleepDaemon** [comment]
![image](https://github.com/Andrews54757/FastStream/assets/88533953/f8ca96d1-c26d-4e5f-a9f8-e1e4d4dcf8bf)

Im guessing this is normal

**Comment by Andrews54757** [comment]
Yes

**Comment by SleepDaemon** [comment]
in none-private mode the extension doesnt work on YT but it does in private mode but when it does it is like stuttering.

I am fine with this as I said I would rather use normal YT player just so I can use it with sponsor block extension.

Will use this extension for other sites where media player are crap.

**Comment by Andrews54757** [comment]
Try updating to 1.2 4 and let me know if that works.

**Comment by Andrews54757** [comment]
<img width="1512" alt="works" src="https://github.com/Andrews54757/FastStream/assets/13282284/c1cf30c3-40d8-42f0-a776-a5fa94bd264b">
