### ISSUE TITLE
[BUG] 0mbps speed

### ISSUE THREAD

**Issue by coder-oo8** [Andrews54757/FastStream#150]
**Describe the bug**
It works fine for some hours then gives 0mbps speed or 0.2mbps eventhough there is no problem with the internet connection. 

**Version**
FastStream version. 1.3.8

**Platform**
The browser you are using Chrome

**Steps to Reproduce**
on Fmovies site stream any video

**Comment by Andrews54757** [comment]
This may be because the server is blocking or throttling your connection. If the website's server decides to limit download speed then you will have slow speeds even with a good internet connection.
