### ISSUE TITLE
[Feature] Add "cinema" mode 

### ISSUE THREAD

**Issue by Dioswilson** [Andrews54757/FastStream#151]
**Is your feature request related to a problem? Please describe.**
While watching youtube I used the "cinema mode", which is a middle ground between windowed fullscreen and small size

**Describe the solution you'd like**
I'd like to see cinnema mode implemented, maybe not for all sites, because you need to rearange the HTML accordingly, but maybe a way to do it in youtube since it already has that functionality

**Describe alternatives you've considered**
I currently just use fullscreen

**Additional context**
Cinnema mode example:
![image](https://github.com/Andrews54757/FastStream/assets/63358200/d29515c5-4b9c-44f6-8118-68600d878bbe)

**Comment by Andrews54757** [comment]
See #80
