### ISSUE TITLE
[BUG] no save button for youtube

### ISSUE THREAD

**Issue by mr-d-r** [Andrews54757/FastStream#152]
thank you for the great extension!

**Describe the bug**
there is no save button for youtube video.
is it bug?
or it is made on intent to avoid copyright headache with google?

**Version**
1.3.8

**Platform**
chrome in windows10

**Steps to Reproduce**
[Please tell us how to reproduce the issue. A URL to a specific video is encouraged.](https://www.youtube.com/watch?v=AHSLN0YnGB0&t=51s)

![image](https://github.com/Andrews54757/FastStream/assets/172079743/a62b9b9d-aa99-4c9f-a423-b4402bf98eb0)

regards

**Comment by Andrews54757** [comment]
From the README:

> Youtube (download not supported on Chrome unless manually installed due to Web Store policy)

**Comment by mr-d-r** [comment]
thank you!
