### ISSUE TITLE
[BUG] Stream not detected on braflix.ru 

### ISSUE THREAD

**Issue by erikk333** [Andrews54757/FastStream#153]
**Describe the bug**
Streams played on braflix website wont  be detected by faststream resulting in that the extension wont be used
**Version**
1.3.8

**Platform**
Firefox

**Steps to Reproduce**
**1. go to https://www.braflix.ru
2. turn faststream on
3. play a stream like https://www.braflix.ru/movie/10331 for example 
4. the stream is not detected
5. refresh the page
6. still not detected**

**Comment by Andrews54757** [comment]
See #147

**Comment by mr-d-r** [comment]
i've done it
it took about 7 hours, looks not good, but it works

take a look if you are curious
https://github.com/mr-d-r/FastStream.byAndrews54757.pieces
all changed lines are marked by   // mr-d-r

thanks again for the great extension and help
