### ISSUE TITLE
storage path for downloaded files

### ISSUE THREAD

**Issue by mr-d-r** [Andrews54757/FastStream#154]
hi

please tell the chrome storage path for all downloaded files.
how long downloaded files are keeping in the chrome cache?

thank you

**Comment by Andrews54757** [comment]
If you don't save it to a file, it will not be saved as a file. It will be cached in chrome as a blob, which is erased when you close the tab.

https://chromium.googlesource.com/chromium/src/+/HEAD/storage/browser/blob/README.md
