### ISSUE TITLE
Date and time to match system clock

### ISSUE THREAD

**Issue by Bolongna** [Andrews54757/FastStream#155]
App works great for most things, However if I save any video it adds the date of 12/31/1903 and a time of 19:00 as the creation date of each file. So if I save a TV series for example it's harder to track the episodes.

If Possible I would like the saved files to match the system date and time.

The only thing I have considered is manually changing the time and date but if you have a lot of episodes that can take a while.

![timestamp](https://github.com/Andrews54757/FastStream/assets/85271732/51e903ba-19e1-4b6e-90eb-fb2bc1e92aa8)

**Comment by Andrews54757** [comment]
The creation date is not controlled by FastStream. Your browser and operating system is responsible for this issue. Please check if you have configured your computer's system time correctly.

**Comment by Bolongna** [comment]
This isn't the creation date, it's the file date and with any other downloads it shows correct time and date. I wonder if it's something server side related, IE they don't set their info to avoid issues? Will try a few other sites to see what they do, I can use different download methods to see if it only happens with FastStreams saves.
edit - update - Tried it on a couple other sites and only FastStream puts that time and date on every file. Other downloaders using the same browser use the system time and date. Not sure where the issue is.
