### ISSUE TITLE
Faststream doesn't work on binged.live website

### ISSUE THREAD

**Issue by MysticMaestro** [Andrews54757/FastStream#156]
**Describe the bug**
The extension works on all other websites I have tested except binged.live

**Version**
Faststream version 1.3.8

**Platform**
Tried it on both Brave / Firefox browser

**Steps to Reproduce**
navigate to binged.live website and play any video. Followed the steps on github readme to open faststream in new tab. Only ublock extension is working in the browser.

**Comment by Andrews54757** [comment]
The site uses a custom source pattern. Add this line in your custom source pattern list.
```
m3u8 /^https:\/\/vidsrc\.pro\/.*\/playlist\.m3u8\.png\?.*$/
```

**Comment by dimii27** [comment]
> The site uses a custom source pattern. Add this line in your custom source pattern list.
> 
> ```
> m3u8 /^https:\/\/vidsrc\.pro\/.*\/playlist\.m3u8\.png\?.*$/
> ```

this doesn't work for me
