### ISSUE TITLE
[BUG] YouTube video blinks when hovering over the progress bar in videos with partitions

### ISSUE THREAD

**Issue by Vitor-ui** [Andrews54757/FastStream#158]
**Describe the bug**
When hovering the mouse over the progress bar the video blinks in Youtube video with partitions

**Version**
FastStream version V1.3.8

**Platform**
Brave

**Steps to Reproduce**
any YouTube video with partitions (divided by names, like, from 1:00 to 3:50 is the YouTuber's intro) and then just wait for the video to load and when it loads completely, just hover the mouse over the progress bar

**Comment by Andrews54757** [comment]
I'm having trouble reproducing this issue. What is it supposed to do?
![image](https://github.com/Andrews54757/FastStream/assets/13282284/47086eaf-ca6f-4690-9652-9a1ced332179)

**Comment by Andrews54757** [comment]
Can you send a screen recording of the issue happening?

**Comment by Andrews54757** [comment]
Closing as stale
