### ISSUE TITLE
[BUG] Youtube video in 1440p only loads up to 5%

### ISSUE THREAD

**Issue by Vitor-ui** [Andrews54757/FastStream#159]
**Describe the bug**
when the video is in 1080p it loads everything normally but when it is in 1440p it loads up to 5% and the same thing in 4k

**Version**
FastStream V1.3.8

**Platform**
Brave

**Steps to Reproduce**
open any video that has a quality higher than 1080p (1440p or 2160p) (preferably 60fps as well)

**Comment by Andrews54757** [comment]
Thats because the size of the video exceeds the maximum size of the predownloaded video. You can change this setting to `infinity` to remove the limit. See the README for more details.
