### ISSUE TITLE
Default audio level and SponsorBlock integration

### ISSUE THREAD

**Issue by woducku** [Andrews54757/FastStream#16]
~~it's 100% by default. i am deaf now. i dont want others to be deaf too.~~ I missed the audio config option. Also if possible, maybe add sponsoreblock support.  The extension is working great for me.

**Comment by woducku** [comment]
also how is it getting higher res? the youtube player isnt showing me that. 

![image](https://github.com/Andrews54757/FastStream/assets/57977673/b6245fc3-16df-4f93-9ec1-4a9c88c4bae7)


![image](https://github.com/Andrews54757/FastStream/assets/57977673/7f338ee7-b77e-42b2-b731-a2af2fe6be43)

**Comment by Andrews54757** [comment]
@anotherduckling You can decrease audio levels persistently by following these steps:

1. Click the blue audio config icon
2. Decrease the master slider on the audio channel mixer.
3. Click "Save Profile"

**Comment by Andrews54757** [comment]
I'll contact @ajayyy to see if I can get FastStream compatible with the SponsorBlock extension.

**Comment by ajayyy** [comment]
ooh, this looks like a very cool extension. I wonder if some of your techniques can be used to ensure that the video after the sponsor skip is pre-buffered.

On making sure they are compatible. Right now, does your extension result in two video elements appearing on the page? If so, maybe, you could set a specific class on one of them that I can make SponsorBlock not use.

**Comment by Andrews54757** [comment]
Yes. One of the video elements is the seek preview window. It is inside a `<div>` with the class `seek_preview_video`. The main video is located in a `<div>` with the class `video-container`.

**Comment by ajayyy** [comment]
It seems you use an iframe so it's actually finding no videos

**Comment by ajayyy** [comment]
Looks like it is against CORS to interact with the iframe

**Comment by Andrews54757** [comment]
Would it be possible for your extension to send skip regions via the [external message passing](https://developer.chrome.com/docs/extensions/mv3/messaging/#external) API? FastStream already has mechanisms in place to skip specific time regions. I can also have FastStream emit messages for your extension.

**Comment by ajayyy** [comment]
One problem is that most people have to install faststream via debug mode, which will produce a different extension id each time

**Comment by Andrews54757** [comment]
Fair, though FastStream is also available on the Chrome Web Store + Mozilla Addons. Maybe there's another way to send messages back and forth? The last option is to just bundle SponsorBlock with the extension.

**Comment by Andrews54757** [comment]
I've got an idea, I can have FastStream send its own ID to SponsorBlock on initialization, that way it won't matter what ID FastStream has.

**Comment by Andrews54757** [comment]
@anotherduckling Unfortunately, SponsorBlock integration communications have broken down (they timed me out without warning for suggesting security improvements in their Discord server). As a result, I don't think I can integrate with the official SponsorBlock extension. I may provide a fork with the necessary API changes in the future, but for now SponsorBlock integration is off the shelf.

**Comment by woducku** [comment]
@Andrews54757 thanks for looking into it. I am still confused about [this one](https://github.com/Andrews54757/FastStream/issues/16#issuecomment-1819041295)

**Comment by Andrews54757** [comment]
@anotherduckling Really basic sponsorblock support was added in [V1.2.7](https://github.com/Andrews54757/FastStream/compare/V1.2.6...V1.2.7). It's a monkeypatch that only allows FS to discover skip segments if you have SB installed, but should be "good enough" until I work on actual support for it.

**Comment by neoOpus** [comment]
I came here to inquire about this feature, as it would significantly enhance YouTube. I believe it is becoming a widely requested addition, as evidenced by this thread and others. Please consider making it possible.

**Comment by wheelsbot7** [comment]
I'm glad to see this is a point of discussion. The current "monkeypatch" implementation works plenty well for my purposes, except for the lack of automatic skipping. Manual skipping already works great, is there a technical reason it has to be manual? Otherwise, I agree it would be a significant addition that would greatly improve the user experience.
