### ISSUE TITLE
[BUG] Blank page on ok.ru when FastStream is enabled

### ISSUE THREAD

**Issue by ale5000-git** [Andrews54757/FastStream#160]
**Describe the bug**
Blank page when FastStream is enabled

**Version**
1.3.8

**Platform**
Chrome on Windows

**Steps to Reproduce**
- Go here: ok.ru/videoembed/6934036482656
- Enable FastStream
- Click on Play
- All become blank

There are a lot of errors in the console but the most important seems to be:
```
Uncaught TypeError: Cannot read properties of null (reading 'contains')
    at Object.r [as isElementInDocument] (okHtml5Player.min.js:6:2959)
    at okHtml5Player.min.js:3:20444
    at Array.forEach (<anonymous>)
    at e (okHtml5Player.min.js:3:20404)
    at okHtml5Player.min.js:3:23003
```

**NOTE:** I have added the custom source pattern: `mpd /^https:\/\/vd[0-9]*\.mycdn\.me\/\?.*&type=1&/`

PS: There are also issues with the download on the same url (downloading the player's buffer storage near the end stuck forever and never end).

**Comment by Andrews54757** [comment]
Fixed. Full download can fail if servers refuse to send all data. You can still save a partial video by holding down `ALT` and clicking the save button.
