### ISSUE TITLE
[Feature] integration with sponsorblock

### ISSUE THREAD

**Issue by Rizkiacry** [Andrews54757/FastStream#162]
**is your feature request related to a problem? please describe.**
yes, it should display "skip segment" button when using regular youtube player.

**describe the solution you'd like**
sorry

**describe alternatives you've considered**
not using sponsorblock

**additional context**
love u dev❤️
https://github.com/ajayyy/SponsorBlock

**Comment by Andrews54757** [comment]
Duplicate #16
