### ISSUE TITLE
[Feature] Forward Button 

### ISSUE THREAD

**Issue by Bashousen** [Andrews54757/FastStream#163]
I would like to know if it is possible to add a forward button. When I'm watching something on my cell phone it's very useful.

**Comment by Andrews54757** [comment]
What does a forward button do?

**Comment by Bashousen** [comment]
> What does a forward button do?

I'm not sure what they're called, but they're these buttons here:
![image](https://github.com/Andrews54757/FastStream/assets/109592830/cff19d00-6145-474a-8737-4c2a72423bc4)

 website doesn't always have apps and some players aren't very mobile friendly, so that's why I asked.(I used translator)

**Comment by rickt** [comment]
StreamFast is such a feature complete player, i feel silly even mentioning this, but a feature on youtube (skipping backwards/forwards by 10 seconds using the J/L keys) would be as similarly welcome as Forward/Back buttons. 

thank you for FastStream! it's great.

**Comment by Andrews54757** [comment]
@rickt FastStream already has a large seek keybind. Press the "<>" keys to seek. You can change the key mapping to J and L in settings.

**Comment by Andrews54757** [comment]
Done https://github.com/Andrews54757/FastStream/commit/706bd4338e19247e9b79a5d0b732dbdc49923e2a

**Comment by rickt** [comment]
thank you!! my apologies for not RTFMing 😳
