### ISSUE TITLE
[BUG] Youtube "Failed to Load" + 403 Error Instructions

### ISSUE THREAD

**Issue by Andrews54757** [Andrews54757/FastStream#164]
## The Problem
Youtube videos are failing to load as of Jul 8 2024.

![image](https://github.com/Andrews54757/FastStream/assets/13282284/7954cc67-3fd9-482e-89b9-bfe1a33af6b6)

Stacktrace:

![image](https://github.com/Andrews54757/FastStream/assets/13282284/29a9edf3-93e4-4de1-a4d3-c18a30d23397)

## The Reason

Youtube has changed their API. Specifically, they have changed [`base.js`](https://www.youtube.com/s/player/b22ef6e7/player_ias.vflset/en_US/base.js)

## The Fix

A fix will require updating the underlying Youtube.js library. Please stay tuned.

**Comment by eeeeb** [comment]
Same here

**Comment by Andrews54757** [comment]
Related issue on YoutubeJS
https://github.com/LuanRT/YouTube.js/issues/683

Related issue on Freetube
https://github.com/FreeTubeApp/FreeTube/issues/5378

**Comment by Andrews54757** [comment]
Investigating potential fix:

https://github.com/LuanRT/YouTube.js/pull/682

**Comment by Andrews54757** [comment]
Fixed in V1.3.10

**Comment by Andrews54757** [comment]
Note: Some users are reporting that they are getting failed fragments, 403 errors on youtube after the update. This is likely because of the cache still using old tokens. Please do the following:

1. Open developer tools on Youtube
2. Click "Application"
3. Under "Storage", find "youtubei.js". Click it.
4. Click delete database.

![image](https://github.com/Andrews54757/FastStream/assets/13282284/ef05bb8d-b3a2-446a-8cee-0aa85fb5b49d)
