### ISSUE TITLE
[BUG] "xxx Fragments Failed! Click to retry." since the last update 1.3.10

### ISSUE THREAD

**Issue by Chucky2401** [Andrews54757/FastStream#165]
**Describe the bug**
On every YouTube video, I got the error message "xxx Fragments Failed! Click to retry.". Retry do nothing.
![image](https://github.com/Andrews54757/FastStream/assets/53853245/27d1083b-0505-40bd-b579-cced6a93ff8c)

In the WebDev console a lot of 403 errors
![image](https://github.com/Andrews54757/FastStream/assets/53853245/87f229ab-dfac-4c47-beef-1e846cdd0227)

**Version**
V1.3.10

**Platform**
Vivaldi / Windows 11 Pro

**Steps to Reproduce**
Just load a video with FastStream enable

**Comment by Andrews54757** [comment]
Youtube has changed their API. Try deleting caches. If the problem persists, it might mean Youtube is now starting to block FastStream's requests.

**Comment by Andrews54757** [comment]
Done https://github.com/Andrews54757/FastStream/commit/706bd4338e19247e9b79a5d0b732dbdc49923e2a

**Comment by Andrews54757** [comment]
See more detailed instructions at [#164](https://github.com/Andrews54757/FastStream/issues/164#issuecomment-2221807166)
