### ISSUE TITLE
[BUG] and Feature Request: Subtitle Not Showing Up Because FastStream Auto Loads Too Fast After A Refresh

### ISSUE THREAD

**Issue by Rizkiacry** [Andrews54757/FastStream#168]
**Describe the bug**
In some sites, the subtitle is downloaded and triggered after the video is played. FastStream loads faster than video player, making it unable to get the subtitle info.

**Version**
1.3.10

**Platform**
Arc Mac (Chromium)

**Steps to Reproduce**
1. Aniwave.to (example)
2. Go to any title with soft sub (Oshi no Ko/Alya)
3. Change to s-sub
4. After FastStream loads, refresh the page
5. The subtitle still not showing.

I recommend implementing a toggle for disabling auto load FastStream after a refresh.

**Comment by Andrews54757** [comment]
Added replacedelay https://github.com/Andrews54757/FastStream/commit/be1f4f451e5f7d8d701d199ffc6c45579caaf0dc option to allow user to control how long FS should wait before replacing the video player.
