### ISSUE TITLE
[BUG] Video player black when switching to Youtube theater mode and then activating FastStream

### ISSUE THREAD

**Issue by eeeeb** [Andrews54757/FastStream#170]
**Describe the bug**
The video player (FastStream) will be black when you activate the Youtube theater mode and then turn FastStream on.
There was no problem like that with FastStream Video Player 1.3.10 and lower.

**Version**
FastStream Video Player 1.3.11

**Platform**
Chrome 126.0.6478.127 (Official Build) (64-bit)

**Steps to Reproduce**
1. Open Youtube video (FastStream not active)
2. Activate Youtube theater mode (or press t)
3. Activate FastStream
4. Reload the page
5. The video player will be black and no FastStream controls will show up

**Comment by Vitor-ui** [comment]
leave it without the theater mode, leave it clicked on any control until the extra controls appear, and then you drag the player's theater mode button and use this theater mode, for me it was also black but doing this resolved it.
Or you can leave theater mode off and go to the video settings using the FastStream player and select a quick key for the Windoed Fullscreen option

**Comment by Andrews54757** [comment]
Looks like its because of #167 . Reverted it.

**Comment by Vitor-ui** [comment]
It's still not working correctly, if it's already in theater mode the screen goes black, in version 1.3.9 it worked perfectly, now it just stays with a black screen

**Comment by Andrews54757** [comment]
I haven't pushed the update to the web stores yet.
