### ISSUE TITLE
[BUG] FastStream is unable to load a direct link to an mp4 video

### ISSUE THREAD

**Issue by ale5000-git** [Andrews54757/FastStream#171]
**Describe the bug**
FastStream is unable to load video

**Version**
1.3.11

**Platform**
Chrome

**Steps to Reproduce**
URL: `http://hentaiplanet.info/archive/Inda_no_Himekishi_Janne_01_Subbed.mp4`
(it is NSFW)

The video play correctly directly in the browser, but when enabling FastStream it say: `Failed to load video!`

**Comment by Andrews54757** [comment]
It works for regular video files like `https://sample-videos.com/video321/mp4/480/big_buck_bunny_480p_10mb.mp4`. Your video might be corrupted in some weird way.

Try playing using Direct mode instead of Accelerated MP4.

**Comment by ale5000-git** [comment]
@Andrews54757
Thanks, it seems to works fine in Direct mode.
Isn't possibile to make FastStream automatically fallback to Direct mode if Accelerated MP4 failed completely before starting?
