### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by mr-d-r** [Andrews54757/FastStream#173]
**Is your feature request related to a problem? Please describe.**
I have some thoughts to improve your cool FastStream extension

**Describe the solution you'd like**
1. FastStream does not pick up the title of the video during save and offering "1" as a filename
   also adding the channel name would be very convenient.
   it happens for ukrainian/russian and I guess for other cyrillic languages

2. I use 256x144 to listen saved videos later, can you please extend video quality list in options to have 256x144 as default?
   also it looks good to have an option "Do not start caching" to choose requires resolution at first.
   is it possible to have an option to save file directly to filesystem without caching to blob?

3. it would be great to assign ''none'' to some keys, which I do not use. 

**Describe alternatives you've considered**

**Additional context**
I hope you will find it useful

**Comment by Andrews54757** [comment]
For 3. you can press "Esc" to set the keybind to none.

**Comment by mr-d-r** [comment]
thank you for 3.

plz consider 1 & 2 as well

"Youtube Tools All in one local download mp3 mp4 HIGT QUALITY return dislikes and more" plugin for tampermonkey takes video title correctly.
https://greasyfork.org/en/scripts/460680-youtube-tools-all-in-one-local-download-mp3-mp4-higt-quality-return-dislikes-and-more
I hope you can borrow the code for simplicity.

**Comment by Andrews54757** [comment]
I have added 144p to the quality list. As for the file name, this is intended. Only latin characters `a-z, A-Z` are allowed to be extracted for security purposes. You can disable this filter by removing this line of code:

https://github.com/Andrews54757/FastStream/blob/4b90ca1a1446cf4ba4459cce26f43de14de72473/chrome/background/background.mjs#L469

**Comment by mr-d-r** [comment]
> I have added 144p to the quality list

cool. thank you. 

> Only latin characters a-z, A-Z are allowed

changed it to:
``` title = title.replace(/[ +=!@#$?\[\],<>:;'"/|\\(){}`%^&*~]/g, '_'); ```
which is safe both for filesystem and against possible inline script execution
can you please make it as extension option "Safe filename" turned ON by default?
may be a hidden one, available only in config file?


And the very last question: 
I have found and tested how to get the channel name in classic javascript
```chanName = window.ytInitialPlayerResponse.videoDetails.author```
but it does not work in extension
I'm IТ-guy, but not a big programmer, and for me it will take days to figure out how to get channel name in extension.
if know the command, please tell me.

**I'm greatly appreciated for the help and patience**

**Comment by mr-d-r** [comment]
i've done it
it took about 7 hours, looks not good, but it works

take a look if you are curious
https://github.com/mr-d-r/FastStream.byAndrews54757.pieces
all changed lines are marked by // mr-d-r

thanks again for the great extension and help
