### ISSUE TITLE
[BUG] black screen when activating Fast Stream with YouTube theater mode active

### ISSUE THREAD

**Issue by Vitor-ui** [Andrews54757/FastStream#175]
**Describe the bug**
When I start the video, the Outube player just has a black screen with the sound playing, with and without the Improve Youtube extension if this BUG happens

**Version**
FastStream version "1.3.11"

**Platform**
Brave

**Steps to Reproduce**
When opening any YouTube video when theater mode is already active, the player does not change the image and the screen remains black
![Bugtube](https://github.com/user-attachments/assets/87791ce0-9532-4f97-ae20-cd4a50d362a6)

**Comment by Andrews54757** [comment]
Unless you are manually installing from source, you won't see the fix.

![image](https://github.com/user-attachments/assets/d816ba98-7e6a-4039-9826-b83c4d3e3e41)

**Comment by Andrews54757** [comment]
Reopened. It seems like youtube may be A/B testing a new layout.

**Comment by Andrews54757** [comment]
Hopefully fixed
