### ISSUE TITLE
[BUG] When pausing a video, it is not possible to unpause using a keyboard command (Fn + F7 on my keyboard)

### ISSUE THREAD

**Issue by Vitor-ui** [Andrews54757/FastStream#176]
**Describe the bug**
Pausing via keyboard shortcut works normally but it does not unpause using the same command

**Version**
FastStream 1.3.11

**Platform**
Brave

**Steps to Reproduce**
Start watching any video, pause it using the keyboard shortcut (some keyboards have different commands) and try to unpause it in the same way you paused it, just nothing happens

**Comment by Andrews54757** [comment]
Your browser may be focusing on a different element when you use system keybinds. Faststream has no control over that.
