### ISSUE TITLE
[BUG]Screen Goes Black

### ISSUE THREAD

**Issue by StayLEgit67** [Andrews54757/FastStream#178]
**Describe the bug**
When Trying To Buffer Video But Works On Every Other Platform

**Version**
FastStream version. You can get the version by opening the player, it will display "Welcome to FastStream Vx.x.x"

**Platform**
Opera

**Steps to Reproduce**
Maybe Update The Extension

**Comment by Andrews54757** [comment]
Is this on Youtube? then it is a duplicate of #175 . Perhaps Youtube is A/B testing a new layout. Will investigate and fix if I can.

**Comment by Andrews54757** [comment]
Closing as duplicate
