### ISSUE TITLE
[Feature] YouTube copy video url at current time

### ISSUE THREAD

**Issue by Yentis** [Andrews54757/FastStream#182]
**Is your feature request related to a problem? Please describe.**
I want to share a video with a start time.

**Describe the solution you'd like**
Add some way to copy the video url at the current time.

Would also be useful if opening a url with a timestamp would start the player from that point.
If desired I can look into implementing it.

**Comment by Andrews54757** [comment]
Feel free to give it a go. Preferably without adding extra buttons. I don't think it is good to have UI elements that only apply to one website (Youtube).

**Comment by Yentis** [comment]
https://github.com/Andrews54757/FastStream/pull/184

**Comment by Andrews54757** [comment]
Implemented
