### ISSUE TITLE
[BUG] Video ends too early when using high playback rate

### ISSUE THREAD

**Issue by Yentis** [Andrews54757/FastStream#188]
**Describe the bug**
The video ends a frame or two too early when using high playback rate

**Version**
1.3.13

**Platform**
Chrome

**Steps to Reproduce**
- Go to a [video](https://www.youtube.com/watch?v=vNlPnruLfjM)
- Skip to a few seconds from the end
- Set playback rate to 2x
- Notice with faststream the video above ends on "see you in the next vide-"
- Notice in vanilla youtube the video ends on "see you in the next video", even when playback rate is set to 2x

**Comment by Andrews54757** [comment]
Thanks for the detailed report. I'll look into it. It seems like this is an issue with the browser's implementation of playback rate. I don't know how Youtube solves this issue. If anyone has an idea, please let me know.

**Comment by Andrews54757** [comment]
Closing because there doesn't seem to be a way to fix this issue
