### ISSUE TITLE
[BUG] high CPU usage with intro/outro analyzer on

### ISSUE THREAD

**Issue by Vitor-ui** [Andrews54757/FastStream#189]
**Describe the bug**
When the video finishes loading, my CPU (ryzen 5 5500) is at 100%

**Version**
FastStream 1.3.14

**Platform**
Brave

**Steps to Reproduce**
Play any video in 1080p and wait for the full video to finish loading
![CPU](https://github.com/user-attachments/assets/a539924b-9f02-41fe-a86c-741e60ca6748)

**Comment by Vitor-ui** [comment]
In fact, the CPU stays at 100% while loading the full video

**Comment by Andrews54757** [comment]
What website does this happen with? What faststream settings are you using? Can you reproduce the issue with Chrome?

**Comment by Vitor-ui** [comment]
in a YouTube video in 1080p, with the video fully loaded with the options set to infinite, I would have to install Chrome and configure my extensions

**Comment by Andrews54757** [comment]
I can't reproduce the issue on my browser. Can you try to reproduce it on Chrome?

**Comment by Vitor-ui** [comment]
I installed Chrome and configured the extensions, it seems that the CPU is only at 100% in some videos, I think it's in the videos that are heavily compressed by the YouTuber himself, the same thing that happens when installing ARK you download 60gb to store 430gb

**Comment by Andrews54757** [comment]
On chrome, can you do the following?

1. open developer tools
![image](https://github.com/user-attachments/assets/6d4d4b99-88b8-4ddc-9346-9d368160b1c9)

3. Go to the performance tab

![image](https://github.com/user-attachments/assets/87491a62-4112-4c96-aacc-ce46b3f81dfd)


5. Click record

![image](https://github.com/user-attachments/assets/e88b90c7-f198-434f-a90c-f24f393c1234)

7. Stop the recording after 5 seconds

![image](https://github.com/user-attachments/assets/e4b7b1ee-f10b-4385-9e4c-d2d7de5ba14d)

9. Click save profile

![image](https://github.com/user-attachments/assets/6540c609-929c-469c-9437-50a474a263fe)

10. Send me the resulting profile file.

**Comment by Vitor-ui** [comment]
[Uploading Trace-20240720T131630.json…]()

**Comment by Andrews54757** [comment]
You sent the comment before it finished uploading. Try uploading it again

**Comment by Vitor-ui** [comment]
[Trace-20240720T131630.json](https://github.com/user-attachments/files/16321682/Trace-20240720T131630.json)

**Comment by Andrews54757** [comment]
Looking at the profile you sent me, it looks like FastStream is trying to analyze the video for intro/outro sequences. Try disabling that setting.

**Comment by Vitor-ui** [comment]
It's true, I activated it yesterday and ended up forgetting to deactivate it, sorry for the inconvenience
