### ISSUE TITLE
[Feature] Default volume

### ISSUE THREAD

**Issue by kamitsu2004** [Andrews54757/FastStream#19]
I would like an option to change the default volume.
Please consider.

**Comment by kamitsu2004** [comment]
I noticed that you can change the volume by looking at #16.

Not to change the subject, but I would like to be able to change the volume in the player from 10% to any desired value, like seekStepSize.
It would be very helpful if the volume could be changed with the mouse wheel!

**Comment by Andrews54757** [comment]
Added mouse wheel support https://github.com/Andrews54757/FastStream/commit/78b075dc4a40f73f237da5998fad9872a5c7d159 . Scroll while hovering over volume controls to change volume.

**Comment by Andrews54757** [comment]
@kamitsu2004 
> Not to change the subject, but I would like to be able to change the volume in the player from 10% to any desired value, like seekStepSize.

High gain will cause audio artifacts resulting in lower audio quality. I recommend that you increase your computer's system volume instead.
