### ISSUE TITLE
[BUG] Some videos don't load completely on Brave

### ISSUE THREAD

**Issue by Vitor-ui** [Andrews54757/FastStream#190]
**Describe the bug**
Even with the extension configured to not limit video loading, some videos end up limiting it, some by 4.5%, others by 12%.

**Version**
FastStream 1.3.14

**Platform**
Brave

**Steps to Reproduce**
Start a YouTube video with the extension unlimited, and wait to see if it's fully loaded, this happens with some videos, I can't tell if it's the original format of the video or a general bug

![image](https://github.com/user-attachments/assets/d360ab7e-a1a0-4721-8cf4-995d977a7e23)

**Comment by Andrews54757** [comment]
Can you provide an example video?

**Comment by Vitor-ui** [comment]
https://github.com/user-attachments/assets/d9c9c7d1-74d3-41c4-ae76-b9f4e8721b79

does this work?

**Comment by Andrews54757** [comment]
No I mean provide a URL to an example youtube video where the issue happens so I can replicate the issue on my computer.

**Comment by Vitor-ui** [comment]
https://www.youtube.com/watch?v=nylsQV-xMZM

**Comment by Andrews54757** [comment]
Are you perhaps using private mode or incognito?

**Comment by Vitor-ui** [comment]
I'm using normal mode, other than the incognito tab

**Comment by Andrews54757** [comment]
It is possible that the size of the video exceeds the storage capacity of your browser. In that case it will not buffer the whole video even if you set no limit in FastStream settings.

**Comment by Vitor-ui** [comment]
This doesn't make sense, there's a 3 hour video that loads completely even in 4k

**Comment by Vitor-ui** [comment]
Do you know how to increase the limit? If I put the video in 1080p it loads completely normally, but there are some that don't load completely

**Comment by Andrews54757** [comment]
Right click the faststream player, click inspect element, then click "console"

Paste this into the console, and press enter.

```
console.log(fastStream.hasDownloadSpace, fastStream.shouldDownloadAll(), fastStream.options.downloadAll, fastStream.storageAvailable)
```

Tell me what the results are

**Comment by Vitor-ui** [comment]
![image](https://github.com/user-attachments/assets/4938b0e7-660d-43fd-b8a1-89a6b9d4b4d3)

**Comment by Andrews54757** [comment]
What about `fastStream.options.maxVideoSize`?

Try pasting that into the console and tell me the results. It should be equal to `-1`

**Comment by Vitor-ui** [comment]
![image](https://github.com/user-attachments/assets/c418ff94-483b-40ee-acd6-f9ef2b24c584)

**Comment by Andrews54757** [comment]
I think your available storage is too small. It is only 2GB which is easily exceeded by a 20 min video in 1440p. My available storage is 450 GB and it loads completely for me. Try using 1080p instead.

The amount of available storage you have is controlled by your browser depending on factors such as your available disk space and whether you are using private browsing. It is not something faststream can control directly.

**Comment by Vitor-ui** [comment]
I have 340GB free, and it's still an SSD, so it just doesn't make sense

**Comment by Andrews54757** [comment]
The browser you are using may impose additional restrictions

**Comment by Andrews54757** [comment]
Try using regular chrome and see if you get the same results

**Comment by Vitor-ui** [comment]
I tested with Chrome and Brave, Brave was limiting at 11.5% and Chrome loaded normally, do you have any idea how to remove this storage limitation?

**Comment by Andrews54757** [comment]
Unfortunately I do not. You will have to ask the Brave developers.
