### ISSUE TITLE
[BUG] FastStream unable to discover video

### ISSUE THREAD

**Issue by RNavarro3000** [Andrews54757/FastStream#193]
**Describe the bug**
FastStream unable to discover video and not loading player after play button is pressed

**Version**
1.3.15

**Platform**
Firefox

**Steps to Reproduce**
Press play button, which is not in fixed location, to start the video.
https://isladelastentaciones.es/ver-isla-de-las-tentaciones-5-programa-16/

**Comment by Andrews54757** [comment]
They use a custom manifest URL. Add this line in the custom source pattern box in settings.
```
# Fix isla
m3u8 /^https:\/\/[^\.]*.cfglobalcdn.com\/silverlight\/secip\/.*hls-vod(?!.*Frag).*$/
```
