### ISSUE TITLE
[Feature] Predownload up to maximum size if video is too large instead of arbitrary amount of time

### ISSUE THREAD

**Issue by Yentis** [Andrews54757/FastStream#194]
**Is your feature request related to a problem? Please describe.**
A big advantage of this player is that it can predownload the entire video, but when the video is too large this advantage is lost.

**Describe the solution you'd like**
It feels more logical to me that the predownload would go up to the max size instead of buffering the arbitrary 200s as it does now.

**Describe alternatives you've considered**
Increasing the size limit so it's basically never an issue, but I don't know what adverse effects that could have.

**Comment by Andrews54757** [comment]
I capped it just to be safe. You can increase the size limit if you want it to buffer everything. Whether you do that or I increase the predownload size will make no difference on the wear of your SSD.

**Comment by Yentis** [comment]
I think you misunderstood what I meant. Right now it buffers 200s if the video is too large, but what I'm suggesting is to instead buffer to 5gb (or whatever the set limit is in options).
