### ISSUE TITLE
[BUG] Fragments failed with V1.3.17

### ISSUE THREAD

**Issue by eeeeb** [Andrews54757/FastStream#196]
**Describe the bug**
After the update to FastStream V1.3.17, I am still getting Fragments failed errors.

**Version**
FastStream V1.3.17

**Platform**
Chrome Version 127.0.6533.89 (Official Build) (64-bit)

**Steps to Reproduce**
For this video it always loads the first 4.6% and then the fragments errors occur: https://www.youtube.com/watch?v=Sxdqn5U8xzs

**Comment by Andrews54757** [comment]
Youtube is changing things around to prevent third party access. We are working to stay on top with frequent updates.

![image](https://github.com/user-attachments/assets/e1351ca5-b8ff-4394-abe1-aa50cb267950)

**Comment by Andrews54757** [comment]
Hopefully fixed in 1.3.18

**Comment by imh1kiko** [comment]
Fragments seem to be failing again.
