### ISSUE TITLE
[BUG] Stopped at the BetterAnime Website

### ISSUE THREAD

**Issue by SamWRS** [Andrews54757/FastStream#197]
**Describe the bug**

Fragment Failed.

**Version**
FastStream version. You can get the version by opening the player, it will display "Welcome to FastStream Vx.x.x"

v1.3.17

**Platform**
The browser you are using Chrome/Firefox/etc..

OperaGX

**Steps to Reproduce**
Please tell us how to reproduce the issue. A URL to a specific video is encouraged.

The website stopped working - https://betteranime.net/anime/dublado/overlord-iii-dublado/episodio-01

To access the site you need to be logged in, log in with any Google account.

**Comment by Andrews54757** [comment]
I am not going to make an account with them. They blocked my IP anyways

**Comment by ale5000-git** [comment]
I think it is an overzealous anti-ddos script; I'm also blocked and I have never visited the site before.
