### ISSUE TITLE
[BUG] Scrolling the volume icon is reversed

### ISSUE THREAD

**Issue by Araxeus** [Andrews54757/FastStream#198]
**Describe the bug**
When I scroll with my mousewheel over the volume icon/bar - the direction is reversed

* Scrolling **up** should raise the volume **up**
* Scrolling **down** should lower the volume **down**

(Currently scrolling **up** lowers the volume and scrolling **down** raise the volume)

**Version**
1.3.17

**Platform**
Chrome

https://github.com/Andrews54757/FastStream/blob/ce2d02a9a4893c87dad7584ec49eb876885e686f/chrome/player/ui/VolumeControls.mjs#L31-L38

**Comment by Araxeus** [comment]
@Andrews54757 hi could you explain your commit?  `deltaY` shouldn't be different on macOS?

**Comment by Andrews54757** [comment]
MacOS trackpads have an inverted scrolling gesture. swiping up will move the page down.

**Comment by Araxeus** [comment]
Interesting, I own a browser extension that do scrolling similar to this, and it has hundreds of MacOS users but no one ever complained about this

**Comment by Andrews54757** [comment]
You're the first person to bring this issue up even though thousands of people, many without Macs, have used FastStream. Congratulations on being observant!

**Comment by Araxeus** [comment]
haha yeah I guess most people don't bother filling github issues
