### ISSUE TITLE
[Feature] a way to have the video to fit the whole screen like 

### ISSUE THREAD

**Issue by DOOMMARINE117** [Andrews54757/FastStream#199]
**Describe alternatives you've considered**

Hi, great add on for video sites. can you add a way to have it fit the screen? like the whole screen with you tube aspect ratio control too where you can choose different sizes of the screen?

**Comment by DOOMMARINE117** [comment]
there seems to be a case of audio issues with fast stream.

**Comment by Andrews54757** [comment]
There is already a fullscreen button and a windowed-fullscreen button.
