### ISSUE TITLE
goes blank

### ISSUE THREAD

**Issue by angellius** [Andrews54757/FastStream#2]
every time  i turn on the extension the player on the sited goes black nothing seen but if you hit the play button before it goes black you hear sound and the video doesn't return when the extension is turned off only returns a webpage refresh

**Comment by Andrews54757** [comment]
@angellius Please tell us:
1. FastStream version, chrome or firefox?
2. URL of website where it breaks

**Comment by Andrews54757** [comment]
Need more information. I've added some more css overrides just in case for 1.16. https://github.com/Andrews54757/FastStream/commit/e7fbaf6c9338ce1eb298b8b488e27ddc56256641

If you are still having this issue:
1. Open a new tab, and press the faststream icon to open the player
2. Go to the website with the video in a seperate tab
3. Click the golden chain icon button to open the sources browser
4. Find the video source you want on the list, and press "Play"
