### ISSUE TITLE
[Feature] Mobile Support

### ISSUE THREAD

**Issue by y-hbb** [Andrews54757/FastStream#200]
**Is your feature request related to a problem? Please describe.**
Support for mobile browser extension. I tried the extension in Kiwi. It works but UI doesn't work as expected. One example would be I am not able to open in fullscreen.

**Describe the solution you'd like**
Support mobile browsers

**Describe alternatives you've considered**

**Additional context**

**Comment by Andrews54757** [comment]
Duplicate #129 

From the readme:

> Please note that there are no plans to make FastStream mobile compatible any time soon. Developing FastStream for Chrome and Firefox for the desktop is already an exhausting endeavor. Supporting mobile on top of all that is too much work for a mere college-student programming hobbyist like me. That said, if you find a way to make it work on more browsers or devices, please feel free to share and make a pull request!
