### ISSUE TITLE
[BUG] extremely (s)low performance since last update - basically no advantages in buffering compared to native player

### ISSUE THREAD

**Issue by nightey89** [Andrews54757/FastStream#201]
Only on 2C on every youtube video, and besides having a gigabit connection it is extemely slow to load the video contents and buffering. especially when skipping a lot, the buffering almost cant keep up. this only happened since 1.3.19.

1.3.19

Chrome Version 127.0.6533.99

**Comment by Andrews54757** [comment]
Youtube is A/B testing anti botting measures. As a result, faststream is now using the IOS client API. This may result in worse performance if it is being throttled by Google. Try changing the YT client in settings from IOS to another option. Note that it might fail if Google enabled anti-botting on your IP.

**Comment by nightey89** [comment]
why do they have to ruin everything good. thanks

**Comment by chosendango** [comment]
> Youtube is A/B testing anti botting measures. As a result, faststream is now using the IOS client API. This may result in worse performance if it is being throttled by Google. Try changing the YT client in settings from IOS to another option. Note that it might fail if Google enabled anti-botting on your IP.

When using the IOS client the max quality I can use is 1080p is this normal or a bug?

**Comment by Andrews54757** [comment]
The qualities are provided by Google. I'll ask around with ppl who know more about it to see what I can do about it.
