### ISSUE TITLE
[Feature] Variable/customizable buffer size/time?

### ISSUE THREAD

**Issue by nightey89** [Andrews54757/FastStream#202]
Given the latest performance issues, would it be possible for you to implement a customizable buffer either in time or in size? So there is something between the standard 200s and predownload the entire video?

As you explain predownloading an entire video can have quite serious impact on SSD longterm performance, while 200s is not quite enough with recent perfmance.

Would it be possible to implement a feature where users could customize the buffer size themselves? Either in seconds or in Gb? So for example when I have 32Gbs of ram but I only usually use 10 of it, I could predownload another 15gb as buffer, which is currently not possible. 

Or being able to set a custom time that is greater than 200 seconds? 

Not sure how the coding is done, but that would solve some performance issues without putting too much stress on ones SSD.

Happy to hear your thoughts
thanks

**Comment by Andrews54757** [comment]
I've already implemented a change to buffer until the max predownload file size specified in settings. It will be in V1.3.20

**Comment by nightey89** [comment]
oh sweet! cant wait
