### ISSUE TITLE
[Feature/"Bug"] Noticable audio delay compared to native players

### ISSUE THREAD

**Issue by nightey89** [Andrews54757/FastStream#204]
I have noticed that there is a noticable audio delay with your player compared to other native players.

Do you know why that could be? Or if you could do anything about it? 

I just a/b tested with bluetooth (bose qc 35 II) and cabled headphones and when using bluetooth headphones the audio delay adds to the bluetooth delay itself to a point where it gets very irritating following vidoes where people talk.

Ive measure it with an [av sync test](https://www.youtube.com/watch?v=ucZl6vQ_8Uo) to be around 150-200ms delay from the player itself. 

Do you think there is anything you could do about that? Ive found an [old chrome extension](https://github.com/gurux13/chrome-audio-delay) that hasnt been developed for 10 years that tried conquering this issue by implementing a video delay into chromes subsystems similar to a feature in MPC (media player classic) that allows +/- delays for audio.

I dont know anything about coding but is that something that would be feasable to integrate?

**Comment by Andrews54757** [comment]
The audio delay depends on your computer hardware. FastStream itself cannot set it. Nevertheless, I refactored the audio code just in case, so that it is faster on older hardware.

**Comment by Andrews54757** [comment]
Added a video delay option
