### ISSUE TITLE
[BUG] Error when playing videos with audio equalizer nodes set

### ISSUE THREAD

**Issue by jajaborsthan** [Andrews54757/FastStream#205]
**Describe the bug**
Error: Node not connected
disconnect@moz-extension://8dc80583-43c4-4a98-b15f-0b67f6ef60c5/player/ui/audio/VirtualAudioNode.mjs:75:13
refreshEQNodes/<@moz-extension://8dc80583-43c4-4a98-b15f-0b67f6ef60c5/player/ui/audio/AudioEqualizer.mjs:130:29
refreshEQNodes@moz-extension://8dc80583-43c4-4a98-b15f-0b67f6ef60c5/player/ui/audio/AudioEqualizer.mjs:128:25
setupNodes@moz-extension://8dc80583-43c4-4a98-b15f-0b67f6ef60c5/player/ui/audio/AudioEqualizer.mjs:29:12
setupNodes@moz-extension://8dc80583-43c4-4a98-b15f-0b67f6ef60c5/player/ui/audio/AudioConfigManager.mjs:363:25
setSource@moz-extension://8dc80583-43c4-4a98-b15f-0b67f6ef60c5/player/FastStreamClient.mjs:466:33

**Version**
1.3.20.1

**Platform**
Firefox

**Steps to Reproduce**
Get this error message when trying to stream any video on https://web.netmovies.to

**Comment by Andrews54757** [comment]
Fixed
