### ISSUE TITLE
[BUG] Audio profile mixer config not applied when loading video [1.3.20.1]

### ISSUE THREAD

**Issue by eeeeb** [Andrews54757/FastStream#206]
**Describe the bug**
The saved sound profile is not applied when opening a YT video.
Only after clicking on the blue FastStream config icon "Toggle sound config window" it is being applied.
This was working fine in one of the past versions.
I deleted all the profiles and created new ones, but the issue still persists.

**Version**
FastStream version: 1.3.20.1

**Platform**
Chrome 127.0.6533.120 (Official Build) (64-bit) on Windows 11

**Steps to Reproduce**
1. Save and set a profile in the FastStream sound options which lets you identify the profile easily (for example reduce the left volume completely)
2. Open a YT video and play it.
3. Click on the blue FastStream config icon "Toggle sound config window" on the bottom of the video.
4. Notice that the profile is only applied after you open the sound config.

**Comment by Andrews54757** [comment]
Fixed
