### ISSUE TITLE
Limit player instances per tab

### ISSUE THREAD

**Issue by royzen22** [Andrews54757/FastStream#207]
On some web pages with multiple video thumbnails or ads, the player will continue to open new unwanted instances when hovering over thumbnails and even downloading their contents. This can be wasteful not only on pc resources but on data for those with limited data plans or grumpy isp's.

An option if possible to limit player instances to only 1 for the target video we came for on that page.

Amazing extension btw. Thank you so much.

**Comment by Andrews54757** [comment]
Do you have an example website I can test?

**Comment by Andrews54757** [comment]
I've implemented https://github.com/Andrews54757/FastStream/commit/bfa13e001630fae7d91b6ca7455d01ec1752c2f9

this will require user interaction with additional players to enable download acceleration/predownloading. the first player in a tab will not require interaction
