### ISSUE TITLE
[Feature] Option to automatically play video upon loading Faststream

### ISSUE THREAD

**Issue by ocenyx** [Andrews54757/FastStream#209]
**Is your feature request related to a problem? Please describe.**
I am loving this addon so far and want to use it (almost) anywhere in the web. It would be nice to have an option to automatically play the video once Faststream loads.

**Describe the solution you'd like**
I know I am being lazy here because (play) is just one click away, but it can't hurt to ask for a quality of life improvement. Maybe something optional we can toggle on or off in Settings.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by Andrews54757** [comment]
there is an autoplay setting for Youtube. There wont be for other sites because they are not always trustworthy.
