### ISSUE TITLE
[Feature] More Detailed/Accurate Lable for the "Choose Resolution" Icon

### ISSUE THREAD

**Issue by Nvertd** [Andrews54757/FastStream#211]
Add Icons such as FHD, 2K, UHD(4K)... etc instead of only HD and SD (currently) so user can recognise which resolution is chosen at a glance without having to click the Resolution Button.

**Comment by Andrews54757** [comment]
I couldn't find matching icons hence why this isn't available. Feel free to send me a set if you can find one.

**Comment by Andrews54757** [comment]
Done! Thanks for submitting icons to me!
