### ISSUE TITLE
[Feature] Recolor progress bar.

### ISSUE THREAD

**Issue by ChromiaCat** [Andrews54757/FastStream#213]
**Is your feature request related to a problem? Please describe.**
I just think it's nice to change it's color from the boring red.

**Describe the solution you'd like**
A way to change progress bar's color, maybe an option for linear-gradient too would be nice.

**Describe alternatives you've considered**
If in fluidplayer.css on line 380 `background-color` gets changed to just `background`, a simple text box that would become a var for `background` could be used instead, only downside is the user would have to form the css for `background` that they want and not everyone knows how to do that.

**Additional context**
Put it in the back burner if you got other stuff going on, it's not that important.

**Comment by Andrews54757** [comment]
Future TODO..... may take a while.
