### ISSUE TITLE
[Feature] map videos speed to keys 

### ISSUE THREAD

**Issue by OzeanBiene** [Andrews54757/FastStream#214]
the problem to select the speed to set the speed of a video with the press of a keyboard button 

the ability to set a specific speed with a key shortcut

**Comment by Andrews54757** [comment]
Will do with settings page rewrite but may take a while.

**Comment by pintassilgo** [comment]
In addition to a shortcut to preferred speed, I suggest to also add a shortcut to "Reset speed", which should be a command to toggle between current speed and 1x.

These two commands are available in Video Speed Controller, a very popular extension with more than 3 million users in Chrome, but this extension is not compatible with FastStream.
