### ISSUE TITLE
Double click fullscreen by default Single click pause\play by default

### ISSUE THREAD

**Issue by slrgt** [Andrews54757/FastStream#215]
**Is your feature request related to a problem? Please describe.**
It would be great if the FastStream player had the same shortcuts as the rest of the web players

**Describe the solution you'd like**
Having double click fullscreen and single click pause\play videos would make it much more convenient for everyday people to use

Thank you so much for this amazing addon its incredible how fast it makes streaming videos and it looks good.

**Comment by Andrews54757** [comment]
You can already configure click actions in settings. The single-click to hide cursor/controls behavior is borrowed from Apple's QuickTime player. This feature allows for the user to quickly remove obscuring control elements from the video and I consider it to be important for accessibility.
