### ISSUE TITLE
[Feature] Automatic episode detection for subtitles

### ISSUE THREAD

**Issue by slrgt** [Andrews54757/FastStream#216]
The subtitle feature is incredible although it would be nice if it could automatically detect the episode.

**Comment by dimii27** [comment]
I was about to issue this! If it detects the name of the show I think it should be able to also detect whether it is a movie or show and which season/episode it is. I am grateful though that it is fairly easy to look for subtitles without even escaping fullscreen (as long as you keep track of the episodes in your head).

**Comment by Andrews54757** [comment]
Done: https://github.com/Andrews54757/FastStream/commit/7abde092f2e2b674181ecefe3f792b0ecca9194a
