### ISSUE TITLE
[Feature] Better Playback Speed Selector

### ISSUE THREAD

**Issue by Nvertd** [Andrews54757/FastStream#217]
If you want to change the playback speed from 1x to 15x with the current playback speed selector, you would have to scroll for a long time. I am proposing seperating the Whole number and the first decimal places, using a drop down list of sorts, that preferrably have keyboard inputs. This way you can quickly switch from say 1x to 10x, while maintaining the option of fintuning the speed to 10.3x for example.

**Comment by Andrews54757** [comment]
Scroll menus within menus are too user-unfriendly. I also do not think that such high playback rates are often used. May take another look in the future.
