### ISSUE TITLE
[Feature] Customize Button Layout At Bottom Left

### ISSUE THREAD

**Issue by Nvertd** [Andrews54757/FastStream#218]
This is actually 2 features in 1 request

**1. Allow customizing button layout to the bottom left of the screen.**
For example, the forward/backward 10s button was added recently. I think that placing these two buttons beside the play pause button is more logical for me. But it can not be done right now.

**2. Allow Users to hide non-essential buttons**
 As discussed above, i already have hotkeys for 10s forward/backward. I dont really need the buttons.

**Comment by Andrews54757** [comment]
Done
