### ISSUE TITLE
[Feature] Next video button

### ISSUE THREAD

**Issue by Nvertd** [Andrews54757/FastStream#219]
Tied with #218 , If the option to hide non-essential buttons is implemented, I would like to request some buttons that others might find usefull.

1. Next video button
2. "Autoplay next video on Youtube" toggle
3. A link to this github

**Comment by Andrews54757** [comment]
1, and 2: Not yet, because the feature is only available for Youtube.
3: There is a link in the settings page.

**Comment by Andrews54757** [comment]
Implemented next/previous video buttons. It should also work on other sites.

**Comment by Andrews54757** [comment]
Implemented right click next button to change autoplay next setting for session
