### ISSUE TITLE
[Feature] "Disable Reading Video Progress From Local" Toolbar Button

### ISSUE THREAD

**Issue by Nvertd** [Andrews54757/FastStream#222]
A button that can be placed on the tool bar that can quickly disable reading video progress from local storage (for the session), essentially just a shortcut to turn off the "Save progress of videos in local storage".

Use case: I am playing music from a youtube playlist that i have played before, but it keeps playing from the  middle of the videos.

**Comment by Andrews54757** [comment]
FastStream will now ignore saved progress when playing the next video in a sequence.
