### ISSUE TITLE
[Feature] Support for more servers

### ISSUE THREAD

**Issue by dimii27** [Andrews54757/FastStream#225]
I am streaming content from `https://hydrahd DOT com` (use an adblocker to enter this website!), which aggregates multiple streaming services. When you are playing an episode there you are free to change the provider if the speed, quality or stability is an issue for you on a certain one.

The problem is that some of the sources you can select aren't detectable by faststream. So far, I managed to add souce "Delta" with this custom source pattern: `m3u8 /^https:\/\/vidsrc\.pro\/.*\/playlist\.m3u8\.png\?.*$/`.

Also, if it does detect the source it doesn't detect the subtitles embedded in the original player of that source (It has subtitles if you disable FastStream, but if you enable it, those subtitles do not appear and you have to search for other subtitles on OpenSubtitles).

I hope I'm not asking for too much, but I would love FastStream to be able to detect all of the servers embedded on HydraHD and to also grab their subtitles when available (because the subtitles are right there so there's no need to put unnecessary traffic on OpenSubtitles' servers and they even rate limit you if you have too many requests in a short time window).

[Edit]: other aggregators with the same problem are `https://primeflix-web DOT vercel DOT app` `https://www.braflix DOT ru`

**Comment by Andrews54757** [comment]
FastStream does not maintain a list of site-specific source patterns. You must set custom patterns to match sources which do not use standard file extensions yourself. You can set custom source patterns for subtitles by using the `srt` and `vtt` file extensions.

**Comment by dimii27** [comment]
How do I learn to use this language for the custom source patterns? I used the code mentioned before from another issue, it's not mine.

**Comment by Andrews54757** [comment]
There is a wiki page https://github.com/Andrews54757/FastStream/wiki/Custom-Source-Patterns
