### ISSUE TITLE
[BUG] Using Next Video Button On YT In Fullscreen Breaks Webpage

### ISSUE THREAD

**Issue by Nvertd** [Andrews54757/FastStream#226]
https://github.com/user-attachments/assets/83c2b58d-1fdb-46af-a703-cbfffdecb466

**Comment by Nvertd** [comment]
Apparently not just using the next video button, auto play next vid have the same issue

**Comment by Andrews54757** [comment]
Was not a bug. it fallbacked to windowed fullscreen mode when fullscreen permissions were denied. I have since removed the fallback feature to reduce confusion
