### ISSUE TITLE
[BUG] TypeError: channel is undefined

### ISSUE THREAD

**Issue by ocenyx** [Andrews54757/FastStream#229]
**Describe the bug**

Please send this error to the developer at https://github.com/Andrews54757/FastStream/issues
TypeError: channel is undefined
setupNodes/this.channelNodes<@moz-extension://53d3325a-9934-4b6a-805c-3d54c2c7352e/player/ui/audio/AudioChannelMixer.mjs:425:35
setupNodes@moz-extension://53d3325a-9934-4b6a-805c-3d54c2c7352e/player/ui/audio/AudioChannelMixer.mjs:411:31
setupNodes@moz-extension://53d3325a-9934-4b6a-805c-3d54c2c7352e/player/ui/audio/AudioConfigManager.mjs:359:28
setSource@moz-extension://53d3325a-9934-4b6a-805c-3d54c2c7352e/player/FastStreamClient.mjs:527:33

**Version**
1.3.24

**Platform**
Firefox

**Steps to Reproduce**
https://hianime(dot)to/watch/dragons-house-hunting-15692?ep=72202&ep=72202&ep=72202&ep=72202
https://www.youtube.com/watch?v=KLDfcNh5Mm4&list=PL0eyrZgxdwhwQZ9zPUC7TnJ-S0KxqGlrN&index=8

and basically everywhere else I tried

**Comment by ocenyx** [comment]
Fixed by reinstalling. Please close.

My dumb ahh forgot to backup my regex though 😭

**Comment by Andrews54757** [comment]
You can also fix this by going to your audio configs and deleting your profiles. See also #228
