### ISSUE TITLE
[BUG] Does not play videos with multiple audio tracks on YouTube

### ISSUE THREAD

**Issue by DustGalaxy** [Andrews54757/FastStream#23]
**Describe the bug**
Does not play videos with multiple audio tracks on YouTube. For example, videos from Mr. Beast channel are not playing.

**Version**
FastStream 1.2.4

**Platform**
browser Edge 119.0.2151.72 64-bit

**Screenshot**
![image](https://github.com/Andrews54757/FastStream/assets/103292379/89c2c30b-d9d6-4c16-98f3-44e61f885123)

**Comment by Andrews54757** [comment]
Can you link to a specific video?

**Comment by Andrews54757** [comment]
I am unable to reproduce with Chrome or Firefox. Try using Chrome or Firefox and let me know if the issue is still there. If you can, please send me the contents of the page's Javascript log.

**Comment by Andrews54757** [comment]
So far I am unable to reproduce with Edge 119. It plays MrBeast's latest video fine.

<img width="1512" alt="Screenshot 2023-11-25 at 8 03 01 PM" src="https://github.com/Andrews54757/FastStream/assets/13282284/a5394086-ac95-44db-ad7e-a41d5f509555">

**Comment by DustGalaxy** [comment]
Apparently the error pops up on any video with multiple audio tracks.

F12 log
Here are the logs, I think they'll give you the most I can give you.
[www.youtube.com-1701004508527.log](https://github.com/Andrews54757/FastStream/files/13466859/www.youtube.com-1701004508527.log)

I'm also providing a list of extensions that I use.
![image](https://github.com/Andrews54757/FastStream/assets/103292379/8cea7b7f-f817-409e-b870-44520ccefd9c)

**Comment by Andrews54757** [comment]
This looks like it is a bug with [Youtube.js](https://github.com/LuanRT/YouTube.js). I will be contacting them to learn more. Still, I am unable to reproduce this issue. Maybe try disabling some of your extensions?

**Comment by Andrews54757** [comment]
@DustGalaxy Could you please try installing the extension manually from the source here on Github? I think I might have fixed the issue with https://github.com/Andrews54757/FastStream/commit/8fa4bdfc021db60d35f5a64e322e751009d115f9

**Comment by Andrews54757** [comment]
After conversing with Youtube.js' creator, we've come to the conclusion that Youtube is probably reading the `accept-language` header to serve localized content, which might contain non ASCII characters. I've fixed this bug with https://github.com/Andrews54757/FastStream/commit/8fa4bdfc021db60d35f5a64e322e751009d115f9 but setting your language to `english` should also resolve the issue.

Unless you install the latest code manually, the fix will be available in FastStream V1.2.6 in approximately 3-4 days.
