### ISSUE TITLE
[BUG] YouTube videos will not buffer above ~25%

### ISSUE THREAD

**Issue by dakotawhitevalley** [Andrews54757/FastStream#233]
**Describe the bug**
When opening any YouTube video, regardless of the connections being set to 1 or all the way up to 6, the video will stop buffering. Opening the devtools network activity log shows that only the first handful of requests are answered, then the rest will all return a 403. 
![image](https://github.com/user-attachments/assets/7844e9d3-d1d5-49f6-bb83-635acd479bf9)
Scrolling down further through the log shows all requests then continue to 403 unless I disable the extension, which then allows normal playback.
![image](https://github.com/user-attachments/assets/18dee80e-a3ca-4c6d-8e94-c979e38dad54)
While writing this issue, I opened another handful of videos and it wouldn't even buffer to 25%, usually stopped around 10-20% depending on length of video.
![image](https://github.com/user-attachments/assets/e21f9bea-fdad-4416-97c5-148c2851e93a)

**Version**
v1.3.25

**Platform**
![image](https://github.com/user-attachments/assets/95a73e06-ba14-4d64-9a40-34495f1a0576)
uBlock Origin is installed as well, but I have tested this issue while turning it off/on, as well as disabling the built in Brave Shields as well. There is no difference regardless of extensions being turned off/on.

**Steps to Reproduce**
1. Open YouTube
2. Click on the FastStream icon to turn it on
3. Click on literally any video on YouTube
4. Video opens, buffers for a few seconds, stalls and will no longer load

**Comment by Andrews54757** [comment]
This means youtube is doing some blocking shenanigans again. Try downloading the video with yt-dlp, and see if that works.
