### ISSUE TITLE
[BUG] `Flip` is confusing and redundant with `Rotate`

### ISSUE THREAD

**Issue by pintassilgo** [Andrews54757/FastStream#238]
First `Flip` mirrors the video as expected, but the second time you trigger this command the video flips vertically, then flips horizontally again while still upside down.

There's already the `Rotate` command to force video to be upside down. Flip should be only horizontally, so with just 2 states (normal / mirrored).

If for any reason user needs the video upside down + mirrored, it should run `Rotate` twice (for 180º) then `Flip` once.

By the way, to not waste opening a new issue, I believe `Rotate` should be clockwise, but currently it's counterclockwise.

**Comment by Andrews54757** [comment]
Will refactor all that with settings rewrite
