### ISSUE TITLE
[BUG] Player doesn't load if you enter valid URL in location bar

### ISSUE THREAD

**Issue by pintassilgo** [Andrews54757/FastStream#239]
FastStream has this option:

> Use player to play HLS/DASH streams when opening playlist URLs

I suppose this means that if I try to open a `.m3u8` URL in new tab, like [Big Buck Bunny](https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8), the extension should automatically load the player and try to play the video, right? But what currently happens is that browser asks to download the playlist file.

There are extensions such as [Native MPEG-Dash + HLS Playback](https://addons.mozilla.org/en-US/firefox/addon/native-mpeg-dash-hls-playback/) which does this job, it would be good if I can replace it with FastStream.

**Comment by Andrews54757** [comment]
Fixed
