### ISSUE TITLE
[BUG] Fails to recognize URLs with parameters

### ISSUE THREAD

**Issue by pintassilgo** [Andrews54757/FastStream#240]
https://github.com/Andrews54757/FastStream/blob/614bfc660404fcdfeb5686e96be6f2ef7632f2a8/chrome/background/background.mjs#L780

This code only matches URLs ending with the file extension, it fails on URLs with parameters, such as `video.mp4?token=yadayada&expire=1726066490`.

Could replace by something like this:

```js
      regexFilter: '^.+\\.(' + filetypes.join('|') + ')(\\?.*)?$',
```

**Comment by Andrews54757** [comment]
Fixed
