### ISSUE TITLE
Can't find temporary video folder

### ISSUE THREAD

**Issue by formlessdao** [Andrews54757/FastStream#245]
Hi, where can I find the temporary video folder on Fedora distro?
I want to empty it's contents so Faststream re-downloads everything from scratch for a website I'm having trouble downloading from.
It downloaded just fine first time but website tab was closed by mistake ...then it only downloads just a segment every other time I tried it since and from 1 hour that the original video was it only downloads now 5 minutes and no matter how many times I reload the page only those 5 minutes keep being downloaded.

**Comment by Andrews54757** [comment]
Your browser is caching the files, not FastStream. You can clear your browser caches to force your browser to redownload from network.
