### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sen-why** [Andrews54757/FastStream#246]
Started happening after the 14th of September update. After I turn the plugin on the video just disappears from the page. And injected by plugin player appears to be disabled.
![image](https://github.com/user-attachments/assets/fe4035aa-df20-49fa-ac0e-4a449fc003f2)

Version 1.3.27.2
Windows 11, Firefox.
Tried on Brave - same result

Can't share a URL as the page is not public, the only step I take is turn the plug-in on, and reload the page.

**Comment by sen-why** [comment]
Sorry for my stupidity, would've deleted this report if I could.
Upon further inspection I realized that the plug-in is not to blame here and it's the site's owners attempting to fight back on the use of the plug-in.

**Comment by Andrews54757** [comment]
You can open the player in a new tab, and reload your other page. the new tab player will collect sources from other tabs, and you can play them by going into the sources browser.

**Comment by Andrews54757** [comment]
I've updated the video replacement code, so it modifies the site slightly less. https://github.com/Andrews54757/FastStream/commit/51bc8d89eebdc7c7d5ed97ec00d16276104403b8
