### ISSUE TITLE
[Feature] Download Audio Only Button

### ISSUE THREAD

**Issue by Rizkiacry** [Andrews54757/FastStream#247]
My internet is metered and i'd like to watch anme with dubbed version (from hianme) while using a good subtitle (from anmephe).

Softsub in most anme sites is littered and so the idea is to change the audio (from hardsub: anmephe) with dubbed audio (from softsub: hianme)

Adding "change audio source" feature is optional, bc some apps have it and i don't want to bother much

best

**Comment by Andrews54757** [comment]
Faststream does not support use cases which require video editing.
