### ISSUE TITLE
[BUG] Not downloading videos on Firefox 

### ISSUE THREAD

**Issue by DareDevil2000** [Andrews54757/FastStream#248]
**Describe the bug**
As the title says but the same video is downloading in Brave Browser

**Version**
FastStream v1.3.28.1

**Platform**
Firefox 130.0.1

**Steps to Reproduce**
As a sample site https://www.videvo.net/video/scientist-pouring-chemical-in-vaccine-container-4k/5351862/#rs=video-box

**Comment by Andrews54757** [comment]
Related to a bug in Firefox. Try turning off enhanced privacy.

https://bugzilla.mozilla.org/show_bug.cgi?id=1917842

**Comment by DareDevil2000** [comment]
But my privacy is set to standard and there wasn't this problem before

**Comment by RNavarro3000** [comment]
Been experiencing the same issue for some time, kept hoping that a new update would eventually fix it. Had to roll back to an older working version in the meantime.  For me, I hit the save button and FastStream goes through the motions and indicates it has saved the file, but it does not trigger the download within Firefox downloader.  This behavior is not site specific.

1.3.29   - Save not working
1.3.28.1 - Save not working
1.3.28   - Save not working
1.3.27.2 - Save not working
1.3.27.1 - Save not working
1.3.27   - Save not working
1.3.26   - **Save is working**

**Comment by Andrews54757** [comment]
Do you have enhanced privacy protection enabled? Do you use Firefox Multi-Account Containers? Since 1.3.27, FastStream has begun using Firefox's `downloads` API to get around their restrictions in sandboxed Iframes. See #235

**Comment by RNavarro3000** [comment]
I do not use Firefox Multi-Account Containers.  "Enhanced Tracking Protection" is set to Standard.  I manually disabled all protections for my specific test sites (clicked Shield for each site and clicked slider to off) and FastStream 1.3.29 is still not saving.

**Comment by RNavarro3000** [comment]
As a test (my main FF profile is years old), I also just installed a fresh instance of latest Firefox on a Win10 VM, so no baggage in profile or other addons to conflict.  All Firefox settings are default and the only addon is FastStream.  I disabled protections manually and FastStream 1.3.29 is not saving.

**Comment by Andrews54757** [comment]
Okay, so I figured it out. My build script wasn't appending the right permissions to the `dist` version of FastStream. I didn't catch it because I test with the development build. It has since been fixed

**Comment by Andrews54757** [comment]
Fixed in V1.3.29.1 (firefox store only release)

**Comment by WolfganP** [comment]
> V1.3.29.1

The new version seems also fixed https://github.com/Andrews54757/FastStream/issues/195 (no thorough testing but a couple of links in FB and IG worked OK)
Thanks a lot!
