### ISSUE TITLE
[BUG]Opening a youtube video is slow

### ISSUE THREAD

**Issue by Dioswilson** [Andrews54757/FastStream#25]
**Describe the bug**
When opening a youtube video with the player it is significantly slower.
You can see it in this screen recording:
https://github.com/Andrews54757/FastStream/assets/63358200/ac77280b-74f7-4e3c-9489-8f9b773601bd

**Version**
1.2.4

**Platform**
Brave

**Steps to Reproduce**
Open a random video you've never watched with and without the extension

**Comment by Andrews54757** [comment]
This is unfortunately not something I can fix as FastStream replaces Youtube's video player entirely. I use [Youtube.js](https://github.com/LuanRT/YouTube.js) to interface with Youtube's API. That library may take a while to fetch the required information to play. I recommend playing with the default youtube player unless it is blocked or missing some features you need.

**Comment by jacksongoode** [comment]
Is there a way to keep the video player in memory so that it doesn't have to reload the player every time?

**Comment by Andrews54757** [comment]
The main cause of loading times is not due to loading player assets, it is due to slow communications with Youtube's servers. Youtube.js, which FastStream uses, already caches Youtube's keys making the latter delay shorter.
