### ISSUE TITLE
Unknown player mode: auto

### ISSUE THREAD

**Issue by sen-why** [Andrews54757/FastStream#256]
## Version:
1.3.29.1

## Error message:
Unknown player mode: auto

## Stack trace:
```
createPlayer@moz-extension://b04b4775-2da7-4f48-ae7c-208675c6a154/player/players/PlayerLoader.mjs:13:13
setSource@moz-extension://b04b4775-2da7-4f48-ae7c-208675c6a154/player/FastStreamClient.mjs:527:45

```

**Comment by sen-why** [comment]
The error message offered to post, so I did. But with manual switching to Accelerated HLS everything works in this case.

**Comment by Andrews54757** [comment]
How did you get this error? Can you describe what you did?

**Comment by Andrews54757** [comment]
Fixed

**Comment by sen-why** [comment]
I pressed play on a source, while the mode set to Auto Detect.
