### ISSUE TITLE
Ability to zoom or enlarge image

### ISSUE THREAD

**Issue by chicotime1** [Andrews54757/FastStream#257]
If this is already imprelemented, my bad - how do you do it?

Really impressed with the player in every aspect, especially the improvement to buffering. But it would be amazing to be able to zoom as well!

**Comment by Andrews54757** [comment]
Please see https://support.google.com/chrome/answer/96810

**Comment by chicotime1** [comment]
What I mean was the ability to zoom the image within the frame. Useful if, for example, you are watching a video with black bars all the way round it. Or if you want to spit your desktop between two browser windows with work or chat or something on one and a video playing on the other which would be really small as YouTube forces the video frame to follow the window size. 

I can achieve all this by using two extra extensions, one to allow full-screen videos within the browser window frame and another to zoom the video image.

Maybe this is seen as super niche usage but if people realised you could do this I think it would be done more.
