### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ssss7861** [Andrews54757/FastStream#258]
i turn on the the extension but it does not work whenever i play a video on a streaming site, it just does not appear. it worked fine for like a month but now it suddenly stopped working. help please?

**Comment by Andrews54757** [comment]
The website has likely changed to use a custom source pattern. Please see https://github.com/Andrews54757/FastStream/wiki/Custom-Source-Patterns

**Comment by ssss7861** [comment]
> The website has likely changed to use a custom source pattern. Please see https://github.com/Andrews54757/FastStream/wiki/Custom-Source-Patterns

i dont think i understand this quite well but it works with some websites and it does not with the others. none of those sites have mp4 etc. in the url

**Comment by Andrews54757** [comment]
You need to find the URL pattern that corresponds to the video. To do this, you can use the network inspector in developer tools.
