### ISSUE TITLE
[BUG] Doesn't work on YouTube?

### ISSUE THREAD

**Issue by PINPAL** [Andrews54757/FastStream#26]
**Describe the bug**
"Failed to load video" error on YouTube.
Works absolutely fine on any other site I tested.

**Version**
FastStream 1.2.4
Version 118.0.5993.88 (Official Build, ungoogled-chromium) (64-bit)

**Platform**
Chromium Version 118.0.5993.88

**Steps to Reproduce**
1. Install Extension
2. Visit YouTube and begin playback
3. Enable extension

**Screenshot**
![screenshot](https://github.com/Andrews54757/FastStream/assets/18197217/a391d066-bba6-46fa-a878-2acfc27fb9cf)

**Comment by Andrews54757** [comment]
Can you send the Javascript log contents?

**Comment by Andrews54757** [comment]
It works fine for me

<img width="1512" alt="works" src="https://github.com/Andrews54757/FastStream/assets/13282284/a9e47bdb-8990-4e19-8018-9c9d2d20b48b">

**Comment by nilsgng** [comment]
I had this error a few times aswell, refreshing the page always worked for me.
Another similar issue is like something failed to load some parts of the video but refreshing the page also helped

**Comment by PINPAL** [comment]
> It works fine for me
> 
> <img alt="works" width="1512" src="https://private-user-images.githubusercontent.com/13282284/285669561-a9e47bdb-8990-4e19-8018-9c9d2d20b48b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNjEwNjAsIm5iZiI6MTcwMTI2MDc2MCwicGF0aCI6Ii8xMzI4MjI4NC8yODU2Njk1NjEtYTllNDdiZGItODk5MC00ZTE5LTgwMTgtOWM5ZDJkMjBiNDhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDEyMjYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzM2UxYzUxZGIyZjIxMGFkOWNlYTVmNTJhYWU1MzA0Yzc4YmRmMmQxMzdkNTU2NzViN2VhYWY1N2RlZjM3MWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L8XFu5HDBg2nuahNIgjo9lqZapGFPog7WiL3q9ODCwg">

I believe in this screenshot you are using Chrome (guessing from the fact you are signed in?). I don't have Chrome installed on my machine but would be happy to test if needed, the extension doesn't work on "Chromium" itself, I'm using the Ungoogled Chromium build here: https://github.com/ungoogled-software/ungoogled-chromium
It's based upon the main chromium source but without all the extra google "junk" which greatly speeds up the browser and doesn't break adblockers.

**Comment by Andrews54757** [comment]
Can you provide a log from the Javascript Console? Hit f12 to open the developer tools. I don't really intend to support all chromium browsers out there, but I can work on a fix if you can help me identify what causes the issue.
