### ISSUE TITLE
YouTube videos not working

### ISSUE THREAD

**Issue by sunRay004** [Andrews54757/FastStream#261]
**Describe the bug**
Videos on YouTube are not working. Other video sites seem to be ok. 
When turned on during a YouTube video, the video does not load. Video loads without faststream

**Version**
FastStream v1.3.31.1

**Platform**
LibreWolf 131.0-1
tried on normal firefox, also broken

**Steps to Reproduce**
Go to YouTube, and use it on any video

**Comment by Andrews54757** [comment]
try it with chrome. if you're using linux, there may be some issues with some codecs.

**Comment by sunRay004** [comment]
Never mind, its working in LibreWolf now. 

I change anything, so it was probably fixed by turning the pc off and on.

**Comment by sunRay004** [comment]
Another thing: enabling ublock origin seems to significantly speed up the video loading, not sure why.
