### ISSUE TITLE
[BUG] Can't play age restricted YouTube video

### ISSUE THREAD

**Issue by ale5000-git** [Andrews54757/FastStream#262]
**Describe the bug**
Can't play a YouTube video.

**Version**
1.3.31.1

**Platform**
Chrome

**Steps to Reproduce**
Play this:
`youtube.com/watch?v=NWkS9AzIOyM&rco=1`

**Comment by Andrews54757** [comment]
That is because it is an age restricted video. Youtube requires sign-in for those. FastStream cannot make video requests using your account credentials.

**Comment by ale5000-git** [comment]
@Andrews54757
The video can be downloaded without account with: [yt-dlp](https://github.com/yt-dlp/yt-dlp)

Quote from their readme:
`By default, "ios,web_creator" is used, and "tv_embedded", "web_creator" and "mediaconnect" are added as required for age-gated videos.`

Can't you do the same and auto-fallback?

**Comment by Andrews54757** [comment]
FastStream already has a fallback to tv_embedded, it just doesn't work anymore. I'll need to check with YoutubeJS' creator to find out how to fix it.

**Comment by ale5000-git** [comment]
@Andrews54757
Isn't possible to copy the "identification" as done by yt-dlp? (for example: web_creator)

**Comment by ballo** [comment]
Can we at least have a notice that the player isn't working instead of blankness? It took me a while to figure out what the heck was going on when I came across this issue and wasted a lot of time thinking it was my fault
