### ISSUE TITLE
[BUG] Uses the disk like crazy on startup

### ISSUE THREAD

**Issue by NullVerdict** [Andrews54757/FastStream#263]
**Describe the bug**
In general, it is strange that it uses disk so much at startup, my disk latency jumped to 50000 ms, then it stabilizes. Is there any way to smooth or disable this moment? I don't want to see such tricks.

**Version**
v1.3.31.1

**Platform**
Firefox

**Steps to Reproduce**
Open Task Manager and see the disk load

**Comment by Andrews54757** [comment]
How do you know if FastStream is causing this issue? Your computer may be misconfigured. Please describe what steps you followed to cause this issue. Also describe your computer specs and operating system.

**Comment by SashaXser** [comment]
> How do you know if FastStream is causing this issue? Your computer may be misconfigured. Please describe what steps you followed to cause this issue. Also describe your computer specs and operating system.

It's definitely not a system issue, it looks like it's due to preloading or similar. Just look at that delay, I've very rarely ever seen that happen.
![изображение](https://github.com/user-attachments/assets/9d33b143-a470-499b-9888-3d3c0ebb7a68)

**Comment by Andrews54757** [comment]
I don't see FastStream's video player in the first screenshot so it is unlikely it is preloading video content. FastStream's code package is only 3.3 MB, so it shouldn't be caused by code loading either. Do you have any other extensions? What is your operating system?

**Comment by SashaXser** [comment]
> What is your operating system?

Are you serious?

>  don't see FastStream's video player in the first screenshot so it is unlikely it is preloading video content.

![изображение](https://github.com/user-attachments/assets/a74df496-5d0d-4e75-b093-1d18b385f957)

> Do you have any other extensions?

I've disabled extensions in my browser, and I can tell you with certainty. The problem is either in your code or in your dependencies. Test it all in incognito mode, maybe this will help you understand what the cause is.

**Comment by Andrews54757** [comment]
Please keep in mind that your issue may not be replicable in all configurations. We request more information as to find out how to best help you, and it is important for us to be thorough. We appreciate kindness and patience throughout this process and we recommend that you review our community's [Code of Conduct](https://github.com/Andrews54757/FastStream/blob/main/CODE_OF_CONDUCT.md) to help guide your interactions with the FastStream project.
