### ISSUE TITLE
Doesn't work with XtremeStream

### ISSUE THREAD

**Issue by BarrenWardo** [Andrews54757/FastStream#264]
**Describe the bug**
Doesn't work with https://xtremestream.co/

**Version**
1.3.31.1

**Platform**
Chrome

**Steps to Reproduce**
Website has some demo videos - https://xtremestream.co/

**Comment by Andrews54757** [comment]
They appear to be using a custom source URL. Add this to your custom source pattern list in settings.
```
# xtremestream
m3u8 /^https:\/\/[a-zA-Z0-9]*\.xtremestream\.xyz\/player\/xs0\.php\?data=.*$/
```
