### ISSUE TITLE
[BUG] Unable to decode Youtube video using GPU

### ISSUE THREAD

**Issue by leoydm** [Andrews54757/FastStream#266]
**Describe the bug**
FastStream does not pick up a stream that can be decoded by my GPU as the Youtube player.

**Version**
Version1.3.31.1

**Platform**
Chrome

**Steps to Reproduce**
https://www.youtube.com/watch?v=E5SvVMqXDCI
When playing this video in 4K, FastStream always chooses AV1 which cannot be decoded by my GPU, while VP9 stream exists. Maybe it should list all the codecs to choose from, add options to pick up a preferred codec for all Youtube videos, and by default choose the same codec as the Youtube player.

**Comment by ChromiaCat** [comment]
Did you try using an extension like enhanced-h264ify at the same time? That should tell YouTube to not serve you the codecs you don't want.

**Comment by leoydm** [comment]
> Did you try using an extension like enhanced-h264ify at the same time? That should tell YouTube to not serve you the codecs you don't want.

I tried this extension but it doesn't work for FastStream. Also, I notice when I choose resolution 2K or 4K, the color from the player is off and with banding artifacts. Maybe it chooses the HDR stream? It would be easier to diagnose if the player can provide detailed stats for the playing video.
![Screenshot1](https://github.com/user-attachments/assets/1ed96caa-7e20-4b6d-89e3-8a3cbb0c9873)
![Screenshot2](https://github.com/user-attachments/assets/73bf3c03-0e60-4b2d-a9ab-99f6a7b2fb3c)

**Comment by Andrews54757** [comment]
vp9 is deprioritized for now because it requires re-encoding when saving the video as an mp4. we are working on a new demuxer/reencoder/remuxer module.

**Comment by Andrews54757** [comment]
Closing as Future TODO
