### ISSUE TITLE
[Feature] Add the ability to control volume with mousewheel

### ISSUE THREAD

**Issue by BurntMike** [Andrews54757/FastStream#267]
One of my favourite extensions is Enhancer for Youtube. This extension allows you to control the volume of a video with your mousewheel.

Of course, after installing FastStream, the YouTube player doesn't work, and therefore neither does scrollwheel volume adjustment.

If you would please add this functionality to FastStream, that would be amazing. Thanks so much!

**Comment by Andrews54757** [comment]
You can adjust the volume using the scrollwheel by hovering over the volume bar.

**Comment by BurntMike** [comment]
Ah, thanks. In the case of Enhancer, you can do so just by hovering on the video window. Please consider adding this functionality to FastStream too, if you are able. Either way, thanks for an excellent extension!
