### ISSUE TITLE
[Feature] Livestream support

### ISSUE THREAD

**Issue by MausRundung** [Andrews54757/FastStream#268]
**Is your feature request related to a problem? Please describe.**
Well it does currently not work on livestreams

**Describe the solution you'd like**
The ability to also use this on livestreams that are a bit laggy to get a smoother experience with a bit of delay ofc

**Comment by Andrews54757** [comment]
From the readme:

> Livestreams are not supported. They will not be supported in the near future.

**Comment by Zero3K** [comment]
What about in the far future?
