### ISSUE TITLE
[Feature] Version for templemonkey

### ISSUE THREAD

**Issue by Michael1297** [Andrews54757/FastStream#269]
**Is your feature request related to a problem? Please describe.**
Unfortunately, it is currently impossible to install any extensions in Chrome on Android. 

**Describe the solution you'd like**
You can install userscripts through [AdGuard](https://adguard.com/kb/general/extensions/). I want to use this extension in Chrome on Android.🙏

**Comment by Andrews54757** [comment]
From the README

> Please note that there are no plans to make FastStream mobile compatible any time soon. Developing FastStream for Chrome and Firefox for the desktop is already an exhausting endeavor. Supporting mobile on top of all that is too much work for a mere college-student programming hobbyist like me. That said, if you find a way to make it work on more browsers or devices, please feel free to share and make a pull request!
