### ISSUE TITLE
[Feature] Single click and always-on cursor visibility

### ISSUE THREAD

**Issue by ToffeeTrish** [Andrews54757/FastStream#27]
**Is your feature request related to a problem? Please describe.**
I prefer to click on my videos to pause/unpause them, especially when switching to the browser from a different application. Having to click on the browser, and then double click (or press space) to pause/unpause isn't as quick as I'd like.

Additionally, I always like to have my cursor on the screen, and I prefer that the cursor disappears after a few seconds of cursor inactivity, and for it to show back up when I move the cursor. The fact that the cursor is hidden when I click once on the video player is disorienting since I have to search for my cursor again when I want to move it out of the video frame.

**Describe the solution you'd like**
An option in the settings panel to manage these scenarios. One for clicks to pause/unpause (current default is 2, have it a dropdown or a number box), and another one for "cursor hiding conditions" (with the options of "one click", "[number] seconds of inactivity", etc).

**Describe alternatives you've considered**
I could just get used to it but it would be a nice feature for general accessibility :)

**Additional context**
Self explanatory I hope?

**Comment by Andrews54757** [comment]
Okay, I've added a `Single Click to Play/Pause` option. Will be coming in v1.2.6 https://github.com/Andrews54757/FastStream/commit/81a47e7b047700c389e21eb49d5fcf1a6438d46e
