### ISSUE TITLE
[BUG] Failure to load websites 

### ISSUE THREAD

**Issue by 29ayush** [Andrews54757/FastStream#272]
**Describe the bug**
When the addon is enabled, the initial loading of websites ( like youtube, and even unrelated like telegram, etc. ) takes too much time, to the point of unreachable.

**Version**
FastStream v1.3.31.1

**Platform**
Chrome

**Steps to Reproduce**
Just keep the addon installed, and normal browsing errors out for me.

Preferred Solution:
Apart from the actual fix, I would love if privacy permissions can be updated such that addon is allowed accessed only when in use, or to that specific website so that atleast it doesn't impact other sites.  Also would be getting more privacy so would be better.

**Comment by 29ayush** [comment]
<img width="693" alt="Screenshot 2024-10-26 at 9 20 28 PM" src="https://github.com/user-attachments/assets/a1103bc5-aa24-4dbe-b0c6-4e2772d345a6">
For the pages not loading, I see this in console.

**Comment by 29ayush** [comment]
This issue was observed when opening https://web.telegram.org/ . The URL doesn't load if addon is present.
I have previously seen it causing load delays for youtube as well.

**Comment by Andrews54757** [comment]
What settings do you have? Did you have any custom source patterns? I can't reproduce your issue.

**Comment by Andrews54757** [comment]
Unable to replicate

**Comment by 29ayush** [comment]
The settings were pretty default, will try to nail down some steps to reproduce next time it happens.
