### ISSUE TITLE
[Feature] How about a Pause option.

### ISSUE THREAD

**Issue by DareDevil2000** [Andrews54757/FastStream#273]
A pause option that will be used to pause buffering and download.

**Comment by Andrews54757** [comment]
You can use the `-` key (multiple times) to remove downloader threads and effectively pause all buffering. Press the `+` key to add back the downloader threads.

**Comment by Andrews54757** [comment]
Added a keybind to pause downloads

**Comment by DareDevil2000** [comment]
Can it pause the buffering  of the video (Not downloading or its using the same function)  ?  
How about a click able other than a keybind  ?

Also not been added to chrome store .
