### ISSUE TITLE
[BUG] Player disappears and mini player not minimized

### ISSUE THREAD

**Issue by Chucky2401** [Andrews54757/FastStream#276]
**Describe the bug**
When I change tab, or after I scroll down enough to activate the mini player and scroll back to top, the player disappears.
Here a screenshot after scrolling down and up:
![image](https://github.com/user-attachments/assets/74e899e2-9bf0-4f5a-bc4d-4b6418be872e)

And, when the mini player appears, it is not minimized:
![image](https://github.com/user-attachments/assets/1ad1b353-102e-4b42-9eaa-c7c2e4657eab)

**Version**
v1.3.32

**Platform**
Vivaldi browser

**Steps to Reproduce**
On any videos. Change tab or scroll down to activate mini player and go back to top

**Comment by Andrews54757** [comment]
Have you tested it with Chrome or Firefox? It works for me.

**Comment by Andrews54757** [comment]
May be fixed now.
