### ISSUE TITLE
[BUG] can be fix with just refresh but i think is still bug although not too disturbing

### ISSUE THREAD

**Issue by farebyting** [Andrews54757/FastStream#277]
**Describe the bug**
<img width="960" alt="{0402CCA6-40DE-4D79-A20E-EAD10571D5E0}" src="https://github.com/user-attachments/assets/d8bb3985-c548-487e-8c17-1471dc566d11">
The bug is like the UI is out of place where it should be

**Version**
FastStream v1.3.32

**Platform**
Firefox 

**Steps to Reproduce**
Watch video with format that 4:3 or something else and change the zoom to 90 and change back 
to 100

**Comment by Andrews54757** [comment]
Fixed
