### ISSUE TITLE
[Feature] Youtube "Chapters" recognition

### ISSUE THREAD

**Issue by ToffeeTrish** [Andrews54757/FastStream#28]
**Is your feature request related to a problem? Please describe.**
Youtube usually places chapters along the video timeline if the description contains timestamps and chapter names.

**Describe the solution you'd like**
For FastStream to be able to locate these chapters and input them within the timeline.

**Additional context**
![image](https://github.com/Andrews54757/FastStream/assets/139289663/aa56b205-1562-4fce-9c4b-f78cf996f695)
![image](https://github.com/Andrews54757/FastStream/assets/139289663/6f2fef3a-4a97-472b-a4fd-f60c2c259440)

**Comment by Andrews54757** [comment]
I'll put this on my TODO list

**Comment by Andrews54757** [comment]
Chapters support will be available in FastStream V1.2.6 https://github.com/Andrews54757/FastStream/commit/ac5da882474e7c9d3952563b4579efcfa2268371

![image](https://github.com/Andrews54757/FastStream/assets/13282284/94c5d08c-c40c-43f6-9c5f-c32dd303542a)
