### ISSUE TITLE
[BUG] Auto enable does not work with Firefox

### ISSUE THREAD

**Issue by MrGoatsy** [Andrews54757/FastStream#281]
**Describe the bug**
Auto enable does not work with Firefox

I have this regex:
`https:\/\/www\.youtube\.com\/watch\?v=([^&]+)`

**Version**
Latest one

**Platform**
Firefox

**Steps to Reproduce**
Any video, it will not automatically enable the player on Youtube.

**Comment by Andrews54757** [comment]
You may have forgotten to put a tilde `~` before the regex. Try this:

```
~https:\/\/www\.youtube\.com\/watch\?v=([^&]+)
```

From the instructions in settings:

> Will automatically enable the extension upon visiting these URLs and disable upon leaving. One URL per line, pages starting with that URL will also match. **For regex, prepend with a tilde (~)**. One regex per line. To exclude sites, prepend with an exclamation mark (!).
