### ISSUE TITLE
[BUG] didn't worked with a website or so

### ISSUE THREAD

**Issue by ADIOR-enigma** [Andrews54757/FastStream#282]
**Describe the bug**
the fast stream is not working with this website watch.lonelil.ru

**Version**
FastStream version 1.3.32

**Platform**
Firefox (latest version)

**Steps to Reproduce**
Step 1: must have installed firefox
Step 2: go to the website watch.lonelil.ru and install the recommended watch.lonelil.com/extension for it (if needed)
Step 3: start watching a movie and you will see that the fast stream is not working even after turning it on

**Comment by ADIOR-enigma** [comment]
oh and it works sometimes

> **Describe the bug** the fast stream is not working with this website watch.lonelil.ru
> 
> **Version** FastStream version 1.3.32
> 
> **Platform** Firefox (latest version)
> 
> **Steps to Reproduce** Step 1: must have installed firefox Step 2: go to the website watch.lonelil.ru and install the recommended watch.lonelil.com/extension for it (if needed) Step 3: start watching a movie and you will see that the fast stream is not working even after turning it on

**Comment by Andrews54757** [comment]
They likely use a custom video source pattern. FastStream also doesn't work with other extensions that modify video sources.

**Comment by ADIOR-enigma** [comment]
> They likely use a custom video source pattern. FastStream also doesn't work with other extensions that modify video sources.

So how it sometimes works in some cases
