### ISSUE TITLE
[Feature] Support zoom video to hide blackbar

### ISSUE THREAD

**Issue by zzsimplezz** [Andrews54757/FastStream#283]
**Is your feature request related to a problem? Please describe.**
- Some video are 21:9 that will use "black bar" space on 16:9 16:10 screen.
- 
**Describe the solution you'd like**
Set hotkey to zoom video like "Zoom to FIll Video" extension

Thank you for your extension....It's a game-changer

**Comment by Andrews54757** [comment]
Added a video zoom setting
