### ISSUE TITLE
[Feature] Add the subtitle translated by youtube to the fast stream

### ISSUE THREAD

**Issue by farebyting** [Andrews54757/FastStream#288]
**Is your feature request related to a problem? Please describe.**
Can you add a translated subtitles from YouTube can be used in fast stream too :(
<img width="139" alt="{BFCF9454-24A5-4862-81EE-4EC234471BF1}" src="https://github.com/user-attachments/assets/f0ea3a60-529a-4d4d-abf9-c8d26fb9c0db">

**Describe the solution you'd like**

**Describe alternatives you've considered**
Nah just that

**Additional context**
Just that

**Comment by Andrews54757** [comment]
See #185 . We are working on it, but it will require some larger updates.
