### ISSUE TITLE
[BUG] Custom Sources Patterns doesn't detect data:application/vnd.apple.mpegurl link

### ISSUE THREAD

**Issue by Hth4nh** [Andrews54757/FastStream#289]
**Describe the bug**
I have this regex but it's doesn't work:
`m3u8 /^data:application\/vnd\.apple\.mpegurl.*?$/gm`

**Version**
FastStream v1.3.33 (newest)

**Platform**
Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0

**Steps to Reproduce**
1. Apply this pattern to Custom Sources Patterns: `m3u8 /^data:application\/vnd\.apple\.mpegurl.*?$/gm`
2. Open a website using Artplayer.js, containing an HLS link in the form: `data:application/vnd.apple.mpegurl;charset=utf-8,%23EXTM3U%0A%23EXT-X-VERSION%3A3%0A%23EXT-X-TARGETDURATION%3A6%0A%23EXT-X-PLAYLIST-TYPE%3AVOD%0A........` and it's doesn't work
3. Try entering that link manually into Sources Browser and it works fine.

**Comment by Andrews54757** [comment]
This is because the browser does not allow data urls to be intercepted by extensions. On firefox, you may try to disable those restrictions following these steps: https://support.mozilla.org/en-US/kb/quarantined-domains

**Comment by Hth4nh** [comment]
> This is because the browser does not allow data urls to be intercepted by extensions. On firefox, you may try to disable those restrictions following these steps: https://support.mozilla.org/en-US/kb/quarantined-domains

I tried both method from the link you provided and it's still doesn't work
