### ISSUE TITLE
[BUG] vk.com doesn't work

### ISSUE THREAD

**Issue by Winrus-web** [Andrews54757/FastStream#290]
**Describe the bug**
Open any video in VK like for example https://vk.com/video/@alliancefansubvideo?z=video-99628251_456239153%2Fpl_-99628251_-2 and activate FastStream, it plays the song not the video. 

**Version**
FastStream v1.3.33

**Platform**
Vivaldi Browser / Windows 11

**Steps to Reproduce**
Just play a song in VK then open any video in VK and try to activate the FastStream.

**Thank you Andrews54757, for this extension it works perfectly in most websites I use. I found this extension randomly before this I used to download each video to play it without any issues. This extension saves me ton of time and nerves thank you once again. If its okay in the future I will post here all other websites that have issues with FastStream.**

**Comment by Andrews54757** [comment]
It looks like they use a custom source pattern. Add this to the custom patterns list in settings:

```
mpd /^https:\/\/vkvd[0-9]*\.okcdn\.ru\/\?.*&type=1&/
```

**Comment by Winrus-web** [comment]
Thanks!

**Comment by Winrus-web** [comment]
Doesn't work as I said the issue isn't that video is not playing, its just replacing audio instead of video as the audio is in m3u8 and loads faster. 
Audio link:
https://cs1-51v4.vkuseraudio.net/s/v1/ac/cL1h76TW8vJSM4AjSAcHMhIIrrEGMoSfnHCD6R19JmIp08m_kfB0dC1FarplJOSx1iKn-nksOm7vdgBjmqNOvsAfwIcNUfuv70cW9NO-OwdP6KVybnH6F4GmxOoNxbc7umY6MNXSzCos_8-FwqbpPLX0A1yLAWLsFBJA874jQlmDE-4/index.m3u8?siren=1
Video link:
https://vkvd374.okcdn.ru/video.m3u8?srcIp=46.71.209.63&pr=40&expires=1732205262941&srcAg=CHROME&fromCache=1&ms=45.136.22.207&mid=2086199634004&type=2&sig=hlx08lG3jYo&ct=8&urls=185.226.53.203&clientType=13&cmd=videoPlayerCdn&id=1008090679892

**Comment by Andrews54757** [comment]
If there are multiple sources, you can change the source using the sources browser (the yellow chain icon).

**Comment by Winrus-web** [comment]
Thanks that worked!
