### ISSUE TITLE
[Feature] integration with idm and video downloading when page is closed

### ISSUE THREAD

**Issue by mix1607** [Andrews54757/FastStream#294]
as of now when the extension takes over the video it seems to not only not be recognized by idm to help dl the video but for some videos it actually removes the idm panel from the original video even if idm recognized it before the extension took over. 

10/10 update would be if idm could recognize the video and offer a download panel for it, also i dont know if videos continue to download if you close the tab. so once a video downloads it should be able to download in the background even if tab is closed to make downloading from the extension more of an option.

**Comment by Andrews54757** [comment]
FastStream cannot integrate with other extensions within its player because extension pages are isolated from each other.
