### ISSUE TITLE
[BUG] Youtube Autoplay Inconsistent

### ISSUE THREAD

**Issue by Nvertd** [Andrews54757/FastStream#295]
Chrome 131.0.6778.86
FS 1.3.33

AutoPlay on YT inconsistent when Browser not in foreground. Sometimes it plays, sometimes it pauses, Making the browser (sometimes the even the tab is required) in the foreground fixes the issue.

**Comment by Andrews54757** [comment]
This sounds like it is a permissions issue. Browsers will only allow webpages to use autoplay in specific circumstances to prevent abuses like spam video ads. It's not something I can solve without changes to the browser's code.
