### ISSUE TITLE
AI controlled dubbing

### ISSUE THREAD

**Issue by MassiveNinja** [Andrews54757/FastStream#297]
Although their are subtitles and I have used a few times this app and very impressed with how easy and trouble free it is, one thing that could elevate it would be automatic AI dubbing, making the ability to watch things on the internet vastly expanded.

As someone who uses my PC a lot at the same time as gaming/researching/using chats, I would love to be able to not be restricted to english speaking only tv/movies, where focus  on multiple things is key and foremost.

**Comment by Andrews54757** [comment]
I've tried AI generated subbing before using Whisper (see the [whisper-test](https://github.com/Andrews54757/FastStream/tree/whisper-test) branch). however, it required too much computational power and the browser struggled to deliver subtitles live.
