### ISSUE TITLE
Incompatibility with Multi Account Containers

### ISSUE THREAD

**Issue by MrGoatsy** [Andrews54757/FastStream#298]
**Describe the bug**
FastStream does not work in combination with:
https://addons.mozilla.org/en-US/firefox/addon/multi-account-containers/

**Version**
Latest version

**Platform**
Firefox

**Steps to Reproduce**
1. Open a tab using multi account containers
2. Watch a Youtube video
3. Activate FastStream
4. It will open below the player
![image](https://github.com/user-attachments/assets/0e9350a4-aad7-4ddc-aa35-691e4a8b0486)

**Comment by Andrews54757** [comment]
Multi-account-containers doesn't work well with FastStream, eg failed saves. I've been trying to work around it but it is likely Mozilla will have to add new APIs.
