### ISSUE TITLE
[Feature] Playing local videos as well

### ISSUE THREAD

**Issue by 29ayush** [Andrews54757/FastStream#299]
I love this player so much.

Is it possible to also play files in local storage, in web-browser using this player.

**Comment by Perchioz** [comment]
you already can if you drag and drop the file on the player, though I'm not sure if there's any other way to do this.

**Comment by 29ayush** [comment]
Two problems with that
1.) the player doesn't open unless I am on a website ( this is just an minor annoyance though )
2.) Drag and drop is major annoyance
But thanks for the advice.
The subtitles don't load though! 

Alternatively, Now I am trying to play an mkv file, and I installed `pyrobox` to host a webserver locally, which also provides an inbuilt vid player
Now when I open a vid file, it starts playing in browser and I can click my extension icon normally to capture and play.

This works fine, but two issues 
1.) The video is not set to mode Direct, hence unable to play. It is set to accelerated/mp4 ( I have control over the headers here so let me know if I need to modify some response headers ) 
2.) The subtiltes are not loading 

I also created a small html page with code as shown in image.
<img width="1193" alt="Screenshot 2024-12-03 at 11 35 33 PM" src="https://github.com/user-attachments/assets/b26401fd-3610-42e4-a0b8-a104a85937ba">

But here also player doesn't load the subtitle and the mode is not correct.
Let me know if there are any suggestions. ( I am not much familiar with modes etc.) 
Here is the html I am currently using for my page:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Video Player with Subtitles</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            padding: 20px;
        }
        video {
            width: 80%;
            max-width: 800px;
        }
    </style>
</head>
<body>
    <h1>Video Player with Subtitles</h1>

    <video id="videoPlayer" controls>
        Your browser does not support the video tag.
    </video>
    
    <p id="errorMessage" style="color: red;"></p>

    <script>
        // Function to get query parameters from the URL
        function getQueryParameter(param) {
            const urlParams = new URLSearchParams(window.location.search);
            return urlParams.get(param);
        }

        // Get the filename from the URL query parameter
        const fileName = getQueryParameter("file");

        if (!fileName) {
            document.getElementById("errorMessage").textContent = "File parameter 'file' is required in the URL.";
        } else {
            // Set up the video player
            const videoPlayer = document.getElementById("videoPlayer");
            const videoSource = document.createElement("source");
            videoSource.src = `http://localhost:6969/${fileName}`;  // Assuming the file is served via the server
            videoSource.type = "video/mp4";  // Adjust this if necessary (for example, "video/webm" for .webm files)
            videoPlayer.innerHTML = '';  // Clear existing sources
            videoPlayer.appendChild(videoSource);

            // Fetch subtitle tracks
            fetch(`/localsub/alltracks?file=${fileName}`)
                .then(response => response.json())
                .then(data => {
                    if (!data || Object.keys(data).length === 0) {
                        document.getElementById("errorMessage").textContent = "No subtitle tracks found for this file.";
                        return;
                    }

                    // Loop through subtitle tracks and add them to the video player
                    Object.keys(data).forEach(label => {
                        const track = document.createElement("track");
                        track.kind = "subtitles";
                        track.label = label;
                        track.src = `/localsub/track?id=${data[label]}`;
                        videoPlayer.appendChild(track);
                        if (label=="eng") {
				track.default = true;
			}
                    });
                })
                .catch(error => {
                    document.getElementById("errorMessage").textContent = "Error loading subtitle tracks: " + error.message;
                });
	    videoPlayer.load();
        }
    </script>
</body>
</html>
```

**Comment by Andrews54757** [comment]
You can already open the player by opening a new tab and clicking the icon. the subtitles not loading may be caused by the `.vtt` extension occurring after the `?` query operator. contents after the query operator are ignored.

**Comment by 29ayush** [comment]
> You can already open the player by opening a new tab and clicking the icon. the subtitles not loading may be caused by the `.vtt` extension occurring after the `?` query operator. contents after the query operator are ignored.

Thanks, I changed the subtitle url, and it worked.
Is there also something I can change somewhere so that extension opens link in `DIRECT` mode.
