### ISSUE TITLE
Conversion to mp4 occasionally fails in FastStream 1.1.17

### ISSUE THREAD

**Issue by gt-nik** [Andrews54757/FastStream#3]
Hi Andrew,

Browser: Firefox 119.0.0 portable (running from HDD)
FastStream Video Player: 1.1.17.0

- This version is very good.
- The first time i tried to download a movie, using this version, it failed because Firefox portable running from a usb drive had not enough free space to save the temporary data! (i know that firefox cannot stream files directly to the downloads folder and must use IndexedDB in profile folder that is in my usb drive)
- Running Firefox portable from HDD, i successfully download 5 movies from different sites. The total download time is identical to Edge's extension (FS 1.1.17.0), CPU load and RAM are normal too !

Ηowever, it failed to download next movie (the player is working good)
Movie page: https://www.megatv.com/tvshows/1228829/epeisodio-33-42/
I press FS Download button + Confirm save as name + ok > Alert: Failed to save video! Would you like to archive...  [console-export-2023-11-3_14-17-21.txt](https://github.com/Andrews54757/FastStream/files/13250043/console-export-2023-11-3_14-17-21.txt)

Thank you

**Comment by Andrews54757** [comment]
Fixed in V1.1.18
