### ISSUE TITLE
[Feature] Integrate lossless scaling capabilities, including frame generation, video upscaling, and sharpening, for enhanced video watching experience.

### ISSUE THREAD

**Issue by x-legion** [Andrews54757/FastStream#301]
[Lossless Scaling](https://store.steampowered.com/app/993090/Lossless_Scaling/)

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when watching videos in the FastStream player, as I often encounter issues with video quality and frame rates, especially on low quality videos. The current player lacks advanced features like frame generation and video upscaling, which would significantly enhance the viewing experience.

**Describe the solution you'd like**
I would like to see the integration of a Lossless Scaling feature within the FastStream Video Player. This would allow users to enjoy enhanced video playback through frame generation, video upscaling, and video sharpening capabilities. Implementing this feature would improve overall video quality and provide a smoother viewing experience, particularly for users with varying hardware capabilities.

**Describe alternatives you've considered**
I have considered using standalone video enhancement software or other players that offer similar features, but these options often require switching applications and do not integrate seamlessly with FastStream. Additionally, relying on external software may lead to compatibility issues or reduced performance.

**Additional context**
Integrating Lossless Scaling into FastStream could position the player as a more versatile and powerful tool for video playback. This enhancement would not only attract more users but also improve satisfaction among existing users who seek better performance and quality. I believe that adding this feature aligns well with FastStream's goal of providing an accessible and efficient video experience. Thank you for considering this request!

**Comment by Andrews54757** [comment]
Unfortunately, this is not possible in the browser due to computational limitations.

**Comment by x-legion** [comment]
> Unfortunately, this is not possible in the browser due to computational limitations.

Another solution would be to add an option to open the PIP mode in original video resolution, while still allowing the use of the player's default shortcuts. Third-party apps like lossless scaling could then be used alongside the player.

**Comment by Andrews54757** [comment]
That is also unfortunately not possible as PiP mode is controlled by the browser. I have implemented Document PiP for the new page player (open new tab and click icon) for Chrome, however, it is not available for the Iframe player due to https://github.com/WICG/document-picture-in-picture/issues/97
