### ISSUE TITLE
[BUG] Youtube not loading video

### ISSUE THREAD

**Issue by mansrm81** [Andrews54757/FastStream#302]
**Describe the bug**
When trying to use the extension to play any video on youtube it never starts to buffer and just has the spinning wheel loading. I looked in the extension errors and it says 403 on load or something like that. I have no idea how to get a file that shows said errors with the extension.

**Version**
FastStream 1.3.35

**Platform**
Using Brave browser

**Steps to Reproduce**
Just try and load any video on youtube and none will load and start buffering was fine yesterday.

**Comment by Andrews54757** [comment]
It looks like Google changed something again, will investigate a fix.

Related issue: https://github.com/LuanRT/YouTube.js/issues/831

**Comment by Andrews54757** [comment]
Fixed in V1.3.36.
