### ISSUE TITLE
[Feature] Firefox version the following extensions do not have shortcuts

### ISSUE THREAD

**Issue by Jert865** [Andrews54757/FastStream#303]
**Is your feature request related to a problem? Please describe.**
The firefox browser does not have a quick activation function via hotkeys.

**Describe the solution you'd like**
Add a quick activation function via keyboard shortcuts in the firefox browser

**Describe alternatives you've considered**
Take it from the Chrome version and cram it into the firefox browser

**Additional context**
![Manage Extension Shortcuts Firefox](https://github.com/user-attachments/assets/5d9a3544-ae6e-4776-85f4-2c0cabb4f9d0)

**Comment by Andrews54757** [comment]
The extension activation keybind is controlled by the browser. It appears that Firefox does not add this keybind by default. I will try adding it manually.
