### ISSUE TITLE
[BUG?] YouTube universally not loading fragments.

### ISSUE THREAD

**Issue by ObscenityIB** [Andrews54757/FastStream#304]
**Describe the bug**
YouTube started annoying me with constant buffering again, so I gave FastStream another try, as it didn't work for me a few weeks back, and it still didn't work for me today.

Interestingly, even with FastStream uninstalled, YouTube is still giving 403 errors to video fragments in their own player.

I even replaced my network card thinking it was on my end, and it did not resolve YouTube's constant buffering and rejecting fragments in its own player.

Is there something that is left behind that messes up YouTube in this way?

**Version**
FastStream v1.3.35
FastStream v1.3.36
FastStream v1.3.37

**Platform**
Firefox 134.0a1
Firefox 135.0a1

**Steps to Reproduce**
Watch any video with either FastStream installed or not, fragments will start getting denied access regardless.

Example Video: https://www.youtube.com/watch?v=FLst31H5T6g&t=379s

The timestamp is just there because every time YouTube buffers, which is every few seconds, I have to right-click, copy the timestamp, and then paste it into the address bar to force it to load more of the video.

Refreshing the page doesn't work because it forgets what point I am at in the video and goes back to the start, which is another YouTube issue unrelated to FastStream, I don't know if FastStream's local timestamp storage works, as it has yet to actually play any video.

**YouTube Player:**
![yt01](https://github.com/user-attachments/assets/def014ae-8b51-4bf7-bd3a-aeb55de07e23)
![yt02](https://github.com/user-attachments/assets/30148bb8-86c1-448a-af9b-4cb89aa7975a)

**FastStream Player:**
![yt03](https://github.com/user-attachments/assets/369b58c5-9a3d-4b42-9d09-4c9f6a04f7e2)

**Comment by Andrews54757** [comment]
It might mean that you have been IP-banned by Google. Try changing your IP address.

**Comment by ObscenityIB** [comment]
> It might mean that you have been IP-banned by Google. Try changing your IP address.

No dice there, same thing, also affects chromium, which I only use for sites that refuse to work on Firefox.

yt-dlp seems to work fine using the same cookies Firefox is using.

Clearing site data and logging in again didn't change it either

Searching around more online, it seems to be a common consensus that YouTube is running tests to block 3rd party software, which is even more weird that their own player doesn't work, but yt-dlp does, and so does a modded android client.

Edit: Also found that alternative frontends work fine too.

**Comment by ObscenityIB** [comment]
Resolved.

Cause was a network-wide DNS block on `jnn-pa.googleapis.com`, this was useful in the past, but now YouTube seems to be checking if the domain was blocked, then denying access to video data.

https://github.com/jdlingyu/ad-wars/blob/e52547153aa2b541f09c4c354aa64fb0d8d914a3/hosts#L803
`127.0.0.1 jnn-pa.googleapis.com`
