### ISSUE TITLE
[Feature] Dual Keybinds for Play/Pause

### ISSUE THREAD

**Issue by Nvertd** [Andrews54757/FastStream#305]
Allow for binding multiple (two) keys to play and pause button.

**Comment by Andrews54757** [comment]
Will do with settings rewrite

**Comment by Rizkiacry** [comment]
> Allow for binding multiple (two) keys to play and pause button.

i use this:
<img width="443" alt="image" src="https://github.com/user-attachments/assets/76a3b273-cb00-4ad1-b70d-dadc23a93421" />
