### ISSUE TITLE
[Feature] Add SponserBlock and AdBlock Features

### ISSUE THREAD

**Issue by ghyujkilop** [Andrews54757/FastStream#312]
**Is your feature request related to a problem? Please describe.**
It doesn't seem [SponsorBlock - Skip Sponsorships on YouTube](https://github.com/ajayyy/SponsorBlock) is compatible with FastStream.

**Describe the solution you'd like**
Possibly use their API Similar to what ReVanced would do to block ads.

**Describe alternatives you've considered**
Tried working both together. It seems SponserBlock overwrites the features of FastStream.

**Comment by Andrews54757** [comment]
Duplicate. Please see #66 .
