### ISSUE TITLE
arrow keys eaten by player

### ISSUE THREAD

**Issue by GeorgeRNG** [Andrews54757/FastStream#36]
**Describe the bug**
When playing a youtube video, arrow buttons are eaten by volume and skipping

**Version**
v1.2.7.1

**Platform**
Firefox

**Steps to Reproduce**
I tested this on a brand new profile, so nothing else should interfere
open a youtube video, click on anywhere which isn't video and not link, for example comment text, and try using up and down arrows to navigate.
Instead of scrolling the video player takes the keypresses as controls.

**Comment by Andrews54757** [comment]
Fixed. Thanks for the report! Fix will be available in 1.2.8
