### ISSUE TITLE
Bug: Generating DASH manifests for live and Post-Live-DVR videos is not supported

### ISSUE THREAD

**Issue by FlamedDogo99** [Andrews54757/FastStream#37]
**Describe the bug**
FastStream does not work for post-live-DVR videos on youtube.
**Version**
v1.2.8
**Platform**
Chrome
**Steps to Reproduce**
Go to an [archived live video](https://www.youtube.com/watch?v=gUpgtJGiDKc), enable the fast stream extension, and view the logs. I've attached mine below using the example link provided: [extension.log](https://github.com/Andrews54757/FastStream/files/13625636/extension.log).
**Feedback**
This is a wonderful extension, keep up the great work!

**Comment by Andrews54757** [comment]
@FlamedDogo99 Thanks for the report. Live streams are not supported by FastStream. Adding live stream capabilities will require major changes to the code, and so isn't planned for the near future. This is not without trying, I've spent several hours trying to add support for it using the built in DASH and HLS libraries, however, I keep getting unexpected errors on Youtube live streams such as `getCurrentDVRInfo()` being `null` (I suspect Youtube has a custom format for their streams).

That said, I'm not sure why it didn't work for you with the example video you provide. FastStream works fine for that video for me.

![image](https://github.com/Andrews54757/FastStream/assets/13282284/0e9cda43-2639-4b4d-995c-e338337e030b)

**Comment by FlamedDogo99** [comment]
@Andrews54757 Thanks for the prompt reply, and for attempting to implement support for live streams. The video does work now, so I'm not sure what changed. I suspect user error.
