### ISSUE TITLE
[BUG] Videos from crunchyroll don't work

### ISSUE THREAD

**Issue by AgustinOrdonez** [Andrews54757/FastStream#40]
**Describe the bug**
When I try to watch videos on https://www.crunchyroll.com/ the player keeps loading indefinitely, I first thought it was because it might be DRM protected content, but I don't get any error message, it just keeps on loading 

**Version**
1.2.8

**Platform**
Brave

**Steps to Reproduce**
1-Go to any video on crunchyroll for example: https://www.crunchyroll.com/es/watch/G69XGG44R/ryomen-sukuna
2-Enable the extension

**Comment by Andrews54757** [comment]
Fixed infinite loading. It should now show error message saying DRM isn't supported (they use DRM).
