### ISSUE TITLE
[Feature] support free content by simple version

### ISSUE THREAD

**Issue by Rahjooyan** [Andrews54757/FastStream#42]
Hi, may you provide simple version of this extension just to upload subtitle with subtitle settings like this version for it to support free content from these sites without download or screenshot and ... buttons:

https://www.youku.tv
http://iq.com/

Thanks.

**Comment by Andrews54757** [comment]
Unfortunately, this is not possible with FastStream. For doing something similar I suggest that you use other extensions such as substital
