### ISSUE TITLE
[BUG] default playback speed doesn't work

### ISSUE THREAD

**Issue by AgustinOrdonez** [Andrews54757/FastStream#43]
**Describe the bug**
When a default speed is set although player shows the speed is set at the asked speed the actual playback speed is still x1 until I change it manually.
I've seen this happen only on youtube.

Example in video below

https://github.com/Andrews54757/FastStream/assets/104699326/7832a8ae-5e12-4ae2-a927-53a847de6f45

**Version**
1.2.8

**Platform**
Brave

**Steps to Reproduce**
Set default playback speed to the desired speed.
Play youtube videos after

**Comment by Andrews54757** [comment]
Thanks for letting me know! This was reported earlier today and I've fixed it already. V1.2.10 is awaiting approval for the Chrome web store.
