### ISSUE TITLE
[Bug] Chrome Video Placement Issues on Youtube

### ISSUE THREAD

**Issue by AgustinOrdonez** [Andrews54757/FastStream#46]
**Is your feature request related to a problem? Please describe.**
Problema: When watching videos(mainly youtube or similar) sometimes there are annoying adds (like raid shadow legends)

**Describe the solution you'd like**
I was wandering if it would be possible to integrate something like [sponsor block](https://chromewebstore.google.com/detail/sponsorblock-para-youtube/mnjggcdmjocbbbhaepdhchncahnbgone) to skip this adds, I know this only works for youtube but maybe could be extended to work on other sites? Or maybe just have the feature for youtube

**Describe alternatives you've considered**
Skipping by 10 seconds steps until the add finishes, but not to great

**Additional context**
In this extension you can personalize which types of adds to skip automatically and which to prompt  for skipping, maybe have something similar? If not I'd prefer always asking just in case

**Comment by Andrews54757** [comment]
Basic sponsorblock support is already available. You have to install the sponsorblock extension too for it to work

**Comment by AgustinOrdonez** [comment]
How do you enable it? I can't find any option and it doesn't work out of the box

**Comment by Andrews54757** [comment]
It should work right away, what version of FastStream and Sponsorblock are you using? What browser?

**Comment by Andrews54757** [comment]
Heres what it should look like:

![image](https://github.com/Andrews54757/FastStream/assets/13282284/26788472-3e65-415b-bdf3-3e0cc512c838)

**Comment by AgustinOrdonez** [comment]
Not working for me:
![image](https://github.com/Andrews54757/FastStream/assets/104699326/9a3c5498-0fa5-4579-84d5-27cc7c6832a8)

Browser is brave and sponsor block version is 5.4.28.
Does it use the same extension I sent? Maybe I am using another one

**Comment by AgustinOrdonez** [comment]
Doesn't work on chrome either, it even renders weirdly on top of the original player and breaks if I enter and exit fullscreen
(breaks=audio keeps playing but video disappears)

![image](https://github.com/Andrews54757/FastStream/assets/104699326/5a079b08-2b30-46ca-a934-00ec16774e67)

**Comment by Andrews54757** [comment]
You are probably using an outdated version of faststream, check to make sure it is version 1.2.10

**Comment by AgustinOrdonez** [comment]
Nervermind it actually works now. Chrome issue persists but sponsor block is working

**Comment by AgustinOrdonez** [comment]
> You are probably using an outdated version of faststream, check to make sure it is version 1.2.10

I am using 1.2.10 on both, just istalled it on chrome and I updated brave's today

**Comment by Andrews54757** [comment]
Weird, I've never seen that happen to me. Are you using any other extensions for Youtube? or maybe it's related to youtube in Argentina specifically.

**Comment by Andrews54757** [comment]
Hmm, tested it with Netherlands Youtube, seems to work fine.

![image](https://github.com/Andrews54757/FastStream/assets/13282284/3b41d9f6-e184-492a-8d22-466a6d2d023b)

**Comment by AgustinOrdonez** [comment]
Only extensions in chrome are FastStream and Sponsor block

**Comment by Andrews54757** [comment]
weird. it's not dark mode either.
![image](https://github.com/Andrews54757/FastStream/assets/13282284/6abe857e-9872-4e2a-afe9-0c0bc87e24ad)

**Comment by AgustinOrdonez** [comment]
VPNing through Netherlands, still the same issue
![image](https://github.com/Andrews54757/FastStream/assets/104699326/187e5e42-a369-4ef4-9692-e845b7b0fc50)

**Comment by Andrews54757** [comment]
What happens if you resize the window? Like, shrink the size of the browser window.

**Comment by AgustinOrdonez** [comment]
If I start with chrome on fullscreen it happens. If I start on windowed (Small/medium size) I can stretch it to fullscreen and then it works

**Comment by Andrews54757** [comment]
that is really bizarre. Right click the video, click inspect element. Can you find the video player's `<iframe>` and send a picture of what it is in? Like this:
![image](https://github.com/Andrews54757/FastStream/assets/13282284/8623e0e7-8bbe-485a-bc93-555f29cdedeb)

**Comment by AgustinOrdonez** [comment]
Not sure if this is the one:
```HTML
<iframe src="chrome-extension://kkeakohpadmbldjaiggikmnldlfkdfog/player/index.html?frame_id=0" style="width: 100px !important; height: 100px !important; padding: 0px !important; opacity: 1 !important; visibility: visible !important;" class="skeleton flexy" allowfullscreen="" allow="autoplay; fullscreen; picture-in-picture"></iframe>
```
The video disappears when the HTML displays.
If I strart with the console opened(and player doesn't disappear):
```HTML
<iframe src="chrome-extension://kkeakohpadmbldjaiggikmnldlfkdfog/player/index.html?frame_id=0" style="width: 927px !important; height: 521.438px !important; padding: 0px !important; opacity: 1 !important; visibility: visible !important; position: relative; z-index: auto; border: 0px none rgb(0, 0, 0); border-radius: 0px; box-shadow: none;" class="style-scope ytd-watch-flexy" allowfullscreen="" allow="autoplay; fullscreen; picture-in-picture"></iframe>
```

**Comment by Andrews54757** [comment]
Yes thats the right element. Can you show me what its inside? the surrounding elements.

**Comment by Andrews54757** [comment]
Can you try this version? I think I might have a solution:
[chrome-libre-faststream_video_player-1.2.10-test2.zip](https://github.com/Andrews54757/FastStream/files/13655118/chrome-libre-faststream_video_player-1.2.10.zip)

**Comment by AgustinOrdonez** [comment]
> Yes thats the right element. Can you show me what its inside? the surrounding elements.
I am not being able to just copy it. Here is a screenshot
![image](https://github.com/Andrews54757/FastStream/assets/104699326/89b86c75-3957-4c6e-95b3-1af10e4f326c)

**Comment by AgustinOrdonez** [comment]
> Can you try this version? I think I might have a solution: [chrome-libre-faststream_video_player-1.2.10-test2.zip](https://github.com/Andrews54757/FastStream/files/13655118/chrome-libre-faststream_video_player-1.2.10.zip)

Will do

**Comment by AgustinOrdonez** [comment]
> Can you try this version? I think I might have a solution: [chrome-libre-faststream_video_player-1.2.10-test2.zip](https://github.com/Andrews54757/FastStream/files/13655118/chrome-libre-faststream_video_player-1.2.10.zip)

Yep, that fixed it

**Comment by Andrews54757** [comment]
Okay, thanks!
