### ISSUE TITLE
[Feature] Scrollwheel for Volume Control

### ISSUE THREAD

**Issue by PINPAL** [Andrews54757/FastStream#47]
**Is your feature request related to a problem? Please describe.**
Many video players offer the ability to use the scroll wheel to control volume this makes it very easily to quickly adjust volume on the fly.

**Describe the solution you'd like**
A option in the settings to enable using the scroll wheel to control volume or being able to assign mouse shortcuts as key binds. 
If adding it as an individual feature as opposed to a key bind change, it may be useful to handle it like many other extensions do and provide an option that makes it such that the scroll volume only works when left or right click is held.

**Describe alternatives you've considered**
Attempting to rebind Volume Up/Down to mouse scroll from the settings panel.

**Additional context**
Some example programs of the feature in action:
- YouTube Enhancer (Extension)
- MPV (Video Player)

**Comment by Andrews54757** [comment]
You can already scroll over the volume icon to change the volume. I highly recommend changing the volume using your computer's system controls. Changing the volume using the browser (especially when boosting) will reduce your audio quality.
