### ISSUE TITLE
[Feature]Add option to have default volume level

### ISSUE THREAD

**Issue by AgustinOrdonez** [Andrews54757/FastStream#48]
**Is your feature request related to a problem? Please describe.**
I usually have my system volume high and decrease the volume acrodingly, with this extension I have to lower the volume every time I open a new video

**Describe the solution you'd like**
I'd like to set a default volume, maybe  this could be done by domain, since volume might be different between streaming sites.
If done this way I guess some way of implementing it is saving the current volume into memory when the player is closed or smth similar. If it is not per domain I would still like to not get into extension's settings and have it being automatically persistant (if possible, ofc)

**Comment by Andrews54757** [comment]
You can already set a default volume level by setting an audio profile in the audio config window. Click the blue soundwave icon to open the audio config window.
