### ISSUE TITLE
[Feature] Couple of enhancements

### ISSUE THREAD

**Issue by acrane13** [Andrews54757/FastStream#49]
**Describe the solution you'd like**
2 Suggestions:

1. Pause/un-pause video with mouse click
     Right now it looks like the video will start playing, upon load, with a mouse click on the video. I'd love to see the video pause and un-pause when you click anywhere on the video after the initial start of playback. Just like pressing the spacebar does now.

2. When video controls auto-hide, have the video progress show at the bottom at 1-2 pixels tall
     When the video begins playing, or during mouse hover, the controls automatically show, including a progress bar of video played and buffered. It would be great that when the video controls auto-hide, that progress bar is shown at the bottom of the video, but not as tall  as the shown video controls height. Maybe only 1-2 pixels. That way it's easy to glance at the video and find out how much of the video you've seen and how much might be left.

Thanks for a great extension!

**Comment by Andrews54757** [comment]
@acrane13 There is already an option to enable single click play/pause in the settings. I'll consider the second suggestion, but I'll probably just have the controls stay visible when the video is paused unless hidden explicitly by the user.

**Comment by Andrews54757** [comment]
Implemented paused control bar visibility https://github.com/Andrews54757/FastStream/commit/ca142bf30fd73ee685b87ba9702f8cb699cf46ff
