### ISSUE TITLE
add YT default tab anywhere to pause video

### ISSUE THREAD

**Issue by bachig26** [Andrews54757/FastStream#5]
current drawback of the FastStream is that, the video can only played/paused by using the spacebar or the clicking over the play/pause button.
the standard tap anywhere on the video player to play/pause them doesn't work.

I would like to see this be added or fixed with the extension.

**Comment by Andrews54757** [comment]
Thank you for your suggestion.

https://github.com/Andrews54757/FastStream/commit/050bbded42eb0958101c1ae87fada68a46046848 adds support for playing the video for the first time by clicking anywhere on the video. Afterwords, clicking once will hide the player controls as usual. Double click to toggle play/pause after playing for the first time.

This feature will be available in version 1.1.20

**Comment by Andrews54757** [comment]
1.1.20 has been released. Approval may take several days.
