### ISSUE TITLE
[BUG] Misaligned video or duplicate controls

### ISSUE THREAD

**Issue by ale5000-git** [Andrews54757/FastStream#50]
**Describe the bug**
Misaligned video or duplicate controls.

**Version**
FastStream V1.2.12

**Platform**
Firefox

**Steps to Reproduce**
Sample page: animesaturn.tv/watch?file=hc6G2-Xth9yC-

If I play the video first then enable FastStream then there are duplicate play/pause controls;
instead if I enable FastStream before playing the video then the video bevome misaligned.

**Comment by Andrews54757** [comment]
Fixed. Will be released in V1.2.13

**Comment by ale5000-git** [comment]
Thanks :-)
