### ISSUE TITLE
[BUG] Full size video redirected to empty player

### ISSUE THREAD

**Issue by ale5000-git** [Andrews54757/FastStream#52]
**Describe the bug**
Empty player (no source loaded)

**Version**
FastStream V1.2.13

**Platform**
Firefox

**Steps to Reproduce**
Sample: vidhidepro.com/v/y77gqfpck5fu
When FastStream is enabled it exit from the site and just display an empy player (without loading any source) on `moz-extension://`...

**Comment by Andrews54757** [comment]
Fixed in https://github.com/Andrews54757/FastStream/commit/9825e100e79c206ec56887afadfb782e5673bfc0
