### ISSUE TITLE
[BUG] Vimeo videos not loading

### ISSUE THREAD

**Issue by AgustinOrdonez** [Andrews54757/FastStream#56]
**Describe the bug**
When opening a video inside [this blog](https://calcworkshop.com/number-theory/modular-arithmetic/) the player keeps loading infinitely without throwing any errors

**Version**
1.2.13

**Platform**
Brave

**Steps to Reproduce**
Open the link search for the video(nearly at the end of the page) and try to play it with FastStream

**Comment by Andrews54757** [comment]
They use Vimeo as their video hosting service. Vimeo uses a custom JSON video stream format. I will see what I can do.

**Comment by Andrews54757** [comment]
Vimeo support added in https://github.com/Andrews54757/FastStream/commit/2ed8f2e11cabe9740f07723c74a484b1f10d8c1c
