### ISSUE TITLE
[BUG] Video not detected on vixcloud.co

### ISSUE THREAD

**Issue by ale5000-git** [Andrews54757/FastStream#57]
**Describe the bug**
Video not detected

**Version**
FastStream V1.2.14

**Platform**
Firefox

**Steps to Reproduce**
Sample: vixcloud.co/embed/174815?token=003084ceaf8ed6503e1ec46acd12547c&referer=&expires=1708202437&canPlayFHD=1

The video isn't detected

**Comment by Andrews54757** [comment]
Add this to the custom source patterns input:

```
# Fix for https://vixcloud.co/
m3u8 /^https:\/\/vixcloud\.co\/playlist\/[0-9]+/
```

**Comment by ale5000-git** [comment]
Thanks very much.

Is there an easy way to look for these playlist links?
Maybe some debug options in the extension?

**Comment by Andrews54757** [comment]
You have to monitor network requests manually. Open developer tools, click the network tab, and inspect each request manually. Every website is different. For security/privacy reasons, there is currently no good way of intercepting the contents of every request with a Manifest V3 chrome extension. FastStream only has the header information.

**Comment by ale5000-git** [comment]
@Andrews54757
There is a minor issue on the same link, the original video take all the screen without scrollbars but when replaced by FastStream then scrollbars appears making a small part of the video go outside the screen.

**Comment by Andrews54757** [comment]
Fixed in https://github.com/Andrews54757/FastStream/commit/4befe5ae617d7e1bc499a163f87950edae6d34a2
