### ISSUE TITLE
[BUG] The extension doesn't work on gojopooltt.su

### ISSUE THREAD

**Issue by Mioni** [Andrews54757/FastStream#59]
First of all, thank you very much for this beautiful extension!

**Describe the bug**
I've already set it to pick up automatically by entering the url, but it still doesn't work

**Version**
1.2.15

**Platform**
Vivaldi

**Steps to Reproduce**
[Please tell us how to reproduce the issue. A URL to a specific video is encouraged.](https://gojopooltt.su/player/pgo.php?token=e8b3a0a40bd3720a42beab6fe60401b2)

**Comment by Andrews54757** [comment]
They use a custom manifest naming scheme. In custom source patterns text box, add the following
```
# Fix for gojopooltt
m3u8 /^https:\/\/gojopooltt\.su\/media\/playlist\.m3u8\.php/
```
