### ISSUE TITLE
jump to next video button | skip -/+x.sec button

### ISSUE THREAD

**Issue by bachig26** [Andrews54757/FastStream#6]
1. in case of YouTube, I just remembered that the `Jump to next video button` on default YT player is not available in FastStream.
if possible, i would really like to see it coming.

2. since most of the web player has the say, -/+ 10 sec button but it's not available in the FastStream. if feasible, please add an option in settings to customize the skip time.

**Comment by Andrews54757** [comment]
Jump to next video is not available because this is not available on all websites. To be able to have this option, I would need to interface with Youtube's API specifically in more intrusive ways. It is possible just for Youtube but it won't work for every other site.

**Comment by Andrews54757** [comment]
Custom seek step configuration was added in https://github.com/Andrews54757/FastStream/commit/609543aad9f15a09baf73606b8fbea8e463e5c27

Will be available in 1.1.20

**Comment by Andrews54757** [comment]
1.1.20 has been released. Approval may take several days.
