### ISSUE TITLE
[BUG] Audio and video without synchrony

### ISSUE THREAD

**Issue by WagnerQuetsia** [Andrews54757/FastStream#61]
**Describe the bug**
Some downloaded videos (FHD 1920x1080, 30 min or more and size over 500 MB) do not have audio and video synchronization. The audio is advanced.

**Version**
1.2.15

**Platform**
Google Chrome and Firefox

**Comment by Andrews54757** [comment]
Please provide the video

**Comment by Andrews54757** [comment]
So that I can debug it, can you send the buffer dump? You can obtain this by clicking the download button while holding down `SHIFT`

**Comment by WagnerQuetsia** [comment]
https://drive.google.com/file/d/1WugHk6dbX8ndxKnROWJnw23L3eIZk613/view?usp=sharing

Some other videos from the same website have the same problem, but not all.

**Comment by Andrews54757** [comment]
Fixed

**Comment by WagnerQuetsia** [comment]
Many thanks, Andrew! The best extension for me.

**Comment by Andrews54757** [comment]
No problem. Let me know if you find any other issues.

BTW: Buffer dumps can be played by dragging and dropping them onto the player. It will almost always work, even if the MP4 save doesn't.
