### ISSUE TITLE
[BUG] Missing quality selector for MP4 videos

### ISSUE THREAD

**Issue by ale5000-git** [Andrews54757/FastStream#62]
**Describe the bug**
Missing quality selector

**Version**
FastStream V1.2.16

**Platform**
Firefox

**Steps to Reproduce**
Sample link: drivejwplayer.xyz/embed/t5kwvgsw4rhqn-b?alt=7268
The original player has a quality selector but after being replaced by FastStream, it no longer allow to select quality.

**Comment by Andrews54757** [comment]
The provided stream doesn't use HLS, instead it is an MP4 file. As it is not actually a stream, FastStream cannot detect other qualities. Unfortunately, there is no way to reliably discover the mp4 files for the other qualities if the website uses a custom playlist loader.

**Comment by Andrews54757** [comment]
Note: You can still load FastStream with a different video quality if you enable FastStream after you select the quality you want in the website's default player.
