### ISSUE TITLE
[Feature] Add support for firefox for android

### ISSUE THREAD

**Issue by Dioswilson** [Andrews54757/FastStream#63]
I'd like to be able to install this extension on my android phon, but I realized it is not supported, I found [this](https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/) related documentation.

**Comment by Andrews54757** [comment]
Not for now. Too much scope creep for me to handle alone. Its already difficult to ensure that FastStream works flawlessly on both Chrome and Firefox desktop. Adding Android support will be the death of me. That said, please feel free to create a Pull Request if you make it work.
