### ISSUE TITLE
Possible to add change the font subtitle and add shadow border? 

### ISSUE THREAD

**Issue by Mioni** [Andrews54757/FastStream#64]
I'd love it if there was an option to change, the font for this video is Trebuchet MS.
Would it be possible to add this function?
Thank you!

![image](https://github.com/Andrews54757/FastStream/assets/6830783/fd0c90ca-d99d-46a3-8516-4d319a82395d)

**Comment by Andrews54757** [comment]
It's on my TODO list.

**Comment by Andrews54757** [comment]
Done
