### ISSUE TITLE
Theater mode

### ISSUE THREAD

**Issue by eeeeb** [Andrews54757/FastStream#67]
**Is your feature request related to a problem? Please describe.**
When watching a video with FastStream there is either 
* the sidebar with videos: https://imgur.com/VM3o4MI
* or a black area: https://imgur.com/IzNqN5S
The second one happens when watching a video with the default YT player in theater mode, then toggling FastStream on and then reloading the page. Or when I add YT to the Auto-enable URLs configuration.

**Describe the solution you'd like**
I would like to have a theater mode option which extends the video to the full width of the browser window.
Like the theater mode in the default YT player: https://imgur.com/WwcNy44

**Comment by Andrews54757** [comment]
Fixed

**Comment by eeeeb** [comment]
Thank you so much!
