### ISSUE TITLE
autoplay on enabling the extension

### ISSUE THREAD

**Issue by bachig26** [Andrews54757/FastStream#7]
either on YouTube or some other streaming site, when enabling the FastStream makes the player appear as paused.

i would really like to see that it autoplays the video on enabling the extension.

**Comment by Andrews54757** [comment]
It used to autoplay but that was disabled because some websites have hidden videos which may also be replaced by FastStream. Having an invisible video that plays in the background is not ideal.

**Comment by Andrews54757** [comment]
Autoplay was added back on just Youtube due to popular demand (can trust Youtube.com enough as a special exception) in V1.2.6 https://github.com/Andrews54757/FastStream/commit/cc3272bbcc8522136f41c1b4afde867316a11c30
