### ISSUE TITLE
settings can opening same time 

### ISSUE THREAD

**Issue by Ebrehe** [Andrews54757/FastStream#71]
![resim](https://github.com/Andrews54757/FastStream/assets/106402223/7314ea34-1f18-432b-9678-4f7b9c26d0d0)
when clicking other settings player looks mest up 
it must close automatic other setting 
(sorry for english)

**Comment by Andrews54757** [comment]
This is not a bug, I prefer UIs that stay open until you close it. Will think about it more though.

**Comment by ale5000-git** [comment]
I also think that it isn't nice like this, an alternative could be to detect the position of the currently opened one and open the new one in a different position in a way it doesn't overlap.

**Comment by Andrews54757** [comment]
Done. You all made me refactor InterfaceController.
