### ISSUE TITLE
why FastStream not working in https://tv1.terbit21.team/

### ISSUE THREAD

**Issue by candrapersada** [Andrews54757/FastStream#72]
why FastStream not working in https://tv1.terbit21.team/iron-man-2008/

**Comment by Andrews54757** [comment]
They use a custom playlist naming scheme, you must add this rule to the custom source patterns list:
```
# tv1.terbit21.team
m3u8 /^https:\/\/gdriveplayer\.to\/hlsnew2\.php\?.*\.m3u8/
```

**Comment by candrapersada** [comment]
not working

**Comment by Andrews54757** [comment]
Works for me. Please see the wiki https://github.com/Andrews54757/FastStream/wiki/Custom-Source-Patterns for more information
