### ISSUE TITLE
[BUG] Volume Slider not working

### ISSUE THREAD

**Issue by nilsgng** [Andrews54757/FastStream#73]
**Describe the bug**
I cant drag the volume slider on youtube (havent tested on other sites).
Bug first occured a couple days ago for the first time, hasnt worked since

**Version**
1.2.19

**Platform**
Firefox 115.7.0esr (64-bit)

**Steps to Reproduce**
Im opening any youtube video, enabling the extension and the volume slider does not work

**Comment by Andrews54757** [comment]
Fixed!
