### ISSUE TITLE
Choose download quality

### ISSUE THREAD

**Issue by kolbdog3333** [Andrews54757/FastStream#74]
This isn't really a bug but i was wondering how you can choose the download qualtiy when clicking save video do you need to reset the video before you save the video when choosing the video resolution or like i want to save the hd video but it saves the lower quality instead?

**Comment by kolbdog3333** [comment]
Also in an unrelated question how do you extract the buffer from the .fsa file

**Comment by Andrews54757** [comment]
It saves the quality you are watching. If you select the HD quality it will save that stream.

**Comment by Andrews54757** [comment]
Note: There is an exception with saving videos from Youtube. When the stream isn't mp4 compatible, Youtube downloads are handled by Youtube.js. It gets the best available mp4 quality, but this may not be 4k. See:

https://github.com/Andrews54757/FastStream/blob/828b71c1fe7631660f0e5c9b4d2de91d39154ff8/chrome/player/players/yt/YTPlayer.mjs#L240-L259
