### ISSUE TITLE
[Feature] Add for Sync

### ISSUE THREAD

**Issue by jbgy** [Andrews54757/FastStream#75]
**Is your feature request related to a problem? Please describe.**
If I setup a new pc or anything, i wish i had a function to sync, like some other extensions do... maybe to make it as a firefox sync thing or so

**Describe the solution you'd like**
There should be a option to sync your option with your firefox acount

**Additional context**
none

**Comment by Andrews54757** [comment]
You can export your settings as a file, share the file, and the import it on your other computer.
