### ISSUE TITLE
Mono audio only plays through the left speakers

### ISSUE THREAD

**Issue by RNavarro3000** [Andrews54757/FastStream#78]
**Is your feature request related to a problem? Please describe.**
People still release videos with mono audio. Watching them with FastStream produces audio in only the left channel. If you disable FastStream temporarily, you can see the sites default media player does this auto map.

**Describe the solution you'd like**
An option to auto map mono audio to both the Left and Right channels if found in a video would be great.

**Describe alternatives you've considered**
Here is the video I'm testing against:  https://twitter.com/SERobinsonJr/status/1758626994093281457

**Additional context**

**Comment by Andrews54757** [comment]
I can't reproduce this on either Chrome or Firefox. It correctly up mixes the audio for me. Please specify what browser you are using, hardware, and operating system.

**Comment by RNavarro3000** [comment]
Both browsers exhibit the same issue:
Windows 7 Pro 64bit
Intel i7-4790K 32GB
Firefox 115.7.0esr
Waterfox G6.0.8

**Comment by Andrews54757** [comment]
I've refactored the audio graph https://github.com/Andrews54757/FastStream/commit/a8b4f0aab4da5e2906a62e73849861967de5fe7e

Can you test if it works? You need to do a manual install. (you can also test by using the web-based player https://faststream.online/player/)

**Comment by RNavarro3000** [comment]
Used the web player (says it's 1.2.21, does it contain the code change?).  Still mono for me.

**Comment by Andrews54757** [comment]
That is very weird. It shows activity in both channels for me:
<img width="1512" alt="Screenshot" src="https://github.com/Andrews54757/FastStream/assets/13282284/3a48f2c0-7eaf-4514-91d9-d65778dad6ee">

**Comment by RNavarro3000** [comment]
When I compared your audio configuration snapshot to mine, I noticed I had no audio showing on the EQ beyond 10khz for the entire clip, but yours goes out to about 13khz. Got me thinking, are we playing the same file?

![screenshot 156](https://github.com/Andrews54757/FastStream/assets/121646/c1c52e58-e68f-40be-9de4-e37c8c19ae7f)

Probing the m3u8, there are three video options and three audio options:

audio-32000-Audio - 32k bit rate, **single** channel audio, channel layout is C (center?), clipped around 9.5khz
audio-64000-Audio - 64k bit rate, **dual** channel audio, channel layout is L R, clipped around 13khz
audio-128000-Audio -  128k bit rate, **dual** channel audio, channel layout is L R, clipped around 15khz

![screenshot 160](https://github.com/Andrews54757/FastStream/assets/121646/489f0f95-7f2a-4c60-a93b-90724ce0546c)
![screenshot 161](https://github.com/Andrews54757/FastStream/assets/121646/54775385-ad51-4380-9a10-4a2d05040d1b)
![screenshot 162](https://github.com/Andrews54757/FastStream/assets/121646/888373ff-198f-44e7-9199-835b1043942c)

When I download the video through FastStream 1.2.21, there was no ability to change quality for this file, so what I get is 320x690 with 32kb audio. That should explain why I get mono audio. I'm guessing you're getting the 64 or 128 stereo stream when you test.

![screenshot 159](https://github.com/Andrews54757/FastStream/assets/121646/b60a8a42-ba69-48ce-bfd8-3e039d72b76f)

**Comment by Andrews54757** [comment]
Thanks for investigating! I was able to reproduce the issue by forcing the lower quality stream.

BTW: You can choose the quality level of the download by changing the quality you are watching (the little SD/HD button).

**Comment by RNavarro3000** [comment]
I do see the quality icon for some videos, just not this one. See the first screenshot of my last reply up above, which confirms this.

**Comment by Andrews54757** [comment]
Fixed. I must note though that the WebAudio API is incredibly dumb.
1. ChannelSplitterNode assigns mono output to index 0, which corresponds to SPEAKER_FRONT_LEFT. It should correspond with index 2 (SPEAKER_FRONT_CENTER)
![image](https://github.com/Andrews54757/FastStream/assets/13282284/52f81006-7ea3-42fb-afe6-709b366c4afc)
2. There is no way to determine how many channels are available.
3. Smart upmixing/downmixing (depending on number of channels of input/output) doesn't occur at any other node besides the `Panner` and `StereoPanner` nodes.

The solution:
1. Connect input to a `StereoPanner` node with `channelInterpretation` set to `discrete`. This ensures that mono is upmixed to stereo before going through any other node, while ensuring that downmixing doesn't occur if source has more than 2 channels.
2. Connect input to a `ChannelSplitter` node with 6 channels. Connect the 4 other channels to a `ChannelSplitter`. Don't connect the Left and Right channels. This effectively removes only the Left and Right channels.
3. Connect `StereoPanner` and `ChannelMerger` to next node in process.

**Comment by Andrews54757** [comment]
I've updated the website. Clear you cache and try it again. It should work this time.

![image](https://github.com/Andrews54757/FastStream/assets/13282284/045498f2-82df-4903-ab7d-2e5b09c2008b)

**Comment by RNavarro3000** [comment]
Web player is working for me now. Mono audio now maps to LR.  **_Many thanks!_**
