### ISSUE TITLE
[Feature] Theater mode button like in default youtube player

### ISSUE THREAD

**Issue by Player505** [Andrews54757/FastStream#80]
**Is your feature request related to a problem? Please describe.**
I have set auto-enable for youtube.com/watch but there is no theater mode option in the player 

**Describe the solution you'd like**
An additional button like the ones in the default youtube player to set theater mode.

**Describe alternatives you've considered**
Using [Theater Mode for YouTube™](https://addons.mozilla.org/en-GB/firefox/addon/theater-mode-for-youtube/) plugin lets me set theater mode by default but switching between normal player and theater mode still requires I disable FastStream first.

**Additional context**
This seems related to issue #67 but that issue is marked as closed?

**Comment by Andrews54757** [comment]
This isn't possible because Youtube moves the video element around in the DOM tree when enabling theater mode. As FastStream is loaded in an iframe, this will mean the player will have to reload the video every time you toggle theatre mode.

**Comment by Player505** [comment]
For anyone else coming to this issue to enable theatre mode by default, the above mentioned plugin doesn't work.
Instead you should run `document.cookie = 'wide=1; expires='+new Date('3099').toUTCString()+'; path=/';` in the browser console.
[Referance](https://www.reddit.com/r/youtube/comments/36v3aj/how_can_i_make_theater_mode_the_default/)
