### ISSUE TITLE
[Feature] Requesting to be uploaded on edge addon store and also make it compatible (like media player of samsung browser) with edge browser mobile since now edge supports addons on mobile.

### ISSUE THREAD

**Issue by ghost** [Andrews54757/FastStream#81]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] no

**Describe the solution you'd like**
Mobile browsers and video playback in browsers on mobile is horrible and not user friendly as it is on desktop. Some browsers like samsung browser, cococ browser, banana browser on mobile have made it easily through media features of video playback (not limited to youtube but to any video played whether it is from cloud or youtube alternative sites) but cannot be used to due lack of sync and cross device usage. So, requesting to be uploaded on edge addon store and also make it compatible (like media player of samsung browser) with edge browser mobile since now edge supports addons on mobile.

**Describe alternatives you've considered**
Actually, there isnt any. But using samsung browser, cococ browser, banana browser.

**Additional context**
Not much. Just want this addon on edge addon store so that chrome doesnt force us to use chrome for addons from its store and once it is on edge, it will be usable on edge mobile with addons support option.

**Comment by Andrews54757** [comment]
See https://github.com/Andrews54757/FastStream/issues/63

> Not for now. Too much scope creep for me to handle alone. Its already difficult to ensure that FastStream works flawlessly on both Chrome and Firefox desktop. Adding Android support will be the death of me. That said, please feel free to create a Pull Request if you make it work.

**Comment by ghost** [comment]
Excellent. Now there is no reason to use this. Thanks.
