### ISSUE TITLE
[Feature] Save volume from previous play

### ISSUE THREAD

**Issue by Player505** [Andrews54757/FastStream#82]
**Is your feature request related to a problem? Please describe.**
Depending on what I'm simultaneously doing while watching a video I change the volume but this change doesn't persist whenever I load a new video.

**Describe the solution you'd like**
When I change volume I would like the percentage to persist when loading a view video.

**Describe alternatives you've considered**
Changing the browser window volume but that changes the volume for the whole browser and not specifically the video I'm playing. In issue #48 you mentioned that you can change the default volume level by setting an audio profile in the audio config window however I only see the abbility to change the gain, not the volume percentage.

**Comment by Andrews54757** [comment]
Gain is a more precise way of adjusting volume using a [decibel scale](https://en.wikipedia.org/wiki/Decibel). You can convert between decibels to volume percentage using the following equation:

```
Percentage =  100% * 10^(dB/20)
dB = log10(Percentage / 100%) / 20
```
