### ISSUE TITLE
[Feature] Youtube comment timestamps

### ISSUE THREAD

**Issue by blox11** [Andrews54757/FastStream#83]
**Is your feature request related to a problem? Please describe.**
When a comment features a specific time interval in the video, it can be clicked on and the player jumps to it.

**Describe the solution you'd like**
Support for similar feature.

**Describe alternatives you've considered**

**Additional context**
If possible

**Comment by Andrews54757** [comment]
I'll think about it. There might be a way. However, the current architecture will make it difficult.

**Comment by Andrews54757** [comment]
Done https://github.com/Andrews54757/FastStream/commit/ea7c8f812dba05df074907559c54716192982963
