### ISSUE TITLE
[Feature] Ability to disable native youtube player

### ISSUE THREAD

**Issue by blox11** [Andrews54757/FastStream#84]
**Is your feature request related to a problem? Please describe.**
Disabling the Youtube player from loading and buffering altogether. I think it should help with page load speeds and unnecessary background bandwidth usage, but also because disabling autoplay in the browser sometimes fails and the youtube video plays anyways.

**Describe the solution you'd like**
Disable/stop youtube player

**Describe alternatives you've considered**
Enhancer for youtube has a similar feature, especially the "completely stop video ".
![Screenshot 2024-02-21 004833](https://github.com/Andrews54757/FastStream/assets/160701606/818b87b8-665e-4345-b3a2-d9a8c05fc9ec)

**Additional context**

**Comment by Andrews54757** [comment]
Does the Youtube player play with FastStream enabled? do you hear two videos play on top of each other?

**Comment by blox11** [comment]
It can happen on occasion that when the page loads the youtube video plays. I have to use a separate extension to keep it from playing entirely. Also, greetings from youtube, I'm blox117 from a few months ago

**Comment by Andrews54757** [comment]
What browser are you on? FastStream should stop the video from playing if it is enabled.

**Comment by blox11** [comment]
Vivaldi

**Comment by Andrews54757** [comment]
Have you tested it on Chrome or Firefox?

**Comment by blox11** [comment]
I haven't tested it extensively, vivaldi is my main browser. But from a quick test it appears to work fine. On vivaldi it works most of the time, but it can allow the regular youtube player to run for a few seconds. It could just be an issue specific to my installation though. I do know that, with the enhancer for youtube extension enabled and the completely stop checkbox enabled it goes away.
