### ISSUE TITLE
[BUG] Youtube doesn't work, shows error

### ISSUE THREAD

**Issue by blox11** [Andrews54757/FastStream#86]
**Describe the bug**
Player fails to load. Right now for some reason it doesn't work at all?

**Version**
1.2.22

**Platform**
Edge, Firefox, Vivaldi, Opera. Tested on 2 different machines, windows 11 and ubuntu

**Steps to Reproduce**
All youtube videos new, refreshed, direct links.
![Screenshot 2024-02-21 184515](https://github.com/Andrews54757/FastStream/assets/160701606/254bfa1c-85b3-4a4b-8633-4dfad89583cc)

**Comment by blox11** [comment]
I looked on odyssey and the player seems to work, so I think it has something to do with youtube servers.

**Comment by Andrews54757** [comment]
Very weird. Especially since the error message is "undefined". Can you update to latest commit by installing it manually? The error should show properly then.

**Comment by Andrews54757** [comment]
Okay, I figured it out. I think Youtube has changed their API

**Comment by Andrews54757** [comment]
https://github.com/LuanRT/YouTube.js/issues/602

**Comment by blox11** [comment]
Yeah I figured as much, it didn't seem to work no matter what until I went to a different site. I was wondering if youtube is trying to block the usage for extensions like yours as well.

**Comment by Andrews54757** [comment]
Issue tracker on YoutubeJS: https://github.com/LuanRT/YouTube.js/issues/602

Confirmed by users of freetube: https://github.com/FreeTubeApp/FreeTube/issues/4700

**Comment by Andrews54757** [comment]
Fixed in 1.2.23

**Comment by Andrews54757** [comment]
V1.2.23 has been published for both Chrome and Firefox! Approval only took 2 hours! A new record!

**Comment by blox11** [comment]
Nice! 👍
