### ISSUE TITLE
[BUG] Faststream causes Odysee.com errors

### ISSUE THREAD

**Issue by blox11** [Andrews54757/FastStream#87]
**Describe the bug**
When faststream extension is on for odysee.com, and you move from one video to the next (i.e. recommended video or clicking to go to the main page) there is an error message.

**Version**
1.2.22

**Platform**
Vivaldi, Edge, Firefox

**Steps to Reproduce**
It happens basically any time you move around on the odysee website with the extension set to on. Refreshing the page will remove the error message 
![Screenshot 2024-02-21 202528](https://github.com/Andrews54757/FastStream/assets/160701606/b00ed8e2-a2ec-47a8-8f40-bfd98e151fcd)

**Comment by Andrews54757** [comment]
Fixed

**Comment by Andrews54757** [comment]
Note: the back button will still break the site. this is unavoidable for now.
