### ISSUE TITLE
[Feature] A-B Repeat Option

### ISSUE THREAD

**Issue by Brasolis** [Andrews54757/FastStream#90]
**Is your feature request related to a problem? Please describe.**
Not related to a problem, just a feature I'd like.

**Describe the solution you'd like**
I feature I really like in VLC is the A-B repeat feature, where you can specify a start and end point that the player will automatically replay that marked segment on a loop, would it be possible to add?

**Comment by Andrews54757** [comment]
I will implement this once I add custom context menus to the player

**Comment by Brasolis** [comment]
Sounds great, thanks for your work.

**Comment by Andrews54757** [comment]
Done
