### ISSUE TITLE
Many disk read/writes on Vivaldi

### ISSUE THREAD

**Issue by phanam** [Andrews54757/FastStream#91]
OS: MacOS Monterey latest, Browser: Vivaldi latest

When looking at my SSD allocation, I noticed that the blob_storage folder (here located under ~/Library/Application Support/Vivaldi/default/blob_storage had reached a whopping 40Gb. While this is not too much a problem having an 1TB internal disk size, the amount of read/writes that are performed will probably wear out the SSD fast. I have moved the browser cache already to RAM to avoid this but for streaming purposes that is impossible so far.
Would it be possible to add the possibility to define the folder that FastStream downloads its blobs to? That way I could set it either to RAM or an external SSD of which I don't care if it wears out.
This issue is pronounced by that fact that every new version of FastStream again sets the default to "Predownload entire video ..".

Remark: I noticed that another extension made it even worse and that was the VideoResumer which prevents the blob_storage from being cleaned on restart of the browser. That extension needs to be deactivated of course.

Many thanks for considering. And it is a great tool you wrote .. thank you for this, too.

**Comment by Andrews54757** [comment]
40GB is excessive. Are you loading a really long video? Blobs should be discarded after each use.

Blobs are managed by the browser, not FastStream. Normally, the browser will create blobs in RAM and then move them to disk when theres no space left. FastStream shouldn't cause that many SSD read/writes unless the video is really long.

**Comment by Andrews54757** [comment]
It is possible that there is a bug with Vivaldi specifically that prevents blobs from being unloaded correctly. Try to reproduce the issue with Chrome.

**Comment by phanam** [comment]
Thank you for your analysis! 
Indeed, I often watch gaming live streams on Twitch which can take up to 7 hours @6407kbps which amount to about 20Gb per video when downloaded fully. I was not aware that this might not be the usual use case. But understandable now why "Download entire video" as a default might be problematic. Maybe a setting to download the entire video up to a certain size would be possible. It certainly would help me.
And you might be correct with Vivaldi. The tab stacks are a godsend, but the bloat around it makes it more buggy than naked Chrome.
I will observe the behaviour further and comment again if anything stands out.

**Comment by Andrews54757** [comment]
Implemented video size limit option.
