### ISSUE TITLE
[Feature] Hide Controls quickly when moused off of the video

### ISSUE THREAD

**Issue by wiviw5** [Andrews54757/FastStream#93]
**Feature suggestion:**
The default of YouTube's Controls is to instantly hide when moused off of the video, and its a feature I'd like in this player as well.

**Solution:**
A speed setting or simple toggle for almost instant player controls in the options menu to hide them when moused off would be a great place for this.

**Comment by Andrews54757** [comment]
FastStream should now instantly hide the controls when moused off
