### ISSUE TITLE
[Feature] Collect sources toggle.

### ISSUE THREAD

**Issue by wiviw5** [Andrews54757/FastStream#94]
In FastStream, opening the player in a new tab is always collecting new sources, if there was a toggle globally in the options menu along with a per tab player toggle so sources lists could be kept concise this would be appreciated.

**Comment by Andrews54757** [comment]
Implemented a per-tab toggle. [Click icon to disable source collection on new tab player](https://github.com/Andrews54757/FastStream/commit/9c725042aaa7561d2bdad6aad4a2e16bb9d23ee8)
