### ISSUE TITLE
[Feature] 2x playback speed hold action

### ISSUE THREAD

**Issue by Ticha22608** [Andrews54757/FastStream#95]
**Feature request:**
A feature I use regularly with the default YouTube player is the newly added hold-to-2x speed feature where, if you hold-click the video player, the video will play at 2x speed.

**Solution:**
It'd be cool if this was an optional feature in FastStream. Something that the normal YouTube player doesn't do is accelerate the video past 2x - for example, if I'm playing a video at 2x and I hold the player, it will not play at 4x. This isn't necessary, but it would be nice if there was a toggle to play the video 2x faster than the currently selected option (e.g. 1.25x -> 3.25x, 2x -> 4x, etc.).

**Demonstration of the described behavior in the default YouTube player**
https://github.com/Andrews54757/FastStream/assets/40746497/2eb43cf8-1943-41f8-ae50-9add502e4551
- If the video is playing, the hold action will change the current playback speed to 2x
   - Letting go will keep playing the video, but it'll revert to playing at the chosen playback speed in settings 
- If the video is paused, the hold action will unpause the video and play it at 2x speed. 
   - Letting go will, once again, pause the video. 
   - When the video is manually unpaused, it'll keep playing at the chosen playback speed.

**Comment by Andrews54757** [comment]
Implemented.
