### ISSUE TITLE
[BUG] 2x speed hold action doesn't work correctly with single-click actions

### ISSUE THREAD

**Issue by Ticha22608** [Andrews54757/FastStream#96]
**Describe the bug**
First of all, I'd like to thank the developer for adding my suggestion ( https://github.com/Andrews54757/FastStream/issues/95 ) in today's update. Unfortunately, it doesn't behave too well with single-click actions.
When letting go of the player, it will revert to the normal speed, but it will also trigger whatever your single-click action shortcut is. For example, if my single-click action is play/pause, and I'm playing the video before I start the hold action, it will pause the video at the end of the hold action. However, if I'm not playing the video, and I begin the hold action, it will unpause the video when I let go of the mouse button.
Note: this bug only occurs if the cursor remains above the player when the hold action ends. This is because moving the cursor away from the player will stop registering the hold action entirely.

**Version**
v1.2.25

**Platform**
Brave 1.63.165 (Chromium 122.0.6261.94)

**Steps to Reproduce**
1. Enable the player
2. Set a single-click action
3. Hold the mouse button with the cursor on the player
4. Let go of the mouse button

**Comment by Andrews54757** [comment]
Fixed. I really need to refactor the user event code

**Comment by Ticha22608** [comment]
> Fixed. I really need to refactor the user event code

lol. it's alright man, thanks for the bug fix. loving the extension and your dedication
