### ISSUE TITLE
[Feature] Shortcut to skip to the beginning of YouTube chapters

### ISSUE THREAD

**Issue by Ticha22608** [Andrews54757/FastStream#97]
**Feature**
Like the vanilla YouTube player, FastStream should have a keybind/combination (ctrl + arrow keys is the default on YouTube) to skip to the beginning of video chapters. Also, it'd be handy if it showed the name of the chapter in the player, like the YouTube player does.

**Comment by Andrews54757** [comment]
FastStream already shows the name of the chapter in the player.
![image](https://github.com/Andrews54757/FastStream/assets/13282284/9e329af8-4e39-4db2-a817-b9599ae67797)

I'll add a keybind later when I have time.

**Comment by Ticha22608** [comment]
oh oops. i didn't see that. thanks for replying. by the way, apologies for asking for so much in such a short period of time. hope it's not a bother

**Comment by Andrews54757** [comment]
Done
