### ISSUE TITLE
[BUG]  - Fragment failed

### ISSUE THREAD

**Issue by Perdoado** [Andrews54757/FastStream#98]
Descriptioin of the issue:
Very often it shows the message '1 Fragment Failed: Click to Retry', but clicking never fixes it and when the playback reaches the second with the missing fragment, the video stops and never plays again, while the message 'Loading...' is permanently showed. 

**Version**
Version: 1.2.25.1

**Platform**
Microsoft Edge

**Steps to Reproduce**
Play this video: https://binged.in/watch/movie/792307

**Comment by Andrews54757** [comment]
This is not a bug with the software. It means that their servers are not sending the required fragment. Contact the owners of the server if you continue to have this issue.

**Comment by Perdoado** [comment]
I see. But it happens in many different servers. Would it be possible to make FastStream skip the fragment missing instead of stop working?

**Comment by Andrews54757** [comment]
I've fixed a bug where the HLS player stops loading after a failed fragment
