### ISSUE TITLE
Frame forward Keybinds

### ISSUE THREAD

**Issue by Nvertd** [Andrews54757/FastStream#99]
Add keybinds that allows user to step forward or backwards one frame at a time (if the video is paused). This is a stock feature on Youtube and i think its very usefull.

**Comment by Andrews54757** [comment]
The [seekToNextFrame](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/seekToNextFrame) method has been deprecated.

Note: you can use the SeekForwardsSmall keybind to seek 0.2 seconds forwards/back.

**Comment by Nvertd** [comment]
@Andrews54757 Yes I know about the SeekForwardsSmall. However 0.2 seconds is 6 frames if video is 30fps. There are circumstances where viewing videos frame by frames are convenient. For example, reviewing sports videos, studying animations, finding the single frame easter eggs some youtubers put in there videos.

**Comment by Andrews54757** [comment]
Done. It is now 1/30 step.
